-- GULI LINGERIE commerce foundation.
-- Safe to run after the existing orders/telegram_users migration.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text not null default '',
  price numeric(12,2) not null default 0 check (price >= 0),
  old_price numeric(12,2) check (old_price is null or old_price >= 0),
  image text not null default '',
  images jsonb not null default '[]'::jsonb,
  sizes jsonb not null default '[]'::jsonb,
  colors jsonb not null default '[]'::jsonb,
  rating numeric(3,2) not null default 0 check (rating >= 0 and rating <= 5),
  reviews integer not null default 0 check (reviews >= 0),
  stock integer not null default 0 check (stock >= 0),
  featured boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_products_active_category
  on public.products (active, category, sort_order);

create index if not exists idx_products_featured
  on public.products (featured, active);

create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text not null check (discount_type in ('percent', 'fixed')),
  discount_value numeric(12,2) not null check (discount_value > 0),
  min_order_amount numeric(12,2) not null default 0 check (min_order_amount >= 0),
  usage_limit integer check (usage_limit is null or usage_limit > 0),
  used_count integer not null default 0 check (used_count >= 0),
  starts_at timestamptz,
  expires_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_promo_codes_active
  on public.promo_codes (active, code);

create table if not exists public.saved_addresses (
  id bigint generated by default as identity primary key,
  telegram_id bigint,
  username text,
  phone text,
  label text default 'Uy',
  latitude double precision not null,
  longitude double precision not null,
  region text,
  district text,
  street text,
  house text,
  apartment text,
  landmark text,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_saved_addresses_telegram_id
  on public.saved_addresses (telegram_id);

-- Keep existing orders compatible while adding production-friendly fields.
alter table public.orders add column if not exists telegram_id bigint;
alter table public.orders add column if not exists username text;
alter table public.orders add column if not exists first_name text;
alter table public.orders add column if not exists telegram_phone text;
alter table public.orders add column if not exists items jsonb;
alter table public.orders add column if not exists subtotal numeric(12,2) default 0;
alter table public.orders add column if not exists delivery numeric(12,2) default 0;
alter table public.orders add column if not exists discount numeric(12,2) default 0;
alter table public.orders add column if not exists total numeric(12,2) default 0;
alter table public.orders add column if not exists address jsonb;
alter table public.orders add column if not exists payment text default 'cash';
alter table public.orders add column if not exists status text default 'Qabul qilindi';
alter table public.orders add column if not exists created_at timestamptz default now();
alter table public.orders add column if not exists updated_at timestamptz default now();

create index if not exists idx_orders_telegram_id
  on public.orders (telegram_id);

create index if not exists idx_orders_status_created_at
  on public.orders (status, created_at desc);

-- RLS is enabled for client safety. The backend uses the Supabase secret key.
alter table public.products enable row level security;
alter table public.promo_codes enable row level security;
alter table public.saved_addresses enable row level security;

-- Public catalog is intentionally readable only when active.
drop policy if exists products_public_read on public.products;
create policy products_public_read
  on public.products
  for select
  using (active = true);

-- Public clients must not write catalog/promo data directly.
