-- GULI LINGERIE commerce foundation.
-- IMPORTANT: if public.products already existed before this file,
-- run supabase/repair_existing_schema.sql first.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text not null default '',
  price numeric(12,2) not null default 0 check (price >= 0),
  old_price numeric(12,2) check (old_price is null or old_price >= 0),
  image text not null default '',
  images jsonb not null default '[]'::jsonb,
  sizes jsonb not null default '[]'::jsonb,
  colors jsonb not null default '[]'::jsonb,
  rating numeric(3,2) not null default 0 check (rating >= 0 and rating <= 5),
  reviews integer not null default 0 check (reviews >= 0),
  stock integer not null default 0 check (stock >= 0),
  featured boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products add column if not exists description text default '';
alter table public.products add column if not exists price numeric(12,2) default 0;
alter table public.products add column if not exists old_price numeric(12,2);
alter table public.products add column if not exists image text default '';
alter table public.products add column if not exists images jsonb default '[]'::jsonb;
alter table public.products add column if not exists sizes jsonb default '[]'::jsonb;
alter table public.products add column if not exists colors jsonb default '[]'::jsonb;
alter table public.products add column if not exists rating numeric(3,2) default 0;
alter table public.products add column if not exists reviews integer default 0;
alter table public.products add column if not exists stock integer default 0;
alter table public.products add column if not exists featured boolean default false;
alter table public.products add column if not exists active boolean default true;
alter table public.products add column if not exists sort_order integer default 0;
alter table public.products add column if not exists created_at timestamptz default now();
alter table public.products add column if not exists updated_at timestamptz default now();
update public.products set active = true where active is null;
create index if not exists idx_products_active_category on public.products (active, category, sort_order);
create index if not exists idx_products_featured on public.products (featured, active);

create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text not null check (discount_type in ('percent', 'fixed')),
  discount_value numeric(12,2) not null check (discount_value > 0),
  min_order_amount numeric(12,2) not null default 0 check (min_order_amount >= 0),
  usage_limit integer check (usage_limit is null or usage_limit > 0),
  used_count integer not null default 0 check (used_count >= 0),
  starts_at timestamptz,
  expires_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists idx_promo_codes_active on public.promo_codes (active, code);

create table if not exists public.saved_addresses (
  id bigint generated by default as identity primary key,
  telegram_id bigint,
  username text,
  phone text,
  label text default 'Uy',
  latitude double precision not null,
  longitude double precision not null,
  region text,
  district text,
  street text,
  house text,
  apartment text,
  landmark text,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_saved_addresses_telegram_id on public.saved_addresses (telegram_id);

alter table public.orders add column if not exists telegram_id bigint;
alter table public.orders add column if not exists username text;
alter table public.orders add column if not exists first_name text;
alter table public.orders add column if not exists telegram_phone text;
alter table public.orders add column if not exists items jsonb;
alter table public.orders add column if not exists subtotal numeric(12,2) default 0;
alter table public.orders add column if not exists delivery numeric(12,2) default 0;
alter table public.orders add column if not exists discount numeric(12,2) default 0;
alter table public.orders add column if not exists total numeric(12,2) default 0;
alter table public.orders add column if not exists address jsonb;
alter table public.orders add column if not exists payment text default 'cash';
alter table public.orders add column if not exists status text default 'Qabul qilindi';
alter table public.orders add column if not exists created_at timestamptz default now();
alter table public.orders add column if not exists updated_at timestamptz default now();
create index if not exists idx_orders_telegram_id on public.orders (telegram_id);
create index if not exists idx_orders_status_created_at on public.orders (status, created_at desc);

-- One transaction owns the complete checkout: price calculation, stock decrement,
-- promo usage increment, and order insert. The service role calls this through RPC.
create or replace function public.create_secure_order(p_order jsonb, p_telegram_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item jsonb;
  v_product record;
  v_qty integer;
  v_subtotal numeric(12,2) := 0;
  v_delivery numeric(12,2) := greatest(0, coalesce((p_order->>'delivery')::numeric, 0));
  v_discount numeric(12,2) := 0;
  v_total numeric(12,2);
  v_promo record;
  v_promo_code text := upper(trim(coalesce(p_order->>'promo_code','')));
  v_items jsonb := '[]'::jsonb;
  v_order_number text := p_order->>'order_number';
  v_existing jsonb;
  v_new_item jsonb;
begin
  if p_telegram_id is null then raise exception 'Telegram foydalanuvchisi aniqlanmadi'; end if;
  if jsonb_typeof(p_order->'items') <> 'array' or jsonb_array_length(p_order->'items') = 0 or jsonb_array_length(p_order->'items') > 100 then
    raise exception 'Buyurtma mahsulotlari noto‘g‘ri';
  end if;

  if v_order_number is not null and v_order_number <> '' then
    select to_jsonb(o) into v_existing from public.orders o where o.order_number = v_order_number and o.telegram_id = p_telegram_id limit 1;
    if v_existing is not null then return v_existing; end if;
  end if;

  for v_item in select value from jsonb_array_elements(p_order->'items') loop
    v_qty := coalesce((v_item->>'quantity')::integer, (v_item->>'qty')::integer, 1);
    if v_qty < 1 or v_qty > 99 then raise exception 'Mahsulot miqdori noto‘g‘ri'; end if;

    if v_item->'product'->>'id' is not null then
      select * into v_product from public.products p where p.id = (v_item->'product'->>'id')::bigint for update;
    elsif v_item->>'product_id' is not null then
      select * into v_product from public.products p where p.id = (v_item->>'product_id')::bigint for update;
    else
      select * into v_product from public.products p where p.product_code = coalesce(v_item->'product'->>'product_code', v_item->>'product_code') for update;
    end if;

    if not found then raise exception 'Mahsulot topilmadi'; end if;
    if not v_product.active then raise exception '% hozir sotuvda emas', coalesce(v_product.name, v_product.title, 'Mahsulot'); end if;
    if v_product.stock < v_qty then raise exception '% uchun omborda yetarli qoldiq yo‘q', coalesce(v_product.name, v_product.title, 'Mahsulot'); end if;

    v_subtotal := v_subtotal + (v_product.price * v_qty);
    v_new_item := v_item || jsonb_build_object(
      'quantity', v_qty,
      'product_id', v_product.id,
      'product_code', v_product.product_code,
      'product', coalesce(v_item->'product','{}'::jsonb) || jsonb_build_object(
        'id', v_product.id,
        'product_code', v_product.product_code,
        'name', coalesce(v_product.name, v_product.title, 'Mahsulot'),
        'price', v_product.price,
        'old_price', v_product.old_price,
        'stock', v_product.stock
      )
    );
    v_items := v_items || jsonb_build_array(v_new_item);
    update public.products set stock = stock - v_qty, updated_at = now() where id = v_product.id;
  end loop;

  if v_promo_code <> '' then
    select * into v_promo from public.promo_codes p where upper(p.code) = v_promo_code for update;
    if not found or not v_promo.active then raise exception 'Promo kod topilmadi yoki faol emas'; end if;
    if v_promo.starts_at is not null and v_promo.starts_at > now() then raise exception 'Promo kod hali kuchga kirmagan'; end if;
    if v_promo.expires_at is not null and v_promo.expires_at < now() then raise exception 'Promo kod muddati tugagan'; end if;
    if v_promo.usage_limit is not null and v_promo.used_count >= v_promo.usage_limit then raise exception 'Promo koddan foydalanish limiti tugagan'; end if;
    if v_subtotal < v_promo.min_order_amount then raise exception 'Minimal buyurtma % so‘m', v_promo.min_order_amount; end if;
    if v_promo.discount_type = 'percent' then v_discount := least(v_subtotal, round(v_subtotal * v_promo.discount_value / 100));
    else v_discount := least(v_subtotal, greatest(0, v_promo.discount_value)); end if;
    update public.promo_codes set used_count = used_count + 1 where id = v_promo.id;
  end if;

  v_total := greatest(0, v_subtotal + v_delivery - v_discount);
  if v_order_number is null or v_order_number = '' then v_order_number := 'GULI-' || lpad((floor(random()*900000)+100000)::int::text, 6, '0'); end if;

  insert into public.orders(order_number, telegram_id, username, first_name, phone, telegram_phone, items, subtotal, delivery, discount, total, address, payment, status, created_at, updated_at)
  values (v_order_number, p_telegram_id, nullif(p_order->>'username',''), nullif(p_order->>'first_name',''), nullif(p_order->>'phone',''), null, v_items, v_subtotal, v_delivery, v_discount, v_total, p_order->'address', coalesce(nullif(p_order->>'payment',''),'cash'), coalesce(nullif(p_order->>'status',''),'Qabul qilindi'), coalesce(nullif(p_order->>'created_at','')::timestamptz, now()), now())
  returning to_jsonb(orders.*) into v_existing;
  return v_existing;
exception when unique_violation then
  select to_jsonb(o) into v_existing from public.orders o where o.order_number = v_order_number and o.telegram_id = p_telegram_id limit 1;
  if v_existing is not null then return v_existing; end if;
  raise;
end;
$$;

grant execute on function public.create_secure_order(jsonb, bigint) to service_role;

alter table public.products enable row level security;
alter table public.promo_codes enable row level security;
alter table public.saved_addresses enable row level security;
drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products for select using (active = true);
