-- GULI LINGERIE commerce foundation. Run this after repair_existing_schema.sql on legacy databases.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text not null default '',
  price numeric(12,2) not null default 0 check (price >= 0),
  old_price numeric(12,2) check (old_price is null or old_price >= 0),
  image text not null default '', images jsonb not null default '[]'::jsonb,
  sizes jsonb not null default '[]'::jsonb, colors jsonb not null default '[]'::jsonb,
  rating numeric(3,2) not null default 0 check (rating >= 0 and rating <= 5), reviews integer not null default 0 check (reviews >= 0),
  stock integer not null default 0 check (stock >= 0), featured boolean not null default false, active boolean not null default true,
  sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.products add column if not exists description text default '';
alter table public.products add column if not exists price numeric(12,2) default 0;
alter table public.products add column if not exists old_price numeric(12,2);
alter table public.products add column if not exists image text default '';
alter table public.products add column if not exists images jsonb default '[]'::jsonb;
alter table public.products add column if not exists sizes jsonb default '[]'::jsonb;
alter table public.products add column if not exists colors jsonb default '[]'::jsonb;
alter table public.products add column if not exists rating numeric(3,2) default 0;
alter table public.products add column if not exists reviews integer default 0;
alter table public.products add column if not exists stock integer default 0;
alter table public.products add column if not exists featured boolean default false;
alter table public.products add column if not exists active boolean default true;
alter table public.products add column if not exists sort_order integer default 0;
alter table public.products add column if not exists created_at timestamptz default now();
alter table public.products add column if not exists updated_at timestamptz default now();
create index if not exists idx_products_active_category on public.products (active, category, sort_order);
create index if not exists idx_products_featured on public.products (featured, active);

create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key, code text not null unique,
  discount_type text not null check (discount_type in ('percent','fixed')), discount_value numeric(12,2) not null check (discount_value > 0),
  min_order_amount numeric(12,2) not null default 0 check (min_order_amount >= 0), usage_limit integer check (usage_limit is null or usage_limit > 0),
  used_count integer not null default 0 check (used_count >= 0), starts_at timestamptz, expires_at timestamptz,
  active boolean not null default true, created_at timestamptz not null default now()
);
create index if not exists idx_promo_codes_active on public.promo_codes (active, code);

create table if not exists public.saved_addresses (
  id bigint generated by default as identity primary key, telegram_id bigint, username text, phone text, label text default 'Uy',
  latitude double precision not null, longitude double precision not null, region text, district text, street text, house text,
  apartment text, landmark text, is_default boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists idx_saved_addresses_telegram_id on public.saved_addresses (telegram_id);

alter table public.orders add column if not exists order_number text;
alter table public.orders add column if not exists telegram_id bigint;
alter table public.orders add column if not exists username text;
alter table public.orders add column if not exists first_name text;
alter table public.orders add column if not exists telegram_phone text;
alter table public.orders add column if not exists items jsonb;
alter table public.orders add column if not exists subtotal numeric(12,2) default 0;
alter table public.orders add column if not exists delivery numeric(12,2) default 0;
alter table public.orders add column if not exists discount numeric(12,2) default 0;
alter table public.orders add column if not exists total numeric(12,2) default 0;
alter table public.orders add column if not exists address jsonb;
alter table public.orders add column if not exists payment text default 'cash';
alter table public.orders add column if not exists status text default 'Qabul qilindi';
alter table public.orders add column if not exists created_at timestamptz default now();
alter table public.orders add column if not exists updated_at timestamptz default now();
create index if not exists idx_orders_telegram_id on public.orders (telegram_id);
create index if not exists idx_orders_status_created_at on public.orders (status, created_at desc);
create index if not exists idx_orders_order_number on public.orders (order_number);

create or replace function public.create_secure_order(p_order jsonb, p_telegram_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  it jsonb; prod record; qty integer; subtotal numeric(12,2):=0; delivery numeric(12,2):=greatest(0,coalesce((p_order->>'delivery')::numeric,0)); discount numeric(12,2):=0; total numeric(12,2);
  promo record; promo_code text:=upper(trim(coalesce(p_order->>'promo_code',''))); normalized jsonb:='[]'::jsonb; new_item jsonb; order_no text:=nullif(p_order->>'order_number',''); existing jsonb; telegram_phone text;
begin
  if p_telegram_id is null then raise exception 'Telegram foydalanuvchisi aniqlanmadi'; end if;
  if jsonb_typeof(p_order->'items') <> 'array' or jsonb_array_length(p_order->'items')=0 or jsonb_array_length(p_order->'items')>100 then raise exception 'Buyurtma mahsulotlari noto‘g‘ri'; end if;
  if order_no is not null then select to_jsonb(o) into existing from orders o where o.order_number=order_no and o.telegram_id=p_telegram_id limit 1; if existing is not null then return existing; end if; end if;
  select tu.telegram_phone into telegram_phone from telegram_users tu where tu.telegram_id=p_telegram_id limit 1;
  for it in select value from jsonb_array_elements(p_order->'items') loop
    qty:=coalesce((it->>'quantity')::integer,(it->>'qty')::integer,1); if qty<1 or qty>99 then raise exception 'Mahsulot miqdori noto‘g‘ri'; end if;
    if it->'product'->>'id' is not null then select * into prod from products where id=(it->'product'->>'id')::bigint for update;
    elsif it->>'product_id' is not null then select * into prod from products where id=(it->>'product_id')::bigint for update;
    else select * into prod from products where product_code=coalesce(it->'product'->>'product_code',it->>'product_code') for update; end if;
    if not found then raise exception 'Mahsulot topilmadi'; end if;
    if not prod.active then raise exception '% hozir sotuvda emas',coalesce(prod.name,'Mahsulot'); end if;
    if prod.stock<qty then raise exception '% uchun omborda yetarli qoldiq yo‘q',coalesce(prod.name,'Mahsulot'); end if;
    subtotal:=subtotal+(prod.price*qty);
    new_item:=it||jsonb_build_object('quantity',qty,'product_id',prod.id,'product_code',prod.product_code,'product',coalesce(it->'product','{}'::jsonb)||jsonb_build_object('id',prod.id,'product_code',prod.product_code,'name',prod.name,'price',prod.price,'old_price',prod.old_price,'stock',prod.stock));
    normalized:=normalized||jsonb_build_array(new_item);
    update products set stock=stock-qty,updated_at=now() where id=prod.id;
  end loop;
  if promo_code<>'' then
    select * into promo from promo_codes where upper(code)=promo_code for update;
    if not found or not promo.active then raise exception 'Promo kod topilmadi yoki faol emas'; end if;
    if promo.starts_at is not null and promo.starts_at>now() then raise exception 'Promo kod hali kuchga kirmagan'; end if;
    if promo.expires_at is not null and promo.expires_at<now() then raise exception 'Promo kod muddati tugagan'; end if;
    if promo.usage_limit is not null and promo.used_count>=promo.usage_limit then raise exception 'Promo koddan foydalanish limiti tugagan'; end if;
    if subtotal<promo.min_order_amount then raise exception 'Minimal buyurtma % so‘m',promo.min_order_amount; end if;
    if promo.discount_type='percent' then discount:=least(subtotal,round(subtotal*promo.discount_value/100)); else discount:=least(subtotal,greatest(0,promo.discount_value)); end if;
    update promo_codes set used_count=used_count+1 where id=promo.id;
  end if;
  total:=greatest(0,subtotal+delivery-discount);
  if order_no is null then order_no:='GULI-'||lpad((floor(random()*900000)+100000)::int::text,6,'0'); end if;
  insert into orders(order_number,telegram_id,username,first_name,phone,telegram_phone,items,subtotal,delivery,discount,total,address,payment,status,created_at,updated_at)
  values(order_no,p_telegram_id,nullif(p_order->>'username',''),nullif(p_order->>'first_name',''),nullif(p_order->>'phone',''),telegram_phone,normalized,subtotal,delivery,discount,total,p_order->'address',coalesce(nullif(p_order->>'payment',''),'cash'),coalesce(nullif(p_order->>'status',''),'Qabul qilindi'),coalesce(nullif(p_order->>'created_at','')::timestamptz,now()),now()) returning to_jsonb(orders.*) into existing;
  return existing;
exception when unique_violation then
  select to_jsonb(o) into existing from orders o where o.order_number=order_no and o.telegram_id=p_telegram_id limit 1; if existing is not null then return existing; end if; raise;
end; $$;
grant execute on function public.create_secure_order(jsonb,bigint) to service_role;

alter table public.products enable row level security;
alter table public.promo_codes enable row level security;
alter table public.saved_addresses enable row level security;
drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products for select using (active=true);
