-- GULI PAYMENT AUDIT LOG HARDENING 2026-09-02
-- Records payment/reservation state changes at the DB boundary.
-- Production public.orders.id is UUID.
-- Run after payment_reservation_hardening_20260901.sql and payment_verified_terminal_20260902.sql.

begin;

do $$
begin
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='id' and data_type='uuid') then
    raise exception 'Payment audit log requires public.orders.id uuid';
  end if;
end;
$$;

create table if not exists public.payment_audit_log (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete restrict,
  order_number text,
  event_type text not null,
  old_payment_status text,
  new_payment_status text,
  old_receipt_path text,
  new_receipt_path text,
  old_stock_reserved boolean,
  new_stock_reserved boolean,
  old_promo_reserved boolean,
  new_promo_reserved boolean,
  old_reservation_released_at timestamptz,
  new_reservation_released_at timestamptz,
  changed_at timestamptz not null default now()
);

create index if not exists payment_audit_log_order_idx on public.payment_audit_log(order_id, changed_at desc);
create index if not exists payment_audit_log_event_idx on public.payment_audit_log(event_type, changed_at desc);

create or replace function public.guli_payment_audit_log()
returns trigger language plpgsql security definer set search_path = public as $$
declare event_name text;
begin
  if tg_op <> 'UPDATE' then return new; end if;
  if old.payment_status is distinct from new.payment_status then event_name := 'payment_status_changed';
  elsif old.payment_receipt_path is distinct from new.payment_receipt_path then event_name := 'receipt_changed';
  elsif old.stock_reserved is distinct from new.stock_reserved or old.promo_reserved is distinct from new.promo_reserved or old.reservation_released_at is distinct from new.reservation_released_at then
    event_name := case when old.reservation_released_at is null and new.reservation_released_at is not null then 'reservation_released'
      when old.reservation_released_at is not null and new.reservation_released_at is null then 'reservation_restored'
      else 'reservation_state_changed' end;
  else return new; end if;
  insert into public.payment_audit_log (
    order_id, order_number, event_type, old_payment_status, new_payment_status,
    old_receipt_path, new_receipt_path, old_stock_reserved, new_stock_reserved,
    old_promo_reserved, new_promo_reserved, old_reservation_released_at,
    new_reservation_released_at, changed_at
  ) values (
    new.id, new.order_number, event_name, old.payment_status, new.payment_status,
    old.payment_receipt_path, new.payment_receipt_path, old.stock_reserved, new.stock_reserved,
    old.promo_reserved, new.promo_reserved, old.reservation_released_at,
    new.reservation_released_at, now()
  );
  return new;
end;
$$;

drop trigger if exists trg_guli_payment_audit_log on public.orders;
create trigger trg_guli_payment_audit_log
after update of payment_status,payment_receipt_path,payment_verified_at,stock_reserved,promo_reserved,reservation_released_at
on public.orders for each row execute function public.guli_payment_audit_log();

revoke all on public.payment_audit_log from public, anon, authenticated;
grant select, insert on public.payment_audit_log to service_role;
revoke all on function public.guli_payment_audit_log() from public, anon, authenticated;
grant execute on function public.guli_payment_audit_log() to service_role;

commit;
select 'GULI payment audit log installed successfully' as result;