-- GULI product reviews schema.
-- Production note: products.id may be UUID. This migration supports UUID and bigint.

do $$
declare
  product_id_type text;
begin
  select format_type(a.atttypid, a.atttypmod)
    into product_id_type
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relname = 'products' and a.attname = 'id'
    and a.attnum > 0 and not a.attisdropped;

  if product_id_type = 'uuid' then
    execute $sql$
      create table if not exists public.product_reviews (
        id bigint generated by default as identity primary key,
        product_id uuid not null references public.products(id) on delete cascade,
        product_code text not null,
        telegram_id bigint not null,
        username text,
        first_name text,
        rating integer not null check (rating between 1 and 5),
        comment text not null check (char_length(comment) between 3 and 1200),
        photos jsonb not null default '[]'::jsonb,
        verified_purchase boolean not null default false,
        order_number text not null,
        status text not null default 'approved' check (status in ('approved','hidden')),
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now(),
        unique (product_id, telegram_id, order_number)
      )
    $sql$;
  elsif product_id_type = 'bigint' then
    execute $sql$
      create table if not exists public.product_reviews (
        id bigint generated by default as identity primary key,
        product_id bigint not null references public.products(id) on delete cascade,
        product_code text not null,
        telegram_id bigint not null,
        username text,
        first_name text,
        rating integer not null check (rating between 1 and 5),
        comment text not null check (char_length(comment) between 3 and 1200),
        photos jsonb not null default '[]'::jsonb,
        verified_purchase boolean not null default false,
        order_number text not null,
        status text not null default 'approved' check (status in ('approved','hidden')),
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now(),
        unique (product_id, telegram_id, order_number)
      )
    $sql$;
  else
    raise exception 'Unsupported public.products.id type: %', product_id_type;
  end if;
end $$;

alter table public.product_reviews add column if not exists product_code text;
alter table public.product_reviews add column if not exists username text;
alter table public.product_reviews add column if not exists first_name text;
alter table public.product_reviews add column if not exists rating integer;
alter table public.product_reviews add column if not exists comment text;
alter table public.product_reviews add column if not exists photos jsonb default '[]'::jsonb;
alter table public.product_reviews add column if not exists verified_purchase boolean default false;
alter table public.product_reviews add column if not exists order_number text;
alter table public.product_reviews add column if not exists status text default 'approved';
alter table public.product_reviews add column if not exists created_at timestamptz default now();
alter table public.product_reviews add column if not exists updated_at timestamptz default now();

create index if not exists idx_product_reviews_product_status_created on public.product_reviews (product_id, status, created_at desc);
create index if not exists idx_product_reviews_telegram on public.product_reviews (telegram_id, created_at desc);

alter table public.product_reviews enable row level security;
drop policy if exists product_reviews_public_read on public.product_reviews;
create policy product_reviews_public_read on public.product_reviews for select using (status = 'approved');

insert into storage.buckets (id, name, public)
values ('review-images', 'review-images', true)
on conflict (id) do update set public = true;

select 'GULI reviews schema ready' as result;
