const express = require("express");
const { createClient } = require("@supabase/supabase-js");
const URL = process.env.SUPABASE_URL || "";
const KEY = process.env.SUPABASE_SECRET_KEY || "";
const authClient = URL && KEY ? createClient(URL, KEY, { auth: { persistSession: false, autoRefreshToken: false } }) : null;
const buckets = new Map(); const WINDOW_MS = 10 * 60 * 1000; const MAX_ATTEMPTS = 8;
function allowed(req) { const ip = String(req.headers["x-forwarded-for"] || req.ip || "unknown").split(",")[0].trim(); const now = Date.now(); const x = buckets.get(ip) || { start: now, count: 0 }; if (now - x.start > WINDOW_MS) { x.start = now; x.count = 0; } x.count += 1; buckets.set(ip, x); return x.count <= MAX_ATTEMPTS; }
function emailOf(v) { return String(v || "").trim().toLowerCase(); }
function validEmail(v) { return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v); }
function validPassword(v) { return typeof v === "string" && v.length >= 8 && v.length <= 128; }
function fail(res, code, message) { return res.status(code).json({ success: false, message }); }
function ok(res, data, message = "OK") { return res.json({ success: true, message, data }); }
function install(method, path, handler) { const original = express.application[method]; express.application[method] = function authRoute(routePath, ...handlers) { if (routePath === path) return original.call(this, routePath, handler, ...handlers); return original.call(this, routePath, ...handlers); }; }
install("post", "/api/auth/password/signup", async (req, res) => { if (!allowed(req)) return fail(res,429,"Juda ko‘p urinish. Bir necha daqiqadan keyin qayta urinib ko‘ring."); if (!authClient) return fail(res,503,"Email autentifikatsiyasi serverda sozlanmagan."); const email=emailOf(req.body?.email), password=String(req.body?.password||""); if(!validEmail(email)) return fail(res,400,"Email manzilini to‘g‘ri kiriting."); if(!validPassword(password)) return fail(res,400,"Parol kamida 8 belgidan iborat bo‘lsin."); try { const {data,error}=await authClient.auth.signUp({email,password}); if(error) return fail(res,400,error.message||"Ro‘yxatdan o‘tib bo‘lmadi."); return ok(res,{user:data.user,session:data.session||null,email},data.session?"Hisob yaratildi.":"Hisob yaratildi. Emailingizni tasdiqlang."); } catch { return fail(res,500,"Ro‘yxatdan o‘tishda server xatosi."); } });
install("post", "/api/auth/password/login", async (req, res) => { if(!allowed(req)) return fail(res,429,"Juda ko‘p urinish. Bir necha daqiqadan keyin qayta urinib ko‘ring."); if(!authClient) return fail(res,503,"Email autentifikatsiyasi serverda sozlanmagan."); const email=emailOf(req.body?.email),password=String(req.body?.password||""); if(!validEmail(email)||!password) return fail(res,400,"Email va parolni kiriting."); try { const {data,error}=await authClient.auth.signInWithPassword({email,password}); if(error) return fail(res,401,"Email yoki parol noto‘g‘ri."); return ok(res,{user:data.user,session:data.session,email},"Tizimga muvaffaqiyatli kirdingiz."); } catch { return fail(res,500,"Kirishda server xatosi."); } });
install("post", "/api/auth/email/start", async (req, res) => { if(!allowed(req)) return fail(res,429,"Juda ko‘p urinish. Bir necha daqiqadan keyin qayta urinib ko‘ring."); if(!authClient) return fail(res,503,"Email autentifikatsiyasi serverda sozlanmagan."); const email=emailOf(req.body?.email); if(!validEmail(email)) return fail(res,400,"Email manzilini to‘g‘ri kiriting."); try { const {error}=await authClient.auth.signInWithOtp({email,options:{shouldCreateUser:true}}); if(error) return fail(res,400,error.message||"Email kodi yuborilmadi."); return ok(res,{email},"Tasdiqlash kodi emailga yuborildi."); } catch { return fail(res,500,"Email kodi yuborishda server xatosi."); } });
install("post", "/api/auth/email/verify", async (req, res) => { if(!allowed(req)) return fail(res,429,"Juda ko‘p urinish. Bir necha daqiqadan keyin qayta urinib ko‘ring."); if(!authClient) return fail(res,503,"Email autentifikatsiyasi serverda sozlanmagan."); const email=emailOf(req.body?.email),token=String(req.body?.token||"").replace(/\s+/g,""); if(!validEmail(email)||!/^[0-9]{6}$/.test(token)) return fail(res,400,"6 xonali email kodini kiriting."); try { const {data,error}=await authClient.auth.verifyOtp({email,token,type:"email"}); if(error) return fail(res,401,"Email kodi noto‘g‘ri yoki muddati tugagan."); return ok(res,{user:data.user,session:data.session,email},"Email tasdiqlandi. Tizimga kirdingiz."); } catch { return fail(res,500,"Email kodini tekshirishda server xatosi."); } });
install("post", "/api/auth/password/reset-start", async (req, res) => { if(!allowed(req)) return fail(res,429,"Juda ko‘p urinish. Bir necha daqiqadan keyin qayta urinib ko‘ring."); if(!authClient) return fail(res,503,"Email autentifikatsiyasi serverda sozlanmagan."); const email=emailOf(req.body?.email); if(!validEmail(email)) return fail(res,400,"Email manzilini to‘g‘ri kiriting."); try { const {error}=await authClient.auth.resetPasswordForEmail(email,{redirectTo:"https://vite-react-guli3550.vercel.app/"}); if(error) return fail(res,400,error.message||"Reset kodi yuborilmadi."); return ok(res,{email},"Parolni tiklash uchun email yuborildi."); } catch { return fail(res,500,"Parolni tiklashda server xatosi."); } });
module.exports = {};
