// Final customer mutation boundary for legacy public order/address routes.
// Client phone, Telegram ID, auth user ID, status, timestamps and receipt URL are
// never authoritative. Identity comes only from verified Telegram WebApp initData
// plus the server-recorded Telegram Contact Share phone.
const crypto = require('crypto');
const { createClient } = require('@supabase/supabase-js');
const { registry, install } = require('./routeRegistry.js');

const URL_ = String(process.env.SUPABASE_URL || '').trim();
const KEY = String(process.env.SUPABASE_SECRET_KEY || '').trim();
const BOT = String(process.env.TELEGRAM_BOT_TOKEN || '').trim();
const supabase = URL_ && KEY ? createClient(URL_, KEY, { auth: { persistSession: false, autoRefreshToken: false } }) : null;

const fail = (res, code, message) => res.status(code).json({ success: false, message });
const safeEqual = (a, b) => { const x = Buffer.from(String(a || '')); const y = Buffer.from(String(b || '')); return x.length === y.length && crypto.timingSafeEqual(x, y); };

function verifiedTelegram(raw) {
  if (!BOT || !raw) return null;
  try {
    const p = new URLSearchParams(String(raw));
    const received = p.get('hash') || '';
    const authDate = Number(p.get('auth_date'));
    if (!received || !Number.isFinite(authDate) || Math.abs(Math.floor(Date.now() / 1000) - authDate) > 86400) return null;
    p.delete('hash');
    const check = [...p.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => `${k}=${v}`).join('\n');
    const secret = crypto.createHmac('sha256', 'WebAppData').update(BOT).digest();
    const expected = crypto.createHmac('sha256', secret).update(check).digest('hex');
    if (!safeEqual(received, expected)) return null;
    const user = JSON.parse(p.get('user') || '{}');
    const id = Number(user.id);
    return Number.isSafeInteger(id) && id > 0 ? { id, user } : null;
  } catch { return null; }
}

async function canonicalIdentity(req) {
  const tg = verifiedTelegram(req.headers['x-telegram-init-data'] || '');
  if (!tg || !supabase) return null;
  const { data: telegram, error } = await supabase.from('telegram_users').select('telegram_id,telegram_phone,username,first_name,last_name').eq('telegram_id', tg.id).maybeSingle();
  if (error || !telegram?.telegram_phone) return null;
  return { telegramId: tg.id, phone: String(telegram.telegram_phone).trim(), user: tg.user, telegram };
}

async function canonicalAddress(req, res) {
  const id = await canonicalIdentity(req);
  if (!id) return fail(res, 403, 'Tasdiqlangan Telegram telefon identifikatori talab qilinadi.');
  const b = req.body || {};
  const lat = Number(b.latitude), lon = Number(b.longitude);
  if (!Number.isFinite(lat) || lat < -90 || lat > 90 || !Number.isFinite(lon) || lon < -180 || lon > 180) return fail(res, 400, 'Lokatsiya koordinatalari noto‘g‘ri.');
  const row = {
    telegram_id: id.telegramId,
    username: id.telegram.username || id.user.username || null,
    phone: id.phone,
    latitude: lat,
    longitude: lon,
    region: b.region || null,
    district: b.district || null,
    street: b.street || null,
    house: b.house || null,
    apartment: b.apartment || null,
    landmark: b.landmark || null
  };
  try {
    const { data, error } = await supabase.from('saved_addresses').insert([row]).select().single();
    if (error) throw error;
    return res.json({ success: true, message: 'Manzil muvaffaqiyatli saqlandi', data });
  } catch (e) {
    console.error('[Canonical address]', e);
    return fail(res, 500, 'Manzilni saqlashda xatolik.');
  }
}

async function canonicalOrder(req, res) {
  const id = await canonicalIdentity(req);
  if (!id) return fail(res, 403, 'Buyurtma uchun Telegram orqali tasdiqlangan telefon talab qilinadi.');
  const b = req.body || {};
  if (!Array.isArray(b.items) || b.items.length < 1 || b.items.length > 100) return fail(res, 400, 'Buyurtma mahsulotlari noto‘g‘ri.');
  const input = {
    // Order number is server-generated by create_secure_order when absent.
    order_number: null,
    username: id.telegram.username || null,
    first_name: id.telegram.first_name || id.user.first_name || null,
    last_name: id.telegram.last_name || id.user.last_name || null,
    customer_name: [id.telegram.first_name || id.user.first_name, id.telegram.last_name || id.user.last_name].filter(Boolean).join(' ') || id.telegram.username || null,
    phone: id.phone,
    items: b.items,
    address: b.address || null,
    payment: b.payment || 'card',
    promo_code: b.promo_code ? String(b.promo_code).trim().toUpperCase() : ''
  };
  try {
    const { data, error } = await supabase.rpc('create_secure_order', { p_order: input, p_telegram_id: id.telegramId });
    if (error) {
      console.error('[Canonical public order RPC]', error);
      return fail(res, 400, error.message || 'Buyurtmani saqlash rad etildi.');
    }
    const order = Array.isArray(data) ? data[0] : data;
    if (!order) return fail(res, 503, 'Buyurtma yaratish xizmati javob bermadi.');
    return res.status(201).json({ success: true, message: 'Buyurtma muvaffaqiyatli saqlandi', data: order });
  } catch (e) {
    console.error('[Canonical public order]', e);
    return fail(res, 503, 'Buyurtma xizmati vaqtincha mavjud emas.');
  }
}

registry.routes = registry.routes.filter((r) => !(
  (r.method === 'post' && r.path === '/api/orders') ||
  (r.method === 'post' && r.path === '/api/save-address')
));
install('post', '/api/orders', canonicalOrder);
install('post', '/api/save-address', canonicalAddress);
console.log('[CanonicalCustomerMutationBoundary] public order/address identity locked to verified Telegram phone');
