// Realtime chat bridge with Telegram, browser-guest and admin auth.
const express = require("express");
const crypto = require("crypto");
const { createClient } = require("@supabase/supabase-js");
const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN || "";
const ADMIN_SECRET = process.env.ADMIN_SECRET || "";
const SUPABASE_URL = process.env.SUPABASE_URL || "";
const SUPABASE_KEY = process.env.SUPABASE_SECRET_KEY || "";
const supabase = SUPABASE_URL && SUPABASE_KEY ? createClient(SUPABASE_URL, SUPABASE_KEY, { auth: { persistSession: false, autoRefreshToken: false } }) : null;
const ADMIN_CHAT_IDS = String(process.env.TELEGRAM_ADMIN_CHAT_IDS || "").split(",").map(v => v.trim()).filter(Boolean);
const clients = new Set();
const REALTIME_CHANNEL = "guli-chat-realtime";
let realtimeStarted = false;
let realtimeChannel = null;
function safeEqual(a, b) { const x = Buffer.from(String(a)); const y = Buffer.from(String(b)); return x.length === y.length && crypto.timingSafeEqual(x, y); }
function signGuest(id, exp) { return crypto.createHmac("sha256", ADMIN_SECRET || BOT_TOKEN).update(`${id}.${exp}`).digest("base64url"); }
function createGuestToken(id) { const exp = Date.now() + 30 * 24 * 60 * 60 * 1000; return `${id}.${exp}.${signGuest(id, exp)}`; }
function verifyGuest(req, expectedId) { if (!ADMIN_SECRET && !BOT_TOKEN) return false; const token = String(req.headers["x-guli-guest-token"] || ""); const [id, exp, sig] = token.split("."); if (!id || !exp || !sig || Number(id) !== Number(expectedId) || Number(exp) <= Date.now()) return false; return safeEqual(sig, signGuest(id, Number(exp))); }
function verifyTelegram(initData) { if (!BOT_TOKEN || !initData) return null; try { const p = new URLSearchParams(initData); const hash = p.get("hash"); const authDate = Number(p.get("auth_date")); if (!hash || !Number.isFinite(authDate) || Math.abs(Math.floor(Date.now() / 1000) - authDate) > 86400) return null; const pairs = []; p.forEach((v, k) => { if (k !== "hash") pairs.push(`${k}=${v}`); }); pairs.sort(); const secret = crypto.createHmac("sha256", "WebAppData").update(BOT_TOKEN).digest(); const calc = crypto.createHmac("sha256", secret).update(pairs.join("\n")).digest("hex"); if (!safeEqual(calc, hash)) return null; const u = JSON.parse(p.get("user") || "null"); return u?.id ? { id: Number(u.id), username: u.username || null, first_name: u.first_name || null } : null; } catch { return null; } }
function verifyAdmin(req) { const h = req.headers.authorization || ""; if (!h.startsWith("Bearer ") || !ADMIN_SECRET) return false; try { const [body, sig] = h.slice(7).split("."); if (!body || !sig) return false; const expected = crypto.createHmac("sha256", ADMIN_SECRET).update(body).digest("base64url"); if (!safeEqual(sig, expected)) return false; const p = JSON.parse(Buffer.from(body, "base64url").toString("utf8")); return p.role === "admin" && Number(p.exp) > Date.now(); } catch { return false; } }
function customer(req) { return verifyTelegram(req.headers["x-telegram-init-data"] || ""); }
function authorizedForUser(req, id) { const n = Number(id); const u = customer(req); return (!!u && Number(u.id) === n) || (n < 0 && verifyGuest(req, n)); }
function sseSend(client, event, data) { try { client.res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`); } catch {} }
function deliverToClients(message) { for (const c of clients) { if (c.admin || Number(c.chatId) === Number(message?.telegram_id)) sseSend(c, "message", message); } }
async function publishRealtime(message) {
  if (!message) return;
  // Always deliver immediately to every connected client on this API instance.
  // Supabase Broadcast remains the cross-instance transport without requiring extra SQL.
  deliverToClients(message);
  if (!realtimeChannel) return;
  try { await realtimeChannel.send({ type: "broadcast", event: "chat_message", payload: message }); }
  catch (error) { console.warn("[Chat realtime] broadcast failed:", error.message); }
}
async function telegramSend(chatId, text) { if (!BOT_TOKEN || !chatId) return; try { await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/sendMessage`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ chat_id: chatId, text, parse_mode: "HTML", disable_web_page_preview: true }) }); } catch (e) { console.warn("[Chat] Telegram admin notification failed:", e.message); } }
async function notifyAdmins(message) { if (!ADMIN_CHAT_IDS.length || message?.sender !== "customer") return; const id = Number(message.telegram_id); const who = id < 0 ? `Browser guest ${Math.abs(id)}` : `Telegram ${id}`; const text = `💬 <b>Yangi mijoz xabari</b>\n\n👤 ${who}\n📝 ${String(message.text || "").slice(0, 300)}`; await Promise.all(ADMIN_CHAT_IDS.map(cid => telegramSend(cid, text))); }
function startRealtime() { if (realtimeStarted || !supabase) return; realtimeStarted = true; realtimeChannel = supabase.channel(REALTIME_CHANNEL, { config: { broadcast: { self: true } } }); realtimeChannel.on("broadcast", { event: "chat_message" }, payload => deliverToClients(payload.payload)); realtimeChannel.subscribe(status => console.log(`[Chat realtime] ${status}`)); }
function patchGet() { const original = express.application.get; express.application.get = function patchedGet(routePath, ...handlers) {
  if (routePath === "/api/chat/guest-session/:guest_id") return original.call(this, routePath, (req, res) => { const id = Number(req.params.guest_id); if (!Number.isSafeInteger(id) || id >= 0 || id < -9007199254740991) return res.status(400).json({ success: false, message: "Noto‘g‘ri guest ID" }); if (!ADMIN_SECRET && !BOT_TOKEN) return res.status(503).json({ success: false, message: "Chat auth secret sozlanmagan" }); return res.json({ success: true, guest_id: id, token: createGuestToken(id), expires_in: 2592000 }); });
  if (routePath === "/api/admin/chat/messages") return original.call(this, routePath, (req, res) => { if (!verifyAdmin(req)) return res.status(401).json({ success: false, message: "Admin sessiyasi tasdiqlanmadi" }); if (!supabase) return res.status(503).json({ success: false, message: "Chat bazasi sozlanmagan" }); return supabase.from("chat_messages").select("*").order("created_at", { ascending: true }).then(({ data, error }) => error ? res.status(500).json({ success: false, message: "Chat tarixini yuklashda xatolik" }) : res.json({ success: true, data: data || [] })); });
  if (routePath === "/api/chat/messages/:telegram_id") return original.call(this, routePath, (req, res) => { const rawId = String(req.params.telegram_id || ""); const isAdmin = rawId === "all" && verifyAdmin(req); if (!isAdmin && !authorizedForUser(req, rawId)) return res.status(401).json({ success: false, message: "Chat sessiyasi tasdiqlanmadi" }); return supabase.from("chat_messages").select("*").eq("telegram_id", rawId).order("created_at", { ascending: true }).then(({ data, error }) => error ? res.status(500).json({ success: false, message: "Chat tarixini yuklashda xatolik" }) : res.json({ success: true, data: data || [] })); });
  if (routePath === "/api/chat/stream/:telegram_id") return original.call(this, routePath, (req, res) => { const rawId = String(req.params.telegram_id || ""); const isAdmin = rawId === "all" && verifyAdmin(req); if (!isAdmin && !authorizedForUser(req, rawId)) return res.status(401).json({ success: false, message: "Chat sessiyasi tasdiqlanmadi" }); res.status(200); res.setHeader("Content-Type", "text/event-stream"); res.setHeader("Cache-Control", "no-cache, no-transform"); res.setHeader("Connection", "keep-alive"); res.flushHeaders?.(); const client = { res, chatId: isAdmin ? null : Number(rawId), admin: isAdmin }; clients.add(client); sseSend(client, "ready", { ok: true }); const heartbeat = setInterval(() => { try { res.write(`: heartbeat ${Date.now()}\n\n`); } catch {} }, 25000); req.on("close", () => { clearInterval(heartbeat); clients.delete(client); }); });
  return original.call(this, routePath, ...handlers);
}; }
function patchChatPost() { const original = express.application.post; express.application.post = function patchedPost(routePath, ...handlers) { if (routePath === "/api/chat/messages" && handlers.length) { const index = handlers.length - 1; const handler = handlers[index]; handlers[index] = async function secureChatPost(req, res, next) { const sender = String(req.body?.sender || "").toLowerCase(); const id = Number(req.body?.telegram_id || 0); if (sender === "customer" || sender === "user") { const u = customer(req); const guest = id < 0 && verifyGuest(req, id); if ((!u || !id || Number(u.id) !== id) && !guest) return res.status(401).json({ success: false, message: "Mijoz sessiyasi tasdiqlanmadi" }); req.body.sender = "customer"; req.body.telegram_id = id; } else if (sender === "admin") { if (!verifyAdmin(req)) return res.status(401).json({ success: false, message: "Admin sessiyasi tasdiqlanmadi" }); } else return res.status(400).json({ success: false, message: "Noto‘g‘ri chat jo‘natuvchisi" }); let payload = null; const originalJson = res.json.bind(res); res.json = body => { payload = body; return originalJson(body); }; const result = await handler(req, res, next); if (payload?.success && payload?.data) { await publishRealtime(payload.data); await notifyAdmins(payload.data); } return result; }; } return original.call(this, routePath, ...handlers); }; }
patchGet(); patchChatPost();
setImmediate(startRealtime);
