// GULI production canonical order/status/payment fix. Loaded last in backend start.
const crypto = require('crypto');
const { createClient } = require('@supabase/supabase-js');
const { install } = require('./routeRegistry');
const URL = String(process.env.SUPABASE_URL || '').trim();
const KEY = String(process.env.SUPABASE_SECRET_KEY || '').trim();
const BOT = String(process.env.TELEGRAM_BOT_TOKEN || '').trim();
const ADMIN_SECRET = String(process.env.ADMIN_SECRET || '').trim();
const db = URL && KEY ? createClient(URL, KEY, { auth:{persistSession:false,autoRefreshToken:false} }) : null;
const STATUSES = new Set(['⏳ Buyurtma kutilmoqda','Qabul qilindi','Tayyorlanmoqda','Yo‘lda','Yetkazildi','Bekor qilindi']);
const eq=(a,b)=>{const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y)};
function tgUser(raw){if(!raw||!BOT)return null;try{const p=new URLSearchParams(String(raw)),h=p.get('hash')||'',ad=Number(p.get('auth_date'));if(!h||!Number.isFinite(ad)||Math.abs(Math.floor(Date.now()/1000)-ad)>86400)return null;p.delete('hash');const s=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');const sk=crypto.createHmac('sha256','WebAppData').update(BOT).digest(),ex=crypto.createHmac('sha256',sk).update(s).digest('hex');if(!eq(h,ex))return null;const u=JSON.parse(p.get('user')||'{}'),id=Number(u.id);return Number.isSafeInteger(id)&&id>0?{id}:null}catch{return null}}
async function customer(req){const t=tgUser(req.headers['x-telegram-init-data']||'');if(t)return{type:'telegram',id:t.id};if(!db)return null;const h=String(req.headers.authorization||'');if(!h.startsWith('Bearer '))return null;const r=await db.auth.getUser(h.slice(7).trim());return r.error||!r.data?.user?.id?null:{type:'auth',id:String(r.data.user.id)}}
const normItem=x=>{const p=x?.product||x?.product_data||x?.productDetails||{},img=x?.image||x?.image_url||x?.photo||p?.image||p?.image_url||(Array.isArray(p?.images)?p.images[0]:'');return{...x,name:x?.name||x?.title||p?.name||p?.title||'Mahsulot',product_code:x?.product_code||p?.product_code||'',image:img,product:{...p,name:p?.name||x?.name||x?.title||'Mahsulot',image:p?.image||img,product_code:p?.product_code||x?.product_code||''}}};
async function signed(path){if(!db||!path)return'';try{return(await db.storage.from('payment-receipts').createSignedUrl(String(path).replace(/^\/+/,''),86400)).data?.signedUrl||''}catch{return''}}
async function orders(req,res){if(!db)return res.status(503).json({success:false,message:'Buyurtmalar xizmati sozlanmagan.'});const u=await customer(req);const nums=String(req.query.order_numbers||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,50),tg=String(req.query.telegram_id||req.headers['x-telegram-id']||'').trim(),phone=String(req.query.phone||req.headers['x-customer-phone']||'').replace(/\D/g,'');try{let q=db.from('orders').select('id,order_number,telegram_id,auth_user_id,username,first_name,last_name,customer_name,birth_date,dob,phone,items,subtotal,delivery,discount,total,address,payment,payment_status,payment_receipt_path,receipt_url,status,created_at,updated_at').order('created_at',{ascending:false}).limit(100);const or=[];if(u?.type==='telegram')or.push(`telegram_id.eq.${u.id}`);if(u?.type==='auth')or.push(`auth_user_id.eq.${u.id}`);if(/^\d+$/.test(tg))or.push(`telegram_id.eq.${tg}`);if(phone.length>=7)or.push(`phone.ilike.%${phone.slice(-7)}%`);for(const n of nums)or.push(`order_number.eq.${n}`);if(!or.length)return res.json({success:true,data:[]});q=q.or(or.join(','));const r=await q;if(r.error)throw r.error;const data=await Promise.all((r.data||[]).map(async o=>({...o,id:String(o.id),items:Array.isArray(o.items)?o.items.map(normItem):[],receipt_url:o.receipt_url||await signed(o.payment_receipt_path),status:o.status||'⏳ Buyurtma kutilmoqda',payment_status:o.payment_status||'pending',createdAt:o.created_at,updatedAt:o.updated_at,statusUpdatedAt:o.updated_at})));res.setHeader('Cache-Control','private,no-store');return res.json({success:true,data})}catch(e){console.error('[GULI canonical orders]',e);return res.status(500).json({success:false,message:'Buyurtmalarni yuklashda xatolik'})}}
async function receipt(req,res){if(!db)return res.status(503).json({success:false,message:'Xizmat sozlanmagan.'});try{const id=String(req.params.orderNumber||req.params.id||req.body?.order_id||'').trim();let r=await db.from('orders').select('*').eq('order_number',id).maybeSingle();if(r.error)throw r.error;let o=r.data;if(!o){r=await db.from('orders').select('*').eq('id',id).maybeSingle();if(r.error)throw r.error;o=r.data}if(!o)return res.status(404).json({success:false,message:'Buyurtma topilmadi.'});let raw=req.body?.data||req.body?.receipt_url||'',mime=String(req.body?.mimeType||'image/jpeg');const m=typeof raw==='string'&&raw.match(/^data:([^;]+);base64,(.+)$/);if(m){mime=m[1];raw=m[2]}if(!raw)return res.status(400).json({success:false,message:'Chek rasmi taqdim etilmadi.'});const buf=Buffer.from(raw,'base64');if(!buf.length||buf.length>10*1024*1024)return res.status(400).json({success:false,message:'Chek hajmi juda katta yoki fayl yaroqsiz.'});const ext=/png/i.test(mime)?'png':/webp/i.test(mime)?'webp':'jpg',path=`receipts/${o.id}/${Date.now()}-${crypto.randomBytes(4).toString('hex')}.${ext}`;const up=await db.storage.from('payment-receipts').upload(path,buf,{contentType:mime,cacheControl:'31536000',upsert:false});if(up.error)throw up.error;const hist=Array.isArray(o.payment_receipt_history)?o.payment_receipt_history.slice():[];hist.push({path,uploaded_at:new Date().toISOString()});const patch={payment_receipt_path:path,payment_receipt_history:hist,payment_status:'receipt_uploaded',payment_receipt_uploaded_at:new Date().toISOString(),updated_at:new Date().toISOString(),status:o.status==='Qabul qilindi'?o.status:(o.status==='Bekor qilindi'?o.status:'⏳ To‘lovni tasdiqlash kutilmoqda')};const u=await db.from('orders').update(patch).eq('id',o.id).select('*').single();if(u.error)throw u.error;return res.json({success:true,message:'Chek muvaffaqiyatli saqlandi.',data:{...u.data,receipt_url:await signed(path)}})}catch(e){console.error('[GULI receipt]',e);return res.status(500).json({success:false,message:'Chekni yuborishda xatolik yuz berdi.'})}}
function validAdmin(t){try{if(!t||!ADMIN_SECRET)return false;const[b,s]=t.split('.'),ex=crypto.createHmac('sha256',ADMIN_SECRET).update(b).digest('base64url');if(!b||!s||!eq(ex,s))return false;const p=JSON.parse(Buffer.from(b,'base64url').toString('utf8'));return p.role==='admin'&&Number(p.exp)>Date.now()}catch{return false}}
async function status(req,res){if(!validAdmin(String(req.headers.authorization||'').replace(/^Bearer\s+/i,'')))return res.status(401).json({success:false,message:'Admin sessiyasi yaroqsiz yoki tugagan'});const s=String(req.body?.status||'').trim();if(!STATUSES.has(s))return res.status(400).json({success:false,message:'Buyurtma statusi noto‘g‘ri'});try{let r=await db.from('orders').select('*').eq('id',req.params.id).maybeSingle();if(r.error)throw r.error;let o=r.data;if(!o){r=await db.from('orders').select('*').eq('order_number',req.params.id).maybeSingle();if(r.error)throw r.error;o=r.data}if(!o)return res.status(404).json({success:false,message:'Buyurtma topilmadi'});const p={status:s,updated_at:new Date().toISOString()};if(s==='Qabul qilindi'){p.payment_status='verified';p.payment_verified_at=new Date().toISOString()}const u=await db.from('orders').update(p).eq('id',o.id).select('*').single();if(u.error)throw u.error;return res.json({success:true,data:u.data})}catch(e){console.error('[GULI admin status]',e);return res.status(500).json({success:false,message:'Buyurtma statusini saqlashda xatolik'})}}
async function decision(req,res){if(!validAdmin(String(req.headers.authorization||'').replace(/^Bearer\s+/i,'')))return res.status(401).json({success:false,message:'Admin sessiyasi yaroqsiz yoki tugagan'});const ps=String(req.body?.payment_status||'');if(!['verified','rejected'].includes(ps))return res.status(400).json({success:false,message:'To‘lov qarori noto‘g‘ri'});try{let r=await db.from('orders').select('*').eq('id',req.params.id).maybeSingle();if(r.error)throw r.error;let o=r.data;if(!o){r=await db.from('orders').select('*').eq('order_number',req.params.id).maybeSingle();if(r.error)throw r.error;o=r.data}if(!o)return res.status(404).json({success:false,message:'Buyurtma topilmadi'});const p={payment_status:ps,updated_at:new Date().toISOString()};if(ps==='verified'){p.payment_verified_at=new Date().toISOString();p.status='Qabul qilindi'}else{p.payment_rejected_at=new Date().toISOString();p.status='Bekor qilindi'}const u=await db.from('orders').update(p).eq('id',o.id).select('*').single();if(u.error)throw u.error;return res.json({success:true,data:u.data})}catch(e){console.error('[GULI payment decision]',e);return res.status(500).json({success:false,message:'To‘lov qarorini saqlab bo‘lmadi'})}}
install('get','/api/orders',orders);install('get','/api/guest/orders',orders);install('get','/api/customer/orders',orders);install('post','/api/orders/:orderNumber/receipt',receipt);install('post','/api/orders/:id/receipt',receipt);install('post','/api/orders/:orderNumber/payment-receipt',receipt);install('put','/api/admin/orders/:id',status);install('post','/api/admin/orders/:id/payment-decision',decision);
