// Canonical customer receipt upload route with the same 10-minute payment deadline.
const express=require('express');const crypto=require('crypto');const {createClient}=require('@supabase/supabase-js');
const URL_=process.env.SUPABASE_URL||'',KEY=process.env.SUPABASE_SECRET_KEY||'',BOT=process.env.TELEGRAM_BOT_TOKEN||'',ADMIN_SECRET_=process.env.ADMIN_SECRET||'';const supabase=URL_&&KEY?createClient(URL_,KEY,{auth:{persistSession:false,autoRefreshToken:false}}):null;const WINDOW=10*60*1000;
function eq(a,b){const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function user(init){if(!BOT||!init)return null;try{const p=new URLSearchParams(init),hash=p.get('hash'),auth=Number(p.get('auth_date'));if(!hash||!Number.isFinite(auth)||Math.abs(Math.floor(Date.now()/1000)-auth)>86400)return null;const a=[];p.forEach((v,k)=>{if(k!=='hash')a.push(`${k}=${v}`)});a.sort();const s=crypto.createHmac('sha256','WebAppData').update(BOT).digest(),c=crypto.createHmac('sha256',s).update(a.join('\n')).digest('hex');if(!eq(c,hash))return null;const u=JSON.parse(p.get('user')||'null');return u?.id?{id:Number(u.id)}:null}catch{return null}}
function guest(t){try{if(!ADMIN_SECRET_)return null;const [b,s]=String(t||'').split('.');const e=crypto.createHmac('sha256',ADMIN_SECRET_).update(b).digest('base64url');if(!eq(s,e))return null;const d=JSON.parse(Buffer.from(b,'base64url').toString('utf8'));const id=Number(d.guestId);return Number.isSafeInteger(id)&&id<0&&Number(d.exp)>=Date.now()?{id}:null}catch{return null}}
function customer(req){return user(req.headers['x-telegram-init-data']||'')||guest(req.headers['x-guli-guest-token']||'')}
function install(method,path,handler){const original=express.application[method];express.application[method]=function(routePath,...handlers){if(routePath===path)return original.call(this,routePath,handler,...handlers);return original.call(this,routePath,...handlers)}}
async function bucket(){const b=await supabase.storage.getBucket('payment-receipts');if(!b.error)return;const c=await supabase.storage.createBucket('payment-receipts',{public:false,allowedMimeTypes:['image/jpeg','image/png','image/webp','application/pdf'],fileSizeLimit:'6MB'});if(c.error&&!/already exists|duplicate/i.test(c.error.message||''))throw c.error}
install('post','/api/orders/:orderNumber/receipt',async(req,res)=>{const u=customer(req);if(!u)return res.status(401).json({success:false,message:'Mijoz sessiyasi topilmadi.'});try{const number=String(req.params.orderNumber||'').trim();const {data:order,error}=await supabase.from('orders').select('id,order_number,total,telegram_id,payment,payment_status,created_at').eq('order_number',number).eq('telegram_id',u.id).maybeSingle();if(error)throw error;if(!order)return res.status(404).json({success:false,message:'Buyurtma topilmadi'});if(String(order.payment||'')!=='card_manual')return res.status(400).json({success:false,message:'Bu buyurtma karta orqali to‘lov uchun yaratilmagan'});if(Date.now()-new Date(order.created_at).getTime()>WINDOW)return res.status(410).json({success:false,message:'10 daqiqalik to‘lov vaqti tugagan. Chek yuborish yopildi.'});const {data,mimeType,extension}=req.body||{};if(!data||typeof data!=='string')return res.status(400).json({success:false,message:'Chek rasmi topilmadi'});if(!/^image\/(jpeg|png|webp)$/.test(String(mimeType||''))&&mimeType!=='application/pdf')return res.status(400).json({success:false,message:'Chek faqat JPG, PNG, WEBP yoki PDF bo‘lishi mumkin'});if(data.length>8200000)return res.status(413).json({success:false,message:'Chek hajmi juda katta'});await bucket();const ext=String(extension||(mimeType==='application/pdf'?'pdf':'jpg')).replace(/[^a-z0-9]/gi,'').toLowerCase()||'jpg';const path=`receipts/${order.id}/${Date.now()}-${crypto.randomBytes(6).toString('hex')}.${ext}`;const up=await supabase.storage.from('payment-receipts').upload(path,Buffer.from(data,'base64'),{contentType:mimeType,cacheControl:'31536000',upsert:false});if(up.error)throw up.error;const {data:updated,error:ue}=await supabase.from('orders').update({payment_receipt_path:path,payment_status:'receipt_uploaded',payment_receipt_uploaded_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',order.id).eq('telegram_id',u.id).select('id,order_number,total,payment_status,payment_receipt_uploaded_at').single();if(ue)throw ue;res.json({success:true,message:'Chek muvaffaqiyatli yuborildi. Endi “To‘lov qildim”ni bosing.',data:updated})}catch(e){console.error('Guarded receipt upload error:',e);res.status(500).json({success:false,message:'Chekni yuborishda xatolik'})}});
