// Customer manual-card payment state + receipt visibility runtime.
// Loaded after manualCardPaymentRuntime so customer/admin payment routes here
// become the canonical state/notification handlers.
const express = require('express');
const crypto = require('crypto');
const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_KEY = process.env.SUPABASE_SECRET_KEY || '';
const supabase = SUPABASE_URL && SUPABASE_KEY ? createClient(SUPABASE_URL, SUPABASE_KEY, { auth: { persistSession: false, autoRefreshToken: false } }) : null;
const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN || '';
const ADMIN_SECRET = process.env.ADMIN_SECRET || '';
const PAYMENT_WINDOW_MS = 10 * 60 * 1000;

function safeEqual(a,b){const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function verifyInitData(initData){if(!BOT_TOKEN||!initData)return null;try{const p=new URLSearchParams(initData),hash=p.get('hash'),authDate=Number(p.get('auth_date'));if(!hash||!Number.isFinite(authDate)||Math.abs(Math.floor(Date.now()/1000)-authDate)>86400)return null;const pairs=[];p.forEach((v,k)=>{if(k!=='hash')pairs.push(`${k}=${v}`)});pairs.sort();const secret=crypto.createHmac('sha256','WebAppData').update(BOT_TOKEN).digest();const calculated=crypto.createHmac('sha256',secret).update(pairs.join('\n')).digest('hex');if(!safeEqual(calculated,hash))return null;const user=JSON.parse(p.get('user')||'null');return user?.id?{id:Number(user.id),username:user.username||null,first_name:user.first_name||null}:null}catch{return null}}
function verifyGuest(token){try{if(!ADMIN_SECRET)return null;const [body,sig]=String(token||'').split('.');if(!body||!sig)return null;const expected=crypto.createHmac('sha256',ADMIN_SECRET).update(body).digest('base64url');if(!safeEqual(sig,expected))return null;const d=JSON.parse(Buffer.from(body,'base64url').toString('utf8'));const id=Number(d.guestId);if(!Number.isSafeInteger(id)||id>=0||Number(d.exp)<Date.now())return null;return{id,username:null,first_name:null}}catch{return null}}
function customer(req){return verifyInitData(req.headers['x-telegram-init-data']||'')||verifyGuest(req.headers['x-guli-guest-token']||'')}
function admin(req){try{if(!ADMIN_SECRET)return false;const h=String(req.headers.authorization||'');if(!h.startsWith('Bearer '))return false;const [body,sig]=h.slice(7).split('.');if(!body||!sig)return false;const expected=crypto.createHmac('sha256',ADMIN_SECRET).update(body).digest('base64url');if(!safeEqual(sig,expected))return false;const d=JSON.parse(Buffer.from(body,'base64url').toString('utf8'));return d.role==='admin'&&Number(d.exp)>Date.now()}catch{return false}}
function install(method,path,handler){const original=express.application[method];express.application[method]=function(routePath,...handlers){if(routePath===path)return original.call(this,routePath,handler,...handlers);return original.call(this,routePath,...handlers)}}
function fail(res,code,message){return res.status(code).json({success:false,message})}
async function telegramApi(method,body){if(!BOT_TOKEN)return null;const r=await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!j.ok)throw new Error(j.description||'Telegram API xatosi');return j.result}
async function notify(userId,text){if(!userId||!BOT_TOKEN)return;try{await telegramApi('sendMessage',{chat_id:Number(userId),text,disable_web_page_preview:true})}catch(e){console.warn('Payment Telegram notification failed:',e.message)}}
async function getOrder(orderNumber,userId){if(!supabase)throw new Error('Supabase sozlanmagan');const {data,error}=await supabase.from('orders').select('*').eq('order_number',orderNumber).eq('telegram_id',userId).maybeSingle();if(error)throw error;return data}
async function expireIfNeeded(order){if(!order||String(order.payment||'')!=='card_manual'||String(order.payment_status||'')==='verified'||String(order.status||'')==='To‘lov qilinmadi')return order;const created=new Date(order.created_at).getTime();if(!Number.isFinite(created)||Date.now()-created<PAYMENT_WINDOW_MS)return order;const {data,error}=await supabase.from('orders').update({status:'To‘lov qilinmadi',payment_status:'rejected',updated_at:new Date().toISOString()}).eq('id',order.id).eq('telegram_id',order.telegram_id).select('*').single();if(error)throw error;return data}

install('get','/api/orders/:orderNumber/payment-state',async(req,res)=>{const user=customer(req);if(!user)return fail(res,401,'Mijoz sessiyasi topilmadi.');try{let order=await getOrder(String(req.params.orderNumber||'').trim(),user.id);if(!order)return fail(res,404,'Buyurtma topilmadi');order=await expireIfNeeded(order);const created=new Date(order.created_at).getTime();const remaining=Math.max(0,PAYMENT_WINDOW_MS-(Date.now()-created));return res.json({success:true,data:{order_number:order.order_number,status:order.status,payment_status:order.payment_status||'pending',payment:order.payment,created_at:order.created_at,remaining_seconds:Math.ceil(remaining/1000),receipt_path:order.payment_receipt_path||null}})}catch(e){console.error('Payment state error:',e);return res.status(500).json({success:false,message:'To‘lov holatini olishda xatolik'})}});

install('get','/api/orders/:orderNumber/receipt',async(req,res)=>{const user=customer(req);if(!user)return fail(res,401,'Mijoz sessiyasi topilmadi.');try{const order=await getOrder(String(req.params.orderNumber||'').trim(),user.id);if(!order)return fail(res,404,'Buyurtma topilmadi');if(!order.payment_receipt_path)return fail(res,404,'Chek hali yuborilmagan');const {data:signed,error}=await supabase.storage.from('payment-receipts').createSignedUrl(String(order.payment_receipt_path).replace(/^\/+/,''),900);if(error)throw error;return res.json({success:true,data:{order_number:order.order_number,total:order.total,payment_status:order.payment_status||'pending',payment_receipt_path:order.payment_receipt_path,receipt_url:signed.signedUrl}})}catch(e){console.error('Customer receipt view error:',e);return res.status(500).json({success:false,message:'Chekni ochishda xatolik'})}});

install('post','/api/orders/:orderNumber/payment-confirm',async(req,res)=>{const user=customer(req);if(!user)return fail(res,401,'Mijoz sessiyasi topilmadi.');try{let order=await getOrder(String(req.params.orderNumber||'').trim(),user.id);if(!order)return fail(res,404,'Buyurtma topilmadi');order=await expireIfNeeded(order);if(String(order.status||'')==='To‘lov qilinmadi')return fail(res,410,'10 daqiqalik to‘lov vaqti tugagan. Buyurtma “To‘lov qilinmadi” holatiga o‘tdi.');if(String(order.payment||'')!=='card_manual')return fail(res,400,'Bu buyurtma karta orqali to‘lov uchun emas.');if(!order.payment_receipt_path)return fail(res,400,'Avval to‘lov chekini yuboring.');const {data,error}=await supabase.from('orders').update({payment_status:'receipt_uploaded',updated_at:new Date().toISOString()}).eq('id',order.id).eq('telegram_id',user.id).select('*').single();if(error)throw error;await notify(order.telegram_id,`💳 To‘lovni tasdiqlash kutilmoq ⏳\n\nBuyurtma № ${order.order_number}\n\nBu bir necha soat vaqt olishi mumkin. To‘lov tasdiqlangach status yangilanadi!`);return res.json({success:true,message:'To‘lov qildim qayd etildi. Admin tasdiqlashi kutilmoqda.',data:{order_number:data.order_number,status:data.status,payment_status:data.payment_status}})}catch(e){console.error('Payment confirm error:',e);return res.status(500).json({success:false,message:e.message||'To‘lovni tasdiqlashda xatolik'})}});

install('post','/api/orders/:orderNumber/payment-timeout',async(req,res)=>{const user=customer(req);if(!user)return fail(res,401,'Mijoz sessiyasi topilmadi.');try{let order=await getOrder(String(req.params.orderNumber||'').trim(),user.id);if(!order)return fail(res,404,'Buyurtma topilmadi');const created=new Date(order.created_at).getTime();if(Number.isFinite(created)&&Date.now()-created<PAYMENT_WINDOW_MS)return fail(res,409,'To‘lov vaqti hali tugamagan.');order=await expireIfNeeded(order);return res.json({success:true,data:{order_number:order.order_number,status:order.status,payment_status:order.payment_status}})}catch(e){console.error('Payment timeout error:',e);return res.status(500).json({success:false,message:'To‘lov vaqtini yakunlashda xatolik'})}});

install('put','/api/admin/orders/:id/payment',async(req,res)=>{if(!admin(req))return fail(res,401,'Admin sessiyasi yaroqsiz yoki tugagan');try{if(!supabase)throw new Error('Supabase sozlanmagan');const s=['pending','receipt_uploaded','verified','rejected'].includes(String(req.body?.payment_status))?String(req.body.payment_status):null;if(!s)return fail(res,400,'To‘lov holati noto‘g‘ri');const {data:before,error:be}=await supabase.from('orders').select('*').eq('id',req.params.id).maybeSingle();if(be)throw be;if(!before)return fail(res,404,'Buyurtma topilmadi');const patch={payment_status:s,payment_verified_at:s==='verified'?new Date().toISOString():null,updated_at:new Date().toISOString(),status:s==='verified'&&String(before.status)==='To‘lov qilinmadi'?'Qabul qilindi':before.status};const {data,error}=await supabase.from('orders').update(patch).eq('id',req.params.id).select('*').single();if(error)throw error;if(s==='verified')await notify(data.telegram_id,`✅ To‘lov tasdiqlandi!\n\nBuyurtma № ${data.order_number}\nSumma: ${Math.round(Number(data.total)||0).toLocaleString('uz-UZ')} so‘m\n\nBuyurtma holati: ${data.status}`);if(s==='rejected')await notify(data.telegram_id,`⚠️ To‘lov cheki rad etildi.\n\nBuyurtma № ${data.order_number}\nIltimos, to‘lov chekini qayta yuboring.`);return res.json({success:true,data})}catch(e){console.error('Admin payment status error:',e);return res.status(/payment_status|payment_verified_at/i.test(e.message||'')?503:500).json({success:false,message:/payment_status|payment_verified_at/i.test(e.message||'')?'To‘lov ustunlari bazada hali tayyor emas. SQL migration\'ni ishga tushiring.':'To‘lov holatini yangilashda xatolik'})}});
