// Final receipt-upload guard. Loaded after manualCardPaymentPatch so the upload
// endpoint cannot accept a receipt after the 10-minute card-payment window.
const express=require('express');
const crypto=require('crypto');
const {createClient}=require('@supabase/supabase-js');
const RURL=process.env.SUPABASE_URL||'', RKEY=process.env.SUPABASE_SECRET_KEY||'', RTOKEN=process.env.TELEGRAM_BOT_TOKEN||'', RSECRET=process.env.ADMIN_SECRET||'';
const rsupabase=RURL&&RKEY?createClient(RURL,RKEY,{auth:{persistSession:false,autoRefreshToken:false}}):null;
const RWINDOW=10*60*1000;
function reqEq(a,b){const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function rTelegram(init){if(!RTOKEN||!init)return null;try{const p=new URLSearchParams(init),h=p.get('hash'),ad=Number(p.get('auth_date'));if(!h||!Number.isFinite(ad)||Math.abs(Math.floor(Date.now()/1000)-ad)>86400)return null;const pairs=[];p.forEach((v,k)=>{if(k!=='hash')pairs.push(`${k}=${v}`)});pairs.sort();const secret=crypto.createHmac('sha256','WebAppData').update(RTOKEN).digest();const calc=crypto.createHmac('sha256',secret).update(pairs.join('\n')).digest('hex');if(!reqEq(calc,h))return null;const u=JSON.parse(p.get('user')||'null');return u?.id?{id:Number(u.id)}:null}catch{return null}}
function rGuest(token){try{if(!RSECRET)return null;const [body,sig]=String(token||'').split('.');const expected=crypto.createHmac('sha256',RSECRET).update(body).digest('base64url');if(!body||!sig||!reqEq(sig,expected))return null;const d=JSON.parse(Buffer.from(body,'base64url').toString('utf8'));const id=Number(d.guestId);return Number.isSafeInteger(id)&&id<0&&Number(d.exp)>Date.now()?{id}:null}catch{return null}}
function rCustomer(req){return rTelegram(req.headers['x-telegram-init-data']||'')||rGuest(req.headers['x-guli-guest-token']||'')}
function rInstall(method,path,handler){const original=express.application[method];express.application[method]=function(routePath,...handlers){if(routePath===path)return original.call(this,routePath,handler,...handlers);return original.call(this,routePath,...handlers)}}
async function rBucket(){const b=await rsupabase.storage.getBucket('payment-receipts');if(!b.error)return;const c=await rsupabase.storage.createBucket('payment-receipts',{public:false,allowedMimeTypes:['image/jpeg','image/png','image/webp','application/pdf'],fileSizeLimit:'6MB'});if(c.error&&!/already exists|duplicate/i.test(c.error.message||''))throw c.error}
rInstall('post','/api/orders/:orderNumber/receipt',async(req,res)=>{const u=rCustomer(req);if(!u)return res.status(401).json({success:false,message:'Mijoz sessiyasi topilmadi.'});try{const number=String(req.params.orderNumber||'').trim();const {data:o,error:oe}=await rsupabase.from('orders').select('id,order_number,total,telegram_id,payment,payment_status,created_at').eq('order_number',number).eq('telegram_id',u.id).maybeSingle();if(oe)throw oe;if(!o)return res.status(404).json({success:false,message:'Buyurtma topilmadi'});if(String(o.payment)!=='card_manual')return res.status(400).json({success:false,message:'Bu buyurtma karta orqali to‘lov uchun yaratilmagan'});const created=new Date(o.created_at).getTime();if(Number.isFinite(created)&&Date.now()-created>=RWINDOW){if(String(o.status||'')!=='To‘lov qilinmadi'){await rsupabase.from('orders').update({status:'To‘lov qilinmadi',payment_status:'rejected',updated_at:new Date().toISOString()}).eq('id',o.id).eq('telegram_id',u.id)}return res.status(410).json({success:false,message:'10 daqiqalik to‘lov vaqti tugagan. Buyurtma “To‘lov qilinmadi” holatiga o‘tdi.'})}if(String(o.payment_status||'')==='verified')return res.status(409).json({success:false,message:'Bu to‘lov allaqachon tasdiqlangan.'});const {data,mimeType,extension}=req.body||{};if(!data||typeof data!=='string')return res.status(400).json({success:false,message:'Chek rasmi topilmadi'});if(!/^image\/(jpeg|png|webp)$/.test(String(mimeType||''))&&mimeType!=='application/pdf')return res.status(400).json({success:false,message:'Chek faqat JPG, PNG, WEBP yoki PDF bo‘lishi mumkin'});if(data.length>8200000)return res.status(413).json({success:false,message:'Chek hajmi juda katta'});await rBucket();const ext=String(extension||(mimeType==='application/pdf'?'pdf':'jpg')).replace(/[^a-z0-9]/gi,'').toLowerCase()||'jpg';const path=`receipts/${o.id}/${Date.now()}-${crypto.randomBytes(6).toString('hex')}.${ext}`;const up=await rsupabase.storage.from('payment-receipts').upload(path,Buffer.from(data,'base64'),{contentType:mimeType,cacheControl:'31536000',upsert:false});if(up.error)throw up.error;const {data:updated,error:ue}=await rsupabase.from('orders').update({payment_receipt_path:path,payment_status:'receipt_uploaded',payment_receipt_uploaded_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',o.id).eq('telegram_id',u.id).select('id,order_number,total,payment_status,payment_receipt_uploaded_at').single();if(ue)throw ue;res.json({success:true,message:'Chek muvaffaqiyatli yuborildi. Endi “To‘lov qildim”ni bosing.',data:updated})}catch(e){console.error('Receipt window error:',e);res.status(500).json({success:false,message:/payment_receipt|payment_status/i.test(e.message||'')?'To‘lov ustunlari bazada hali tayyor emas. SQL migrationni bir marta ishga tushiring.':'Chekni yuborishda xatolik'})}});
