// Standalone customer review runtime. The older reviewPatch files depend on
// index.js module-local variables, so this version is self-contained and is
// loaded with Node -r before the main server.
const express = require('express');
const crypto = require('crypto');
const { createClient } = require('@supabase/supabase-js');
const SUPABASE_URL=process.env.SUPABASE_URL||'';
const SUPABASE_KEY=process.env.SUPABASE_SECRET_KEY||'';
const BOT_TOKEN=process.env.TELEGRAM_BOT_TOKEN||'';
const ADMIN_SECRET=process.env.ADMIN_SECRET||'';
const supabase=SUPABASE_URL&&SUPABASE_KEY?createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}):null;
const MAX_PHOTOS=3,MAX_PHOTO_BYTES=220*1024;
function safeEqual(a,b){const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function telegramUser(initData){if(!BOT_TOKEN||!initData)return null;try{const p=new URLSearchParams(initData),hash=p.get('hash'),auth=Number(p.get('auth_date'));if(!hash||!Number.isFinite(auth)||Math.abs(Math.floor(Date.now()/1000)-auth)>86400)return null;const pairs=[];p.forEach((v,k)=>{if(k!=='hash')pairs.push(`${k}=${v}`)});pairs.sort();const secret=crypto.createHmac('sha256','WebAppData').update(BOT_TOKEN).digest();const calc=crypto.createHmac('sha256',secret).update(pairs.join('\n')).digest('hex');if(!safeEqual(calc,hash))return null;const u=JSON.parse(p.get('user')||'null');return u?.id?{id:Number(u.id),username:u.username||null,first_name:u.first_name||null,last_name:u.last_name||null}:null}catch{return null}}
function requireTelegram(req,res,next){const user=telegramUser(req.headers['x-telegram-init-data']||'');if(!user)return res.status(401).json({success:false,message:'Telegram sessiyasi tasdiqlanmadi. Mini App ichidan qayta oching.'});req.telegramUser=user;next()}
function admin(req){try{if(!ADMIN_SECRET)return false;const h=String(req.headers.authorization||'');if(!h.startsWith('Bearer '))return false;const [body,sig]=h.slice(7).split('.');const expected=crypto.createHmac('sha256',ADMIN_SECRET).update(body).digest('base64url');if(!safeEqual(sig,expected))return false;const p=JSON.parse(Buffer.from(body,'base64url').toString('utf8'));return p.role==='admin'&&Number(p.exp)>Date.now()}catch{return false}}
function install(method,path,handler){const original=express.application[method];express.application[method]=function(routePath,...handlers){if(routePath===path)return original.call(this,routePath,handler,...handlers);return original.call(this,routePath,...handlers)}}
function display(row){const f=String(row?.first_name||'').trim(),u=String(row?.username||'').trim();return f&&u?`${f} (@${u})`:f||u?`@${u}`:'GULI mijozi'}
function parsePhoto(value){const m=String(value||'').match(/^data:(image\/(?:jpeg|jpg|png|webp));base64,(.+)$/i);if(!m)return null;const mime=m[1].toLowerCase().replace('jpg','jpeg'),buffer=Buffer.from(m[2],'base64');if(!buffer.length||buffer.length>MAX_PHOTO_BYTES)return null;return{mime,buffer,ext:mime==='image/png'?'png':mime==='image/webp'?'webp':'jpg'}}
async function bucket(){if(!supabase)throw new Error('Supabase sozlanmagan');const b=await supabase.storage.getBucket('review-images');if(!b.error)return;const c=await supabase.storage.createBucket('review-images',{public:true,allowedMimeTypes:['image/jpeg','image/png','image/webp'],fileSizeLimit:'220KB'});if(c.error&&!/already exists|duplicate/i.test(c.error.message||''))throw c.error}
async function verifiedOrder(userId,productId,code){const {data,error}=await supabase.from('orders').select('order_number,status,items,created_at').eq('telegram_id',userId).order('created_at',{ascending:false}).limit(500);if(error)throw error;return(data||[]).find(o=>String(o.status||'')==='Yetkazildi'&&(Array.isArray(o.items)?o.items:[]).some(item=>{const p=item?.product||{};return String(p.id??item?.product_id)===String(productId)||String(p.product_code||item?.product_code||'')===String(code)}))||null}
install('get','/api/reviews',async(req,res)=>{try{const code=String(req.query.product_code||'').trim();if(!/^\d{6}$/.test(code))return res.status(400).json({success:false,message:'Mahsulot kodi noto‘g‘ri'});const {data:p,error:pe}=await supabase.from('products').select('id,product_code,rating,reviews').eq('product_code',code).maybeSingle();if(pe)throw pe;if(!p)return res.status(404).json({success:false,message:'Mahsulot topilmadi'});const {data,error}=await supabase.from('product_reviews').select('id,rating,comment,photos,username,first_name,created_at,verified_purchase,order_number').eq('product_id',p.id).eq('status','approved').order('created_at',{ascending:false}).limit(100);if(error)throw error;const rows=(data||[]).map(r=>({...r,display_name:display(r),photos:Array.isArray(r.photos)?r.photos:[]}));const liveSum=rows.reduce((n,r)=>n+Number(r.rating||0),0),legacyCount=Math.max(0,Number(p.reviews||0)),legacyAvg=Math.max(0,Number(p.rating||0)),totalCount=legacyCount+rows.length;const avg=totalCount?Math.round(((legacyAvg*legacyCount+liveSum)/totalCount)*100)/100:0;const distribution=[5,4,3,2,1].map(star=>({star,count:rows.filter(r=>Number(r.rating)===star).length}));res.json({success:true,data:{reviews:rows,distribution,live_count:rows.length,total_count:totalCount,total_average:avg}})}catch(e){console.error('Reviews GET:',e);res.status(500).json({success:false,message:'Sharhlarni yuklashda xatolik'})}});
install('get','/api/reviews/can-review',requireTelegram,async(req,res)=>{try{const code=String(req.query.product_code||'').trim();if(!/^\d{6}$/.test(code))return res.status(400).json({success:false,message:'Mahsulot kodi noto‘g‘ri'});const {data:p,error}=await supabase.from('products').select('id,product_code,name').eq('product_code',code).maybeSingle();if(error)throw error;if(!p)return res.status(404).json({success:false,message:'Mahsulot topilmadi'});const order=await verifiedOrder(req.telegramUser.id,p.id,code);if(!order)return res.json({success:true,data:{eligible:false,reason:'Baho berish faqat yetkazilgan buyurtmadan keyin mumkin.'}});const {data:existing,error:ee}=await supabase.from('product_reviews').select('id,rating,comment,photos,created_at').eq('product_id',p.id).eq('telegram_id',req.telegramUser.id).eq('order_number',order.order_number).maybeSingle();if(ee)throw ee;res.json({success:true,data:{eligible:true,verified_purchase:true,order_number:order.order_number,existing:existing||null}})}catch(e){console.error('Review eligibility:',e);res.status(500).json({success:false,message:'Baho berish imkonini tekshirishda xatolik'})}});
install('post','/api/reviews',requireTelegram,async(req,res)=>{try{const code=String(req.body?.product_code||'').trim(),rating=Number(req.body?.rating),comment=String(req.body?.comment||'').trim();if(!/^\d{6}$/.test(code))return res.status(400).json({success:false,message:'Mahsulot kodi noto‘g‘ri'});if(!Number.isInteger(rating)||rating<1||rating>5)return res.status(400).json({success:false,message:'Baho 1 dan 5 gacha bo‘lishi kerak'});if(comment.length<3||comment.length>1200)return res.status(400).json({success:false,message:'Sharh 3–1200 belgi bo‘lishi kerak'});const {data:p,error:pe}=await supabase.from('products').select('id,product_code,name').eq('product_code',code).maybeSingle();if(pe)throw pe;if(!p)return res.status(404).json({success:false,message:'Mahsulot topilmadi'});const order=await verifiedOrder(req.telegramUser.id,p.id,code);if(!order)return res.status(403).json({success:false,message:'Faqat yetkazilgan buyurtma uchun sharh qoldirish mumkin.'});const {data:dup,error:de}=await supabase.from('product_reviews').select('id').eq('product_id',p.id).eq('telegram_id',req.telegramUser.id).eq('order_number',order.order_number).maybeSingle();if(de)throw de;if(dup)return res.status(409).json({success:false,message:'Bu buyurtma uchun sharh allaqachon qoldirilgan.'});const photos=[];for(const raw of(Array.isArray(req.body?.photos)?req.body.photos.slice(0,MAX_PHOTOS):[])){const parsed=parsePhoto(raw);if(!parsed)continue;try{await bucket();const path=`${req.telegramUser.id}/${p.id}/${Date.now()}-${crypto.randomBytes(5).toString('hex')}.${parsed.ext}`;const up=await supabase.storage.from('review-images').upload(path,parsed.buffer,{contentType:parsed.mime,cacheControl:'31536000',upsert:false});if(!up.error){const pub=supabase.storage.from('review-images').getPublicUrl(path);if(pub.data?.publicUrl)photos.push(pub.data.publicUrl)}}catch(e){console.warn('Review photo upload skipped:',e.message)}}const row={product_id:p.id,product_code:code,telegram_id:req.telegramUser.id,username:req.telegramUser.username||null,first_name:req.telegramUser.first_name||null,rating,comment,photos,verified_purchase:true,order_number:order.order_number,status:'approved',created_at:new Date().toISOString(),updated_at:new Date().toISOString()};const {data,error}=await supabase.from('product_reviews').insert([row]).select('id,rating,comment,photos,username,first_name,created_at,verified_purchase,order_number').single();if(error)throw error;res.status(201).json({success:true,message:'Sharhingiz e’lon qilindi ✓',data:{...data,display_name:display(data)}})}catch(e){console.error('Review POST:',e);res.status(500).json({success:false,message:'Sharhni saqlashda xatolik'})}});
install('get','/api/admin/reviews',async(req,res)=>{if(!admin(req))return res.status(401).json({success:false,message:'Admin sessiyasi yaroqsiz yoki tugagan'});try{const {data,error}=await supabase.from('product_reviews').select('*').order('created_at',{ascending:false}).limit(500);if(error)throw error;res.json({success:true,data:data||[]})}catch(e){res.status(500).json({success:false,message:'Sharhlarni yuklashda xatolik'})}});
install('patch','/api/admin/reviews/:id',async(req,res)=>{if(!admin(req))return res.status(401).json({success:false,message:'Admin sessiyasi yaroqsiz yoki tugagan'});try{const status=['approved','hidden'].includes(String(req.body?.status))?String(req.body.status):null;if(!status)return res.status(400).json({success:false,message:'Sharh holati noto‘g‘ri'});const {data,error}=await supabase.from('product_reviews').update({status,updated_at:new Date().toISOString()}).eq('id',req.params.id).select().single();if(error)throw error;res.json({success:true,data})}catch(e){res.status(500).json({success:false,message:'Sharh holatini o‘zgartirishda xatolik'})}});
install('delete','/api/admin/reviews/:id',async(req,res)=>{if(!admin(req))return res.status(401).json({success:false,message:'Admin sessiyasi yaroqsiz yoki tugagan'});try{const {error}=await supabase.from('product_reviews').delete().eq('id',req.params.id);if(error)throw error;res.json({success:true})}catch(e){res.status(500).json({success:false,message:'Sharhni o‘chirishda xatolik'})}});
