// Telegram chat discovery + verification runtime.
// Loaded by customerServer before app.listen, so it can wrap the already-registered webhook route.
const express = require("express");
const { createClient } = require("@supabase/supabase-js");
const crypto = require("crypto");
const supabase = process.env.SUPABASE_URL && process.env.SUPABASE_SECRET_KEY ? createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SECRET_KEY, { auth: { persistSession: false, autoRefreshToken: false } }) : null;
function token(){return String(process.env.TELEGRAM_BOT_TOKEN||"").trim()}
function admin(req){const h=String(req.headers.authorization||"");if(!h.startsWith("Bearer ")||!process.env.ADMIN_SECRET)return false;try{const[b,s]=h.slice(7).split("."),e=crypto.createHmac("sha256",process.env.ADMIN_SECRET).update(b).digest("base64url"),p=JSON.parse(Buffer.from(b,"base64url").toString("utf8"));return s===e&&p.role==="admin"&&Number(p.exp)>Date.now()}catch{return false}}
async function tg(method,body){const t=token();if(!t)throw new Error("TELEGRAM_BOT_TOKEN sozlanmagan");const r=await fetch(`https://api.telegram.org/bot${t}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw new Error(j?.description||`Telegram API ${r.status}`);return j.result}
function row(chat,member){const status=String(member?.status||"");return{chat_id:String(chat.id),title:chat.title||chat.username||String(chat.id),username:chat.username||null,chat_type:["group","supergroup","channel"].includes(chat.type)?chat.type:"supergroup",bot_status:status,can_post_messages:status==="creator"||status==="administrator"&&chat.type!=="channel"?true:status==="administrator"&&member?.can_post_messages!==false,active:true,updated_at:new Date().toISOString()}}
function canPost(chat,member){const s=String(member?.status||"");if(s==="creator")return true;if(s!=="administrator")return false;return chat?.type==="channel"?member?.can_post_messages!==false:member?.can_send_messages!==false}
async function save(chat,member){if(!supabase||!chat?.id)return null;const r=row(chat,member);r.can_post_messages=canPost(chat,member);r.active=r.can_post_messages;const{data,error}=await supabase.from("telegram_broadcast_chats").upsert(r,{onConflict:"chat_id"}).select("*").single();if(error)throw error;return data}
async function discover(payload){const change=payload?.my_chat_member||payload?.chat_member,chat=change?.chat,member=change?.new_chat_member;if(!chat?.id||!member||!supabase)return;const me=await tg("getMe",{});if(Number(member?.user?.id||0)!==Number(me?.id||0))return;const status=String(member.status||"");if(status==="administrator"||status==="creator"){if(canPost(chat,member)){await save(chat,member);console.log(`[Telegram auto chat discovery] ${chat.id} ${chat.title||"private group"}`)}}else if(status==="left"||status==="kicked"){await supabase.from("telegram_broadcast_chats").update({active:false,can_post_messages:false,bot_status:status,updated_at:new Date().toISOString()}).eq("chat_id",String(chat.id))}}
const originalListen=express.application.listen;
express.application.listen=function(...args){const app=this;
  const webhook=(app._router?.stack||[]).find(l=>l.route?.path==="/api/telegram/webhook"&&l.route?.methods?.post);
  if(webhook?.route?.stack?.length){const index=webhook.route.stack.length-1,original=webhook.route.stack[index].handle;webhook.route.stack[index].handle=async(req,res,next)=>{try{await discover(req.body)}catch(e){console.error("[Telegram auto chat discovery]",e?.message||e)}return original(req,res,next)}}
  app.get("/api/admin/telegram-config",async(req,res)=>{if(!admin(req))return res.status(401).json({success:false,message:"Admin sessiyasi tasdiqlanmadi"});try{const{data,error}=await supabase.from("telegram_broadcast_chats").select("chat_id,title,username,chat_type,bot_status,can_post_messages,active,updated_at").order("updated_at",{ascending:false});if(error)throw error;res.json({success:true,data:{botConfigured:Boolean(token()),chats:data||[]}})}catch(e){res.status(500).json({success:false,message:e?.message||"Telegram sozlamalarini yuklashda xatolik"})}});
  app.post("/api/admin/telegram-config/chat",async(req,res)=>{if(!admin(req))return res.status(401).json({success:false,message:"Admin sessiyasi tasdiqlanmadi"});const raw=String(req.body?.chatId||"").trim();if(!raw)return res.status(400).json({success:false,message:"Kanal/guruh ID kiritilmagan"});try{const chat=await tg("getChat",{chat_id:raw});const me=await tg("getMe",{}),member=await tg("getChatMember",{chat_id:chat.id,user_id:me.id});if(!canPost(chat,member))return res.status(400).json({success:false,message:`Bot bu chatda admin yoki post huquqiga ega emas (status: ${member.status||"unknown"})`});const data=await save(chat,member);res.json({success:true,message:`${chat.title||chat.username||chat.id} saqlandi — bot post qila oladi ✅`,data})}catch(e){res.status(400).json({success:false,message:e?.message||"Telegram chatni tekshirishda xatolik"})}});
  return originalListen.apply(this,args)
};
