// Hardening layer for the admin Telegram bot.
// 1) Telegram editMessageMedia must reference the multipart FIELD name (attach://photo),
//    not the uploaded filename. This prevents "InputMedia: media not found".
// 2) The final worker historically treated duplicate online-chat claims as successful;
//    persist a durable content hash and suppress repeats before Telegram sendMessage.
(() => {
  const crypto = require('crypto');
  const { createClient } = require('@supabase/supabase-js');
  const ADMIN_TOKEN = String(process.env.TELEGRAM_ADMIN_BOT_TOKEN || '').trim();
  const URL_ = String(process.env.SUPABASE_URL || '').trim();
  const KEY = String(process.env.SUPABASE_SECRET_KEY || '').trim();
  const db = URL_ && KEY ? createClient(URL_, KEY, { auth: { persistSession: false, autoRefreshToken: false } }) : null;
  const nativeFetch = globalThis.fetch;
  if (!nativeFetch || globalThis.__GULI_ADMIN_BOT_HARDENING__) return;
  globalThis.__GULI_ADMIN_BOT_HARDENING__ = true;

  async function dedupeOnlineChat(body) {
    if (!db || !body || typeof body.get !== 'function') return true;
    const text = String(body.get('text') || '');
    if (!/^💬 ONLINE CHAT/i.test(text.trim())) return true;
    const key = `admin-online-chat:${crypto.createHash('sha256').update(text).digest('hex')}`;
    try {
      const { error } = await db.from('telegram_admin_bot_events').insert({ event_key: key, event_type: 'online_chat', order_id: null });
      if (!error) return true;
      if (String(error.code) === '23505') return false;
    } catch {}
    return true;
  }

  globalThis.fetch = async (input, init) => {
    const url = String(typeof input === 'string' ? input : input?.url || '');
    if (!url.includes('api.telegram.org')) return nativeFetch(input, init);

    // Fix the final worker's multipart InputMedia reference.
    if (url.includes(`/bot${ADMIN_TOKEN}/editMessageMedia`) && init?.body && typeof init.body.get === 'function') {
      try {
        const original = init.body;
        const mediaRaw = String(original.get('media') || '');
        if (mediaRaw.includes('attach://order.jpg')) {
          const media = JSON.parse(mediaRaw);
          media.media = 'attach://photo';
          const form = new FormData();
          for (const [k, v] of original.entries()) {
            if (k === 'media') form.append('media', JSON.stringify(media));
            else form.append(k, v);
          }
          init = { ...(init || {}), body: form, headers: undefined };
        }
      } catch {}
    }

    // Durable dedupe for online-chat messages generated by the final worker.
    if (url.includes(`/bot${ADMIN_TOKEN}/sendMessage`) && init?.body && typeof init.body.get === 'function') {
      const allow = await dedupeOnlineChat(init.body);
      if (!allow) {
        return new Response(JSON.stringify({ ok: true, result: { message_id: 0, __guli_duplicate: true } }), {
          status: 200,
          headers: { 'content-type': 'application/json' },
        });
      }
    }
    return nativeFetch(input, init);
  };
})();
