// GULI production admin bot: one editable message per order; receipt/product media is merged into the same message.
const crypto=require('crypto');const sharp=require('sharp');const {createClient}=require('@supabase/supabase-js');
const ADMIN_BOT=String(process.env.TELEGRAM_ADMIN_BOT_TOKEN||'').trim(),CUSTOMER_BOT=String(process.env.TELEGRAM_BOT_TOKEN||'').trim(),URL=String(process.env.SUPABASE_URL||'').trim(),KEY=String(process.env.SUPABASE_SECRET_KEY||'').trim();
const db=URL&&KEY?createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}}):null;
const state=globalThis.__GULI_ADMIN_PROD_BOT__||{running:false,offset:0,sigs:new Map(),startedAt:new Date().toISOString()};globalThis.__GULI_ADMIN_PROD_BOT__=state;if(!state.startedAt)state.startedAt=new Date().toISOString();
async function tg(method,body,token=ADMIN_BOT){if(!token)throw Error('Telegram bot token sozlanmagan');const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw Error(j?.description||`Telegram ${r.status}`);return j.result}
async function admins(){const s=new Set(String(process.env.TELEGRAM_ADMIN_CHAT_IDS||'').split(',').map(x=>x.trim()).filter(Boolean));if(db){const r=await db.from('telegram_admin_bot_chats').select('chat_id').eq('active',true);for(const x of r.data||[])s.add(String(x.chat_id))}return[...s]}
const money=v=>`${Math.round(Number(v||0)).toLocaleString('uz-UZ')} so‘m`;
function caption(o,title='🛒 YANGI BUYURTMA'){const items=Array.isArray(o.items)?o.items:[],lines=items.slice(0,15).map((x,i)=>{const p=x?.product||x?.product_data||x?.productDetails||x||{};return`${i+1}. ${p.name||p.title||x.name||'Mahsulot'}${p.product_code||x.product_code?` #${p.product_code||x.product_code}`:''} × ${Number(x.quantity||x.qty||1)} dona`});const ps=String(o.payment_status||'pending').toLowerCase();const pay=ps==='verified'?'✅ To‘lov tasdiqlangan':ps==='rejected'?'❌ Chek rad etilgan':ps==='receipt_uploaded'?'🧾 Chek yuklangan — tekshirish kutilmoqda':'⏳ To‘lov kutilmoqda';return[`<b>${title}</b>`,`🛒 <b>№:</b> <code>${o.order_number||o.id}</code>`,`👤 <b>Mijoz:</b> ${o.customer_name||[o.first_name,o.last_name].filter(Boolean).join(' ')||o.username||'Mijoz'}`,`📞 <b>Telefon:</b> ${o.phone||'—'}`,`💰 <b>Jami:</b> ${money(o.total)}`,`💳 <b>To‘lov:</b> ${o.payment||'—'}`,`🔎 <b>To‘lov holati:</b> ${pay}`,`📦 <b>Status:</b> ${o.status||'⏳ Buyurtma kutilmoqda'}`,'',`👗 <b>Mahsulotlar (${items.length} ta):</b>`,lines.join('\n')||'—','',`🧾 <b>Cheklar:</b> ${Array.isArray(o.payment_receipt_history)?o.payment_receipt_history.length:(o.payment_receipt_path?1:0)} ta`].join('\n').slice(0,3900)}
function keyboard(o){const ps=String(o.payment_status||'pending').toLowerCase();return o?.id&&['pending','receipt_uploaded'].includes(ps)?{inline_keyboard:[[{text:'✅ To‘lovni tasdiqlash',callback_data:`guli_pay:verified:${o.id}`},{text:'❌ Chekni rad etish',callback_data:`guli_pay:rejected:${o.id}`}]]}:{inline_keyboard:[]}}
function productImages(o){const out=[];for(const x of Array.isArray(o.items)?o.items:[]){const p=x?.product||x?.product_data||x?.productDetails||{};for(const u of [x.image,x.image_url,x.photo,p.image,p.image_url,...(Array.isArray(p.images)?p.images:[])])if(typeof u==='string'&&/^https?:\/\//i.test(u)&&!out.includes(u)){out.push(u);break}}return out}
async function signed(path){if(!db||!path)return'';try{return(await db.storage.from('payment-receipts').createSignedUrl(String(path).replace(/^\/+/,''),86400)).data?.signedUrl||''}catch{return''}}
async function receiptImages(o){const h=Array.isArray(o.payment_receipt_history)?o.payment_receipt_history:[],paths=h.map(x=>x?.path).filter(Boolean);if(o.payment_receipt_path&&!paths.includes(o.payment_receipt_path))paths.push(o.payment_receipt_path);const out=[];for(const p of paths){const u=await signed(p);if(u)out.push(u)}return out}
async function collage(o){const urls=[...productImages(o),...(await receiptImages(o))].slice(0,10),imgs=[];for(const u of urls){try{const r=await fetch(u);if(r.ok)imgs.push(await sharp(Buffer.from(await r.arrayBuffer())).resize(420,420,{fit:'cover'}).jpeg({quality:86}).toBuffer())}catch{}}if(!imgs.length)return null;const size=420,gap=8,cols=Math.min(3,imgs.length),rows=Math.ceil(imgs.length/3),input=imgs.map((b,i)=>({input:b,left:(i%3)*(size+gap),top:Math.floor(i/3)*(size+gap)}));return sharp({create:{width:cols*size+(cols-1)*gap,height:rows*size+(rows-1)*gap,channels:3,background:'#fff'}}).composite(input).jpeg({quality:88}).toBuffer()}
async function existing(orderId,chatId){if(!db)return null;const r=await db.from('telegram_admin_bot_order_messages').select('message_id').eq('order_id',String(orderId)).eq('chat_id',Number(chatId)).maybeSingle();return r.data?.message_id?Number(r.data.message_id):null}
async function save(orderId,chatId,messageId){if(db&&messageId)await db.from('telegram_admin_bot_order_messages').upsert({order_id:String(orderId),chat_id:Number(chatId),message_id:Number(messageId),updated_at:new Date().toISOString()},{onConflict:'order_id,chat_id'})}
async function sendOrEdit(chatId,o,title){const mid=await existing(o.id,chatId),buf=await collage(o),cap=caption(o,title),kb=keyboard(o);if(mid&&buf){const f=new FormData();f.append('chat_id',String(chatId));f.append('message_id',String(mid));f.append('media',JSON.stringify({type:'photo',media:'attach://guli_order',caption:cap,parse_mode:'HTML'}));f.append('reply_markup',JSON.stringify(kb));f.append('guli_order',new Blob([buf],{type:'image/jpeg'}),'guli_order.jpg');try{const r=await fetch(`https://api.telegram.org/bot${ADMIN_BOT}/editMessageMedia`,{method:'POST',body:f});if(r.ok&&(await r.json().catch(()=>null))?.ok)return mid}catch{}}if(mid){try{await tg('editMessageCaption',{chat_id:chatId,message_id:mid,caption:cap,parse_mode:'HTML',reply_markup:kb});return mid}catch{try{await tg('editMessageText',{chat_id:chatId,message_id:mid,text:cap,parse_mode:'HTML',reply_markup:kb});return mid}catch{}}}let sent=null;if(buf){const f=new FormData();f.append('chat_id',String(chatId));f.append('caption',cap);f.append('parse_mode','HTML');f.append('reply_markup',JSON.stringify(kb));f.append('photo',new Blob([buf],{type:'image/jpeg'}),'guli_order.jpg');const r=await fetch(`https://api.telegram.org/bot${ADMIN_BOT}/sendPhoto`,{method:'POST',body:f});const j=await r.json().catch(()=>null);if(j?.ok)sent=j.result}if(!sent)sent=await tg('sendMessage',{chat_id:chatId,text:cap,parse_mode:'HTML',reply_markup:kb});await save(o.id,chatId,sent?.message_id);return sent?.message_id||null}
async function updateCustomer(o){if(!CUSTOMER_BOT||!o?.telegram_id||!o?.telegram_status_message_id)return;const items=Array.isArray(o.items)?o.items:[],lines=items.slice(0,15).map(x=>{const p=x?.product||x?.product_data||x||{};return`• ${p.name||p.title||x.name||'Mahsulot'} × ${Number(x.quantity||x.qty||1)} dona`}),ps=String(o.payment_status||'pending').toLowerCase(),pay=ps==='verified'?'✅ To‘lov tasdiqlandi':ps==='rejected'?'❌ Chek rad etildi':ps==='receipt_uploaded'?'🧾 Chek qabul qilindi — tekshirilmoqda':'⏳ To‘lov kutilmoqda',body=[`🛍 <b>GULI Lingerie — BUYURTMA</b>`,`№ <b>${o.order_number||o.id}</b>`,``,`📦 <b>Buyurtma statusi:</b> <b>${o.status||'⏳ Buyurtma kutilmoqda'}</b>`,`💳 <b>To‘lov:</b> ${pay}`,'',`👗 <b>Mahsulotlar (${items.length} ta):</b>`,lines.join('\n')||'—','',`💰 <b>Jami:</b> ${money(o.total)}`].join('\n').slice(0,3900);try{await tg('editMessageText',{chat_id:Number(o.telegram_id),message_id:Number(o.telegram_status_message_id),text:body,parse_mode:'HTML',disable_web_page_preview:true},CUSTOMER_BOT)}catch(e){if(!/message is not modified/i.test(e.message||''))console.warn('[GULI customer status edit]',e.message)}}
async function getOrder(id){if(!db)return null;let r=await db.from('orders').select('*').eq('id',id).maybeSingle();if(!r.data&&/GULI-/i.test(String(id)))r=await db.from('orders').select('*').eq('order_number',id).maybeSingle();return r.data||null}
async function callback(c){const chat=Number(c?.message?.chat?.id||0),from=Number(c?.from?.id||0),d=String(c?.data||'');if(!chat||chat!==from||!d.startsWith('guli_pay:'))return;const ids=await admins();if(!ids.includes(String(chat))){await tg('answerCallbackQuery',{callback_query_id:c.id,text:'⛔ Ruxsat yo‘q',show_alert:true}).catch(()=>{});return}const[,decision,id]=d.split(':');if(!['verified','rejected'].includes(decision)||!id)return;const o=await getOrder(id);if(!o)return;const ps=String(o.payment_status||'pending');if(!['pending','receipt_uploaded'].includes(ps)){await tg('answerCallbackQuery',{callback_query_id:c.id,text:'Bu to‘lov bo‘yicha qaror allaqachon qabul qilingan'}).catch(()=>{});return}const patch={payment_status:decision,status:decision==='verified'?'Qabul qilindi':'Bekor qilindi',updated_at:new Date().toISOString()};patch[decision==='verified'?'payment_verified_at':'payment_rejected_at']=new Date().toISOString();const r=await db.from('orders').update(patch).eq('id',o.id).select('*').single();if(r.error)throw r.error;await sendOrEdit(chat,r.data,decision==='verified'?'💳 TO‘LOV TASDIQLANDI':'💳 TO‘LOV RAD ETILDI');await updateCustomer(r.data);await tg('answerCallbackQuery',{callback_query_id:c.id,text:decision==='verified'?'✅ To‘lov tasdiqlandi':'❌ To‘lov rad etildi'}).catch(()=>{})}
async function poll(){if(state.running||!ADMIN_BOT||!db)return;state.running=true;try{for(const u of await tg('getUpdates',{offset:state.offset,timeout:0,allowed_updates:['callback_query']})||[]){state.offset=Math.max(state.offset,Number(u.update_id||0)+1);if(u.callback_query)await callback(u.callback_query).catch(e=>console.error('[GULI admin callback]',e))}}finally{state.running=false}}
async function sync(){if(!db||!ADMIN_BOT)return;const ids=await admins();if(!ids.length)return;const r=await db.from('orders').select('*').order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;for(const o of r.data||[]){const sig=crypto.createHash('sha256').update(JSON.stringify({status:o.status,payment_status:o.payment_status,items:o.items,payment_receipt_history:o.payment_receipt_history,payment_receipt_path:o.payment_receipt_path,total:o.total})).digest('hex'),key=String(o.id),old=state.sigs.get(key);state.sigs.set(key,sig);if(!old){if(new Date(o.created_at||0)>=new Date(state.startedAt))for(const chat of ids)await sendOrEdit(chat,o,'🛒 YANGI BUYURTMA').catch(e=>console.error('[GULI admin new order]',e))}else if(old!==sig){const title=String(o.payment_status||'').toLowerCase()==='verified'?'💳 TO‘LOV TASDIQLANDI':String(o.payment_status||'').toLowerCase()==='rejected'?'💳 TO‘LOV RAD ETILDI':'📦 BUYURTMA YANGILANDI';for(const chat of ids)await sendOrEdit(chat,o,title).catch(e=>console.error('[GULI admin update]',e));await updateCustomer(o)}}}
if(!globalThis.__GULI_ADMIN_PROD_BOT_STARTED__){globalThis.__GULI_ADMIN_PROD_BOT_STARTED__=true;(async()=>{while(true){try{await poll();await sync()}catch(e){console.error('[GULI admin bot]',e)}await new Promise(r=>setTimeout(r,5000))}})()}
