// GULI production admin bot: one order = one Telegram media-group notification; every image is separate, with actions on the album.
const crypto=require('crypto');const {createClient}=require('@supabase/supabase-js');
const ADMIN_BOT=String(process.env.TELEGRAM_ADMIN_BOT_TOKEN||'').trim(),CUSTOMER_BOT=String(process.env.TELEGRAM_BOT_TOKEN||'').trim(),URL=String(process.env.SUPABASE_URL||'').trim(),KEY=String(process.env.SUPABASE_SECRET_KEY||'').trim();
const db=URL&&KEY?createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}}):null;
const state=globalThis.__GULI_ADMIN_PROD_BOT__||{running:false,offset:0,sigs:new Map(),startedAt:new Date().toISOString()};globalThis.__GULI_ADMIN_PROD_BOT__=state;
async function tg(method,body,token=ADMIN_BOT){if(!token)throw Error('Telegram bot token sozlanmagan');const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw Error(j?.description||`Telegram ${r.status}`);return j.result}
async function admins(){const s=new Set(String(process.env.TELEGRAM_ADMIN_CHAT_IDS||'').split(',').map(x=>x.trim()).filter(Boolean));if(db){const r=await db.from('telegram_admin_bot_chats').select('chat_id').eq('active',true);for(const x of r.data||[])s.add(String(x.chat_id))}return[...s]}
const money=v=>`${Math.round(Number(v||0)).toLocaleString('uz-UZ')} so‘m`;
function caption(o,title='🛒 YANGI BUYURTMA'){const items=Array.isArray(o.items)?o.items:[],lines=items.slice(0,15).map((x,i)=>{const p=x?.product||x?.product_data||x?.productDetails||x||{};return`${i+1}. ${p.name||p.title||x.name||'Mahsulot'}${p.product_code||x.product_code?` #${p.product_code||x.product_code}`:''} × ${Number(x.quantity||x.qty||1)} dona`});const ps=String(o.payment_status||'pending').toLowerCase();const pay=ps==='verified'?'✅ To‘lov tasdiqlangan':ps==='rejected'?'❌ Chek rad etilgan':ps==='receipt_uploaded'?'🧾 Chek yuklangan — tekshirish kutilmoqda':'⏳ To‘lov kutilmoqda';return[`<b>${title}</b>`,`🛒 <b>№:</b> <code>${o.order_number||o.id}</code>`,`👤 <b>Mijoz:</b> ${o.customer_name||[o.first_name,o.last_name].filter(Boolean).join(' ')||o.username||'Mijoz'}`,`📞 <b>Telefon:</b> ${o.phone||'—'}`,`💰 <b>Jami:</b> ${money(o.total)}`,`💳 <b>To‘lov:</b> ${o.payment||'—'}`,`🔎 <b>To‘lov holati:</b> ${pay}`,`📦 <b>Status:</b> ${o.status||'⏳ Buyurtma kutilmoqda'}`,'',`👗 <b>Mahsulotlar (${items.length} ta):</b>`,lines.join('\n')||'—','',`🧾 <b>Cheklar:</b> ${Array.isArray(o.payment_receipt_history)?o.payment_receipt_history.length:(o.payment_receipt_path?1:0)} ta`].join('\n').slice(0,1024)}
function keyboard(o){const ps=String(o.payment_status||'pending').toLowerCase();return o?.id&&['pending','receipt_uploaded'].includes(ps)?{inline_keyboard:[[{text:'✅ To‘lovni tasdiqlash',callback_data:`guli_pay:verified:${o.id}`},{text:'❌ Chekni rad etish',callback_data:`guli_pay:rejected:${o.id}`}]]}:{inline_keyboard:[]}}
function productImages(o){const out=[];for(const x of Array.isArray(o.items)?o.items:[]){const p=x?.product||x?.product_data||x?.productDetails||{};for(const u of [x.image,x.image_url,x.photo,p.image,p.image_url,...(Array.isArray(p.images)?p.images:[])])if(typeof u==='string'&&/^https?:\/\//i.test(u)&&!out.includes(u)){out.push(u);break}}return out}
async function signed(path){if(!db||!path)return'';try{return(await db.storage.from('payment-receipts').createSignedUrl(String(path).replace(/^\/+/,''),86400)).data?.signedUrl||''}catch{return''}}
async function receiptImages(o){const h=Array.isArray(o.payment_receipt_history)?o.payment_receipt_history:[],paths=h.map(x=>x?.path).filter(Boolean);if(o.payment_receipt_path&&!paths.includes(o.payment_receipt_path))paths.push(o.payment_receipt_path);const out=[];for(const p of paths){const u=await signed(p);if(u)out.push(u)}return out}
async function mediaUrls(o){return[...productImages(o),...(await receiptImages(o))].filter((u,i,a)=>u&&a.indexOf(u)===i).slice(0,10)}
async function existing(o,chat){if(!db)return null;const r=await db.from('telegram_admin_bot_order_messages').select('message_id,message_ids').eq('order_id',String(o.id)).eq('chat_id',Number(chat)).maybeSingle();if(!r.data)return null;return{mid:Number(r.data.message_id||0)||null,ids:Array.isArray(r.data.message_ids)?r.data.message_ids.map(Number).filter(Boolean):[]}}
async function save(o,chat,ids){const list=(Array.isArray(ids)?ids:[]).map(Number).filter(Boolean);const mid=list[0]||null;if(db&&mid)await db.from('telegram_admin_bot_order_messages').upsert({order_id:String(o.id),chat_id:Number(chat),message_id:mid,message_ids:list,updated_at:new Date().toISOString()},{onConflict:'order_id,chat_id'})}
async function sendAlbum(chat,o,title){const urls=await mediaUrls(o);if(!urls.length)return null;const cap=caption(o,title),items=urls.map((u,i)=>({type:'photo',media:u,...(i===0?{caption:cap,parse_mode:'HTML'}:{})}));try{const sent=await tg('sendMediaGroup',{chat_id:Number(chat),media:items,reply_markup:keyboard(o)});const ids=(sent||[]).map(x=>Number(x?.message_id||0)).filter(Boolean);if(ids.length)await save(o,chat,ids);return ids[0]||null}catch(e){console.warn('[GULI album]',e.message);return null}}
async function replaceAlbum(chat,o,title){const old=await existing(o,chat);if(old?.ids?.length){await tg('deleteMessages',{chat_id:Number(chat),message_ids:old.ids}).catch(async()=>{for(const id of old.ids)await tg('deleteMessage',{chat_id:Number(chat),message_id:id}).catch(()=>{})})}else if(old?.mid){await tg('deleteMessage',{chat_id:Number(chat),message_id:old.mid}).catch(()=>{})}return sendAlbum(chat,o,title)}
async function updateControl(chat,o,title){const old=await existing(o,chat);const ps=String(o.payment_status||'').toLowerCase();if(ps==='receipt_uploaded'&&!old?.ids?.length)return sendAlbum(chat,o,title);if(!old?.mid)return sendAlbum(chat,o,title);try{await tg('editMessageCaption',{chat_id:Number(chat),message_id:old.mid,caption:caption(o,title),parse_mode:'HTML',reply_markup:keyboard(o)});return old.mid}catch{try{await tg('editMessageReplyMarkup',{chat_id:Number(chat),message_id:old.mid,reply_markup:keyboard(o)});return old.mid}catch{return sendAlbum(chat,o,title)}}}
function customerBody(o){const items=Array.isArray(o.items)?o.items:[],lines=items.slice(0,15).map(x=>{const p=x?.product||x?.product_data||x||{};return`• ${p.name||p.title||x.name||'Mahsulot'} × ${Number(x.quantity||x.qty||1)} dona`}),ps=String(o.payment_status||'pending').toLowerCase(),pay=ps==='verified'?'✅ To‘lov tasdiqlandi':ps==='rejected'?'❌ Chek rad etildi':ps==='receipt_uploaded'?'🧾 Chek qabul qilindi — tekshirilmoqda':'⏳ To‘lov kutilmoqda';return[`🛍 <b>GULI Lingerie — BUYURTMA</b>`,`№ <b>${o.order_number||o.id}</b>`,``,`📦 <b>Buyurtma statusi:</b> <b>${o.status||'⏳ Buyurtma kutilmoqda'}</b>`,`💳 <b>To‘lov:</b> ${pay}`,'',`👗 <b>Mahsulotlar (${items.length} ta):</b>`,lines.join('\n')||'—','',`💰 <b>Jami:</b> ${money(o.total)}`].join('\n').slice(0,3900)}
async function ensureCustomerStatusMessage(o){if(!CUSTOMER_BOT||!db||!o?.telegram_id||o?.telegram_status_message_id)return Number(o?.telegram_status_message_id||0)||null;try{const sent=await tg('sendMessage',{chat_id:Number(o.telegram_id),text:customerBody(o),parse_mode:'HTML',disable_web_page_preview:true},CUSTOMER_BOT);const mid=Number(sent?.message_id||0)||null;if(mid){const r=await db.from('orders').update({telegram_status_message_id:mid}).eq('id',o.id).select('telegram_status_message_id').maybeSingle();return Number(r.data?.telegram_status_message_id||mid)||mid}}catch(e){console.warn('[GULI customer status create]',e.message)}return null}
async function updateCustomer(o){if(!CUSTOMER_BOT||!o?.telegram_id)return;let mid=Number(o.telegram_status_message_id||0)||null;if(!mid)mid=await ensureCustomerStatusMessage(o);if(!mid)return;try{await tg('editMessageText',{chat_id:Number(o.telegram_id),message_id:mid,text:customerBody(o),parse_mode:'HTML',disable_web_page_preview:true},CUSTOMER_BOT)}catch(e){if(!/message is not modified/i.test(e.message||''))console.warn('[GULI customer status edit]',e.message)}}
async function getOrder(id){if(!db)return null;let r=await db.from('orders').select('*').eq('id',id).maybeSingle();if(!r.data&&/GULI-/i.test(String(id)))r=await db.from('orders').select('*').eq('order_number',id).maybeSingle();return r.data||null}
async function callback(c){const chat=Number(c?.message?.chat?.id||0),from=Number(c?.from?.id||0),d=String(c?.data||'');if(!chat||chat!==from||!d.startsWith('guli_pay:'))return;const ids=await admins();if(!ids.includes(String(chat))){await tg('answerCallbackQuery',{callback_query_id:c.id,text:'⛔ Ruxsat yo‘q',show_alert:true}).catch(()=>{});return}const[,decision,id]=d.split(':');if(!['verified','rejected'].includes(decision)||!id)return;const o=await getOrder(id);if(!o)return;const ps=String(o.payment_status||'pending');if(!['pending','receipt_uploaded'].includes(ps)){await tg('answerCallbackQuery',{callback_query_id:c.id,text:'Bu to‘lov bo‘yicha qaror allaqachon qabul qilingan'}).catch(()=>{});return}const patch={payment_status:decision,status:decision==='verified'?'Qabul qilindi':'Bekor qilindi',updated_at:new Date().toISOString()};patch[decision==='verified'?'payment_verified_at':'payment_rejected_at']=new Date().toISOString();const r=await db.from('orders').update(patch).eq('id',o.id).select('*').single();if(r.error)throw r.error;await updateControl(chat,r.data,decision==='verified'?'💳 TO‘LOV TASDIQLANDI':'💳 TO‘LOV RAD ETILDI');await updateCustomer(r.data);await tg('answerCallbackQuery',{callback_query_id:c.id,text:decision==='verified'?'✅ To‘lov tasdiqlandi':'❌ To‘lov rad etildi'}).catch(()=>{})}
async function poll(){if(state.running||!ADMIN_BOT||!db)return;state.running=true;try{for(const u of await tg('getUpdates',{offset:state.offset,timeout:0,allowed_updates:['callback_query']})||[]){state.offset=Math.max(state.offset,Number(u.update_id||0)+1);if(u.callback_query)await callback(u.callback_query).catch(e=>console.error('[GULI admin callback]',e))}}finally{state.running=false}}
async function sync(){if(!db||!ADMIN_BOT)return;const ids=await admins();if(!ids.length)return;const r=await db.from('orders').select('*').order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;for(const o of r.data||[]){const sig=crypto.createHash('sha256').update(JSON.stringify({status:o.status,payment_status:o.payment_status,items:o.items,payment_receipt_history:o.payment_receipt_history,payment_receipt_path:o.payment_receipt_path,total:o.total})).digest('hex'),key=String(o.id),old=state.sigs.get(key);state.sigs.set(key,sig);if(!old){if(new Date(o.created_at||0)>=new Date(state.startedAt)){for(const chat of ids){await sendAlbum(chat,o,'🛒 YANGI BUYURTMA').catch(()=>{})}await ensureCustomerStatusMessage(o)}}else if(old!==sig){const ps=String(o.payment_status||'').toLowerCase();const title=ps==='verified'?'💳 TO‘LOV TASDIQLANDI':ps==='rejected'?'💳 TO‘LOV RAD ETILDI':ps==='receipt_uploaded'?'🧾 CHEK YUKLANDI — BUYURTMA YANGILANDI':'📦 BUYURTMA YANGILANDI';for(const chat of ids){if(ps==='receipt_uploaded')await replaceAlbum(chat,o,title).catch(()=>{});else await updateControl(chat,o,title).catch(()=>{})}await updateCustomer(o)}}}
if(!globalThis.__GULI_ADMIN_PROD_BOT_STARTED__){globalThis.__GULI_ADMIN_PROD_BOT_STARTED__=true;(async()=>{while(true){try{await poll();await sync()}catch(e){console.error('[GULI admin bot]',e)}await new Promise(r=>setTimeout(r,5000))}})()}
