// GULI production admin bot: one editable photo message per order.
const crypto=require('crypto');const sharp=require('sharp');const {createClient}=require('@supabase/supabase-js');
const BOT=String(process.env.TELEGRAM_ADMIN_BOT_TOKEN||'').trim(),CUSTOMER_TOKEN=String(process.env.TELEGRAM_BOT_TOKEN||'').trim(),URL=String(process.env.SUPABASE_URL||'').trim(),KEY=String(process.env.SUPABASE_SECRET_KEY||'').trim();
const db=URL&&KEY?createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}}):null;const state=globalThis.__GULI_ADMIN_PROD_BOT__||{running:false,offset:0,sigs:new Map(),startedAt:new Date().toISOString()};globalThis.__GULI_ADMIN_PROD_BOT__=state;if(!state.startedAt)state.startedAt=new Date().toISOString();
async function tg(method,body,token=BOT){if(!token)throw Error('Telegram bot token sozlanmagan');const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw Error(j?.description||`Telegram ${r.status}`);return j.result}
async function admins(){const s=new Set(String(process.env.TELEGRAM_ADMIN_CHAT_IDS||'').split(',').map(x=>x.trim()).filter(Boolean));if(db){const r=await db.from('telegram_admin_bot_chats').select('chat_id').eq('active',true);for(const x of r.data||[])s.add(String(x.chat_id))}return[...s]}
const money=v=>`${Math.round(Number(v||0)).toLocaleString('uz-UZ')} so‘m`;
function text(o,title='🛒 YANGI BUYURTMA'){const its=Array.isArray(o.items)?o.items:[];const lines=its.slice(0,15).map((x,i)=>{const p=x?.product||x?.product_data||x?.productDetails||x||{};const n=p.name||p.title||x.name||'Mahsulot',c=p.product_code||x.product_code||'',q=Number(x.quantity||x.qty||1);return`${i+1}. ${n}${c?` #${c}`:''} × ${q} dona`});const ps=String(o.payment_status||'pending').toLowerCase();const pay=ps==='verified'?'✅ To‘lov tasdiqlangan':ps==='rejected'?'❌ Chek rad etilgan':ps==='receipt_uploaded'?'🧾 Chek yuklangan — tekshirish kutilmoqda':'⏳ To‘lov kutilmoqda';return [`<b>${title}</b>`,`🛒 <b>№:</b> <code>${o.order_number||o.id}</code>`,`👤 <b>Mijoz:</b> ${o.customer_name||[o.first_name,o.last_name].filter(Boolean).join(' ')||o.username||'Mijoz'}`,`📞 <b>Telefon:</b> ${o.phone||'—'}`,`💰 <b>Jami:</b> ${money(o.total)}`,`💳 <b>To‘lov:</b> ${o.payment||'—'}`,`🔎 <b>To‘lov holati:</b> ${pay}`,`📦 <b>Status:</b> ${o.status||'⏳ Buyurtma kutilmoqda'}`,'',`👗 <b>Mahsulotlar (${its.length} ta):</b>`,lines.join('\n')||'—','',`🧾 <b>Cheklar:</b> ${Array.isArray(o.payment_receipt_history)?o.payment_receipt_history.length:(o.payment_receipt_path?1:0)} ta`].join('\n').slice(0,3900)}
function keyboard(o){const ps=String(o.payment_status||'pending').toLowerCase();if(!o.id||!['pending','receipt_uploaded'].includes(ps))return{inline_keyboard:[]};return{inline_keyboard:[[{text:'✅ To‘lovni tasdiqlash',callback_data:`guli_pay:verified:${o.id}`},{text:'❌ Chekni rad etish',callback_data:`guli_pay:rejected:${o.id}`}]]}}
function imageCandidates(o){const out=[];for(const x of Array.isArray(o.items)?o.items:[]){const p=x?.product||x?.product_data||x?.productDetails||{};for(const u of [x.image,x.image_url,x.photo,p.image,p.image_url,...(Array.isArray(p.images)?p.images:[])])if(typeof u==='string'&&/^https?:\/\//i.test(u)&&!out.includes(u)){out.push(u);break}}return out}
async function signed(path){if(!db||!path)return'';try{return(await db.storage.from('payment-receipts').createSignedUrl(String(path).replace(/^\/+/,''),86400)).data?.signedUrl||''}catch{return''}}
async function receiptUrls(o){const h=Array.isArray(o.payment_receipt_history)?o.payment_receipt_history:[];const paths=h.map(x=>x?.path).filter(Boolean);if(o.payment_receipt_path&&!paths.includes(o.payment_receipt_path))paths.push(o.payment_receipt_path);const urls=[];for(const p of paths){const u=await signed(p);if(u)urls.push(u)}return urls}
async function fetchImage(url){try{const r=await fetch(url);if(!r.ok)return null;const b=Buffer.from(await r.arrayBuffer());return await sharp(b).resize(420,420,{fit:'cover'}).jpeg({quality:86}).toBuffer()}catch{return null}}
async function collage(o){const urls=[...imageCandidates(o),...(await receiptUrls(o))].slice(0,10);const imgs=[];for(const u of urls){const b=await fetchImage(u);if(b)imgs.push(b)}if(!imgs.length)return null;const size=420,gap=8,w=Math.min(3,imgs.length)*size+(Math.min(3,imgs.length)-1)*gap,h=Math.ceil(imgs.length/3)*size+(Math.ceil(imgs.length/3)-1)*gap;const input=imgs.map((b,i)=>({input:b,left:(i%3)*(size+gap),top:Math.floor(i/3)*(size+gap)}));return sharp({create:{width:w,height:h,channels:3,background:'#ffffff'}}).composite(input).jpeg({quality:88}).toBuffer()}
async function saveMessage(orderId,chatId,messageId){if(!db)return;await db.from('telegram_admin_bot_order_messages').upsert({order_id:String(orderId),chat_id:Number(chatId),message_id:Number(messageId),updated_at:new Date().toISOString()},{onConflict:'order_id,chat_id'})}
async function existing(orderId,chatId){if(!db)return null;const r=await db.from('telegram_admin_bot_order_messages').select('message_id').eq('order_id',String(orderId)).eq('chat_id',Number(chatId)).maybeSingle();return r.data?.message_id?Number(r.data.message_id):null}
async function sendOrEdit(chatId,o,title='🛒 YANGI BUYURTMA'){const mid=await existing(o.id,chatId),buf=await collage(o),caption=text(o,title),markup=keyboard(o);if(mid&&buf){const form=new FormData();form.append('chat_id',String(chatId));form.append('message_id',String(mid));form.append('media',JSON.stringify({type:'photo',media:'attach://guli_order',caption,parse_mode:'HTML'}));form.append('reply_markup',JSON.stringify(markup));form.append('guli_order',new Blob([buf],{type:'image/jpeg'}),'guli_order.jpg');try{const r=await fetch(`https://api.telegram.org/bot${BOT}/editMessageMedia`,{method:'POST',body:form});if(r.ok){const j=await r.json().catch(()=>null);if(j?.ok)return mid}}catch{}}if(mid){try{await tg('editMessageCaption',{chat_id:chatId,message_id:mid,caption,parse_mode:'HTML',reply_markup:markup});return mid}catch{try{await tg('editMessageText',{chat_id:chatId,message_id:mid,text:caption,parse_mode:'HTML',reply_markup:markup});return mid}catch{}}}let sent;if(buf){const form=new FormData();form.append('chat_id',String(chatId));form.append('caption',caption);form.append('parse_mode','HTML');form.append('reply_markup',JSON.stringify(markup));form.append('photo',new Blob([buf],{type:'image/jpeg'}),'guli_order.jpg');const r=await fetch(`https://api.telegram.org/bot${BOT}/sendPhoto`,{method:'POST',body:form});const j=await r.json().catch(()=>null);if(j?.ok)sent=j.result}if(!sent)sent=await tg('sendMessage',{chat_id:chatId,text:caption,parse_mode:'HTML',reply_markup:markup});if(sent?.message_id)await saveMessage(o.id,chatId,sent.message_id);return sent?.message_id||null}
async function updateCustomerOrderMessage(order){if(!CUSTOMER_TOKEN||!order?.telegram_id||!order?.telegram_status_message_id)return;const chatId=Number(order.telegram_id),messageId=Number(order.telegram_status_message_id);if(!chatId||!messageId)return;const items=Array.isArray(order.items)?order.items:[];const lines=items.slice(0,15).map((x)=>{const p=x?.product||x?.product_data||x||{};const n=p?.name||p?.title||x?.name||'Mahsulot';const q=Number(x?.quantity||x?.qty||1);return`• ${n} × ${q} dona`});const status=String(order.status||'⏳ Buyurtma kutilmoqda');const pay=String(order.payment_status||'pending').toLowerCase();const payText=pay==='verified'?'✅ To‘lov tasdiqlandi':pay==='rejected'?'❌ Chek rad etildi':pay==='receipt_uploaded'?'🧾 Chek qabul qilindi — tekshirilmoqda':'⏳ To‘lov kutilmoqda';const body=[`🛍 <b>GULI Lingerie — BUYURTMA</b>`,`№ <b>${order.order_number||order.id}</b>`,``,`📦 <b>Buyurtma statusi:</b> <b>${status}</b>`,`💳 <b>To‘lov:</b> ${payText}`,'',`👗 <b>Mahsulotlar (${items.length} ta):</b>`,lines.join('\n')||'—','',`💰 <b>Jami:</b> ${money(order.total)}`].join('\n').slice(0,3900);try{await tg('editMessageText',{chat_id:chatId,message_id:messageId,text:body,parse_mode:'HTML',disable_web_page_preview:true})}catch(e){if(!/message is not modified/i.test(e.message||''))console.warn('[GULI customer status edit]',e.message)}}
async function getOrder(id){if(!db)return null;let r=await db.from('orders').select('*').eq('id',id).maybeSingle();if(!r.data&&/GULI-/i.test(String(id)))r=await db.from('orders').select('*').eq('order_number',id).maybeSingle();return r.data||null}
async function callback(c){const chat=Number(c?.message?.chat?.id||0),from=Number(c?.from?.id||0),d=String(c?.data||'');if(!chat||chat!==from||!d.startsWith('guli_pay:'))return;const ids=await admins();if(!ids.includes(String(chat))){await tg('answerCallbackQuery',{callback_query_id:c.id,text:'⛔ Ruxsat yo‘q',show_alert:true}).catch(()=>{});return}const[,decision,id]=d.split(':');if(!['verified','rejected'].includes(decision)||!id)return;const o=await getOrder(id);if(!o){await tg('answerCallbackQuery',{callback_query_id:c.id,text:'Buyurtma topilmadi',show_alert:true}).catch(()=>{});return}const ps=String(o.payment_status||'pending');if(!['pending','receipt_uploaded'].includes(ps)){await tg('answerCallbackQuery',{callback_query_id:c.id,text:'Bu to‘lov bo‘yicha qaror allaqachon qabul qilingan',show_alert:false}).catch(()=>{});return}const patch={payment_status:decision,updated_at:new Date().toISOString(),status:decision==='verified'?'Qabul qilindi':'Bekor qilindi'};if(decision==='verified')patch.payment_verified_at=new Date().toISOString();else patch.payment_rejected_at=new Date().toISOString();const r=await db.from('orders').update(patch).eq('id',o.id).select('*').single();if(r.error)throw r.error;await sendOrEdit(chat,r.data,decision==='verified'?'💳 TO‘LOV TASDIQLANDI':'💳 TO‘LOV RAD ETILDI');await updateCustomerOrderMessage(r.data);await tg('answerCallbackQuery',{callback_query_id:c.id,text:decision==='verified'?'✅ To‘lov tasdiqlandi':'❌ To‘lov rad etildi'}).catch(()=>{})}
async function poll(){if(state.running||!BOT||!db)return;state.running=true;try{const xs=await tg('getUpdates',{offset:state.offset,timeout:0,allowed_updates:['callback_query']});for(const u of xs||[]){state.offset=Math.max(state.offset,Number(u.update_id||0)+1);if(u.callback_query)await callback(u.callback_query).catch(e=>console.error('[GULI admin callback]',e))}}finally{state.running=false}}
async function sync(){if(!db||!BOT)return;const ids=await admins();if(!ids.length)return;const r=await db.from('orders').select('*').order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;for(const o of r.data||[]){const sig=crypto.createHash('sha256').update(JSON.stringify({status:o.status,payment_status:o.payment_status,items:o.items,payment_receipt_history:o.payment_receipt_history,payment_receipt_path:o.payment_receipt_path,total:o.total})).digest('hex');const key=String(o.id),old=state.sigs.get(key);state.sigs.set(key,sig);if(!old){if(new Date(o.created_at||0).getTime()>=new Date(state.startedAt).getTime()){for(const chat of ids){await sendOrEdit(chat,o,'🛒 YANGI BUYURTMA').catch(e=>console.error('[GULI admin new order]',e))}}}else if(old!==sig){for(const chat of ids){await sendOrEdit(chat,o,String(o.payment_status||'').toLowerCase()==='verified'?'💳 TO‘LOV TASDIQLANDI':String(o.payment_status||'').toLowerCase()==='rejected'?'💳 TO‘LOV RAD ETILDI':'📦 BUYURTMA YANGILANDI').catch(e=>console.error('[GULI admin update]',e))}await updateCustomerOrderMessage(o)}}}
if(!globalThis.__GULI_ADMIN_PROD_BOT_STARTED__){globalThis.__GULI_ADMIN_PROD_BOT_STARTED__=true;(async()=>{while(true){try{await poll();await sync()}catch(e){console.error('[GULI admin bot]',e)}await new Promise(r=>setTimeout(r,5000))}})()}
