// GULI ADMIN TELEGRAM BOT v2
// Product photos + every receipt are sent as a real Telegram album.
// Receipt updates never delete the previous admin message; a new album contains
// the full product set plus the complete receipt history, while the control
// message for the order is edited in place.
const { createClient } = require('@supabase/supabase-js');
const ADMIN_TOKEN=String(process.env.TELEGRAM_ADMIN_BOT_TOKEN||'').trim();
const CUSTOMER_TOKEN=String(process.env.TELEGRAM_BOT_TOKEN||'').trim();
const URL=String(process.env.SUPABASE_URL||'').trim();
const KEY=String(process.env.SUPABASE_SECRET_KEY||'').trim();
const db=URL&&KEY?createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}}):null;
const explicitIds=()=>String(process.env.TELEGRAM_ADMIN_CHAT_IDS||'').split(',').map(x=>x.trim()).filter(Boolean);
const state=globalThis.__GULI_ADMIN_BOT_V2__||{started:false,offset:0,signatures:new Map(),running:false};
globalThis.__GULI_ADMIN_BOT_V2__=state;
async function tg(method,body,token=ADMIN_TOKEN){if(!token)return null;const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw new Error(j?.description||`Telegram ${r.status}`);return j.result;}
async function adminIds(){const s=new Set(explicitIds());if(db){const{data}=await db.from('telegram_admin_bot_chats').select('chat_id').eq('active',true);for(const x of data||[])s.add(String(x.chat_id));}return[...s];}
const money=v=>`${Math.round(Number(v||0)).toLocaleString('uz-UZ')} so‘m`;
const name=o=>o?.customer_name||[o?.first_name,o?.last_name].filter(Boolean).join(' ')||o?.username||'Mijoz';
function payment(o){const p=String(o?.payment||'').toLowerCase();if(['card_manual','card_manual_transfer','uzcard_humo','card'].includes(p))return'💳 Karta (Uzcard / Humo)';if(p==='click')return'📲 Click';if(p==='payme')return'📱 Payme';return o?.payment||'—';}
function payStatus(o){const p=String(o?.payment_status||'pending').toLowerCase();return p==='verified'?'✅ Tasdiqlangan':p==='rejected'?'❌ Rad etilgan':p==='receipt_uploaded'?'🧾 Chek yangilandi — tekshiruv kutilmoqda':'⏳ Kutilmoqda';}
function productName(x){return x?.name||x?.title||x?.product_name||x?.product?.name||'Mahsulot';}
function lines(o){return(Array.isArray(o?.items)?o.items:[]).slice(0,20).map((x,i)=>`${i+1}. ${productName(x)} × ${Number(x?.quantity||x?.qty||1)}${x?.price!=null?` — ${money(x.price)}`:''}`);}
function text(o,title='🛒 YANGI ORDER'){const ls=lines(o);return(`${title}\n\n🛒 №: ${o?.order_number||o?.id||'—'}\n👤 Mijoz: ${name(o)}\n📞 Telefon: ${o?.phone||'—'}\n💰 Jami: ${money(o?.total)}\n💳 To‘lov: ${payment(o)}\n🔎 To‘lov holati: ${payStatus(o)}\n📦 Status: ${o?.status||'⏳ Buyurtma kutilmoqda'}\n📍 Manzil: ${typeof o?.address==='string'?o.address:'Buyurtmada mavjud'}${ls.length?`\n\n${ls.join('\n')}`:''}`).slice(0,4096);}
function keyboard(o){const p=String(o?.payment||'').toLowerCase(),s=String(o?.payment_status||'pending').toLowerCase();if(!['card_manual','card_manual_transfer','uzcard_humo','card'].includes(p)||!['pending','receipt_uploaded'].includes(s)||!o?.id)return{inline_keyboard:[]};return{inline_keyboard:[[{text:'✅ Tasdiqlash',callback_data:`guli_pay:verified:${o.id}`},{text:'❌ Rad etish',callback_data:`guli_pay:rejected:${o.id}`}]]};}
function imageUrl(x){const p=x?.product||x?.product_data||x?.productDetails||{};const a=[x?.image,x?.image_url,x?.photo,...(Array.isArray(x?.images)?x.images:[]),p?.image,p?.image_url,p?.photo,...(Array.isArray(p?.images)?p.images:[])];return a.map(v=>String(v||'').trim()).find(v=>/^https?:\/\//i.test(v))||'';}
async function signedReceipt(path){if(!path||!db)return'';const{data}=await db.storage.from('payment-receipts').createSignedUrl(String(path).replace(/^\/+/,''),3600);return data?.signedUrl||'';}
async function receiptHistory(orderId){if(!db)return[];const{data,error}=await db.from('payment_receipt_history').select('receipt_path,uploaded_at').eq('order_id',orderId).order('uploaded_at',{ascending:true});if(error)return[];return data||[];}
async function bytes(url){try{const r=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!r.ok)return null;const type=String(r.headers.get('content-type')||'').toLowerCase();if(!type.startsWith('image/'))return null;const b=Buffer.from(await r.arrayBuffer());return b.length?{b,type}:null;}catch{return null;}}
async function sendAlbum(chatId,o){const files=[];const seen=new Set();for(const item of Array.isArray(o?.items)?o.items:[]){const u=imageUrl(item);if(u&&!seen.has(u)){seen.add(u);files.push({url:u,label:'product'});}if(files.length>=8)break;}const history=await receiptHistory(o.id);for(const h of history){const u=await signedReceipt(h.receipt_path);if(u&&!seen.has(u)&&files.length<10){seen.add(u);files.push({url:u,label:'receipt'});}}if(!files.length)return null;const uploaded=[];for(const f of files){const b=await bytes(f.url);if(b)uploaded.push({...f,...b});}if(!uploaded.length)return null;const media=uploaded.map((f,i)=>({type:'photo',media:`attach://f${i}`,...(i===0?{caption:text(o,history.length?'🧾 CHEK / ORDER YANGILANDI':'🛒 YANGI ORDER')}:{} )}));const form=new FormData();form.append('chat_id',String(chatId));form.append('media',JSON.stringify(media));uploaded.forEach((f,i)=>form.append(`f${i}`,new Blob([f.b],{type:'image/jpeg'}),`guli-${i}.jpg`));const r=await fetch(`https://api.telegram.org/bot${ADMIN_TOKEN}/sendMediaGroup`,{method:'POST',body:form});const j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw new Error(j?.description||`Telegram ${r.status}`);return j.result||[];}
async function findControl(orderId,chatId){const{data}=await db.from('telegram_admin_bot_order_messages').select('message_id').eq('order_id',orderId).eq('chat_id',Number(chatId)).maybeSingle();return data?.message_id?Number(data.message_id):null;}
async function saveControl(orderId,chatId,messageId){if(!messageId)return;await db.from('telegram_admin_bot_order_messages').upsert({order_id:orderId,chat_id:Number(chatId),message_id:Number(messageId),updated_at:new Date().toISOString()},{onConflict:'order_id,chat_id'});}
async function editControl(chatId,messageId,o,title){try{return await tg('editMessageText',{chat_id:chatId,message_id:messageId,text:text(o,title),disable_web_page_preview:true,reply_markup:keyboard(o)});}catch(e){if(/message is not modified/i.test(e.message))return null;throw e;}}
async function createControl(chatId,o,title,replyTo){const sent=await tg('sendMessage',{chat_id:chatId,text:text(o,title),disable_web_page_preview:true,reply_markup:keyboard(o),...(replyTo?{reply_parameters:{message_id:Number(replyTo)}}:{})});await saveControl(o.id,chatId,sent?.message_id);return sent?.message_id||null;}
function sig(o){return JSON.stringify({status:o?.status||'',payment_status:o?.payment_status||'',receipt:o?.payment_receipt_path||''});}
function recent(o){const t=Date.parse(o?.created_at||'');return Number.isFinite(t)&&Date.now()-t<30*60*1000;}
async function callback(c){const chatId=Number(c?.message?.chat?.id||0),fromId=Number(c?.from?.id||0),data=String(c?.data||'');if(!chatId||chatId!==fromId||!data.startsWith('guli_pay:'))return;const ids=await adminIds();if(!ids.includes(String(chatId))){await tg('answerCallbackQuery',{callback_query_id:c.id,text:'⛔ Ruxsat yo‘q',show_alert:true}).catch(()=>{});return;}const[,decision,orderId]=data.split(':');if(!orderId||!['verified','rejected'].includes(decision))return;try{const{data:o0,error:e0}=await db.from('orders').select('*').eq('id',orderId).maybeSingle();if(e0||!o0)throw new Error('Buyurtma topilmadi');const ps=String(o0.payment_status||'pending').toLowerCase();if(!['pending','receipt_uploaded'].includes(ps)){await tg('answerCallbackQuery',{callback_query_id:c.id,text:'To‘lov bo‘yicha qaror allaqachon qabul qilingan'});return;}const{error:e1}=await db.rpc('admin_payment_decision',{p_order_id:orderId,p_payment_status:decision});if(e1)throw e1;const{data:o,error:e2}=await db.from('orders').select('*').eq('id',orderId).single();if(e2)throw e2;await saveControl(o.id,chatId,c.message.message_id);await editControl(chatId,c.message.message_id,o,decision==='verified'?'💳 TO‘LOV TASDIQLANDI':'💳 TO‘LOV RAD ETILDI');await tg('answerCallbackQuery',{callback_query_id:c.id,text:decision==='verified'?'✅ To‘lov tasdiqlandi':'❌ To‘lov rad etildi'});if(CUSTOMER_TOKEN&&o.telegram_id){await tg('sendMessage',{chat_id:Number(o.telegram_id),text:decision==='verified'?`✅ To‘lov tasdiqlandi!\n\nBuyurtma № ${o.order_number}\nSumma: ${money(o.total)}\n\nBuyurtma holati: ${o.status||'Qabul qilindi'}`:`⚠️ To‘lov cheki rad etildi.\n\nBuyurtma № ${o.order_number}\nIltimos, to‘lov chekini qayta yuboring.`},CUSTOMER_TOKEN).catch(()=>{});}}catch(e){await tg('answerCallbackQuery',{callback_query_id:c.id,text:`Xatolik: ${String(e.message||'').slice(0,160)}`,show_alert:true}).catch(()=>{});}}
async function updates(){const xs=await tg('getUpdates',{offset:state.offset,timeout:0,allowed_updates:['message','callback_query']});for(const u of xs||[]){state.offset=Math.max(state.offset,Number(u.update_id||0)+1);if(u.callback_query){await callback(u.callback_query);continue;}const m=u.message,ch=m?.chat;if(ch?.type!=='private'||!ch?.id||!/^\/start(?:@\w+)?(?:\s|$)/i.test(String(m.text||'').trim()))continue;await db.from('telegram_admin_bot_chats').upsert({chat_id:Number(ch.id),username:ch.username||null,first_name:ch.first_name||null,last_name:ch.last_name||null,active:true,updated_at:new Date().toISOString()},{onConflict:'chat_id'});await tg('sendMessage',{chat_id:ch.id,text:`👤 GULI ADMIN MA‘LUMOTI\n\nTelegram ID: ${ch.id}\nChat ID: ${ch.id}\nHolat: ✅ Admin botga ulangan`});}}
async function orders(){const ids=await adminIds();if(!ids.length)return;const{data,error}=await db.from('orders').select('*').order('created_at',{ascending:false}).limit(100);if(error)throw error;for(const o of data||[]){const id=String(o.id),s=sig(o),prev=state.signatures.get(id);state.signatures.set(id,s);for(const chatId of ids){let mid=await findControl(o.id,chatId);if(!mid){if(recent(o)){const album=await sendAlbum(chatId,o);mid=await createControl(chatId,o,String(o.payment_status||'').toLowerCase()==='receipt_uploaded'?'🧾 CHEK YUKLANDI':'🛒 YANGI ORDER',album?.[0]?.message_id);}continue;}if(prev!==undefined&&prev!==s){let oldReceipt='';try{oldReceipt=JSON.parse(prev).receipt||'';}catch{}const receiptChanged=oldReceipt!==String(o.payment_receipt_path||'');if(receiptChanged){const album=await sendAlbum(chatId,o);if(album?.[0]?.message_id)await tg('sendMessage',{chat_id:chatId,text:`🧾 Yangi chek qo‘shildi\n\n№ ${o.order_number}\n${payStatus(o)}\nEski cheklar saqlandi, yangi chek ham albomga qo‘shildi.`,disable_web_page_preview:true,reply_parameters:{message_id:Number(album[0].message_id)}}).catch(()=>{});}const p=String(o.payment_status||'').toLowerCase();const title=p==='verified'?'💳 TO‘LOV TASDIQLANDI':p==='rejected'?'💳 TO‘LOV RAD ETILDI':receiptChanged?'🧾 CHEK YANGILANDI':'📦 ORDER STATUS O‘ZGARDI';await editControl(chatId,mid,o,title);}}}}
async function loop(){if(state.running)return;state.running=true;try{await updates().catch(()=>{});await orders().catch(e=>console.warn('[Admin bot v2]',e.message));}finally{state.running=false;}}
if(ADMIN_TOKEN&&db&&!state.started){state.started=true;setTimeout(()=>void loop(),1200);setInterval(()=>void loop(),3000);console.log('[GULI Admin bot] v2 album + receipt-history bridge enabled.');}
