import { FormEvent, useEffect, useMemo, useState } from "react";
import ProductModalV2 from "./ProductModalV2";
import "./AdminPro.css";

type Product={id?:number;product_code?:string;name:string;category:string;description:string;price:number;old_price?:number|null;image:string;images:string[];sizes:string[];colors:string[];rating:number;reviews:number;stock:number;featured:boolean;active?:boolean;sort_order?:number};
type Order={id:string|number;order_number?:string;telegram_id?:number;username?:string;first_name?:string;phone?:string;total:number;subtotal:number;delivery:number;discount:number;payment:string;status:string;address?:any;items:any[];created_at:string};
type User={telegram_id:number;username?:string;first_name?:string;last_name?:string;telegram_phone?:string;updated_at?:string};
type Promo={id?:number;code:string;discount_type:"percent"|"fixed";discount_value:number;min_order_amount:number;usage_limit:number|null;used_count:number;active:boolean};
const API=(import.meta.env.VITE_API_URL||"https://guli-lingerie-api.onrender.com").replace(/\/$/,"");
const STATUSES=["Qabul qilindi","Tayyorlanmoqda","Yo‘lda","Yetkazildi","Bekor qilindi"];
const emptyProduct:Product={product_code:"",name:"",category:"Byustgalter",description:"",price:0,old_price:null,image:"",images:[],sizes:[],colors:[],rating:0,reviews:0,stock:0,featured:false,active:true,sort_order:0};
const emptyPromo:Promo={code:"",discount_type:"percent",discount_value:10,min_order_amount:0,usage_limit:null,used_count:0,active:true};
const money=(n:number)=>`${Math.round(Number(n)||0).toLocaleString("uz-UZ")} so'm`;
const date=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString("uz-UZ",{dateStyle:"medium",timeStyle:"short"})};
const csv=(rows:any[])=>rows.map(r=>r.map((x:any)=>`"${String(x??"").replace(/"/g,'""')}"`).join(",")).join("\n");
function download(name:string,text:string){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+text],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}

export default function AdminPro(){
 const [token,setToken]=useState(()=>sessionStorage.getItem("guli_admin_token")||"");const [login,setLogin]=useState("");const [password,setPassword]=useState("");const [loginError,setLoginError]=useState("");const [busy,setBusy]=useState(false);const [tab,setTab]=useState("dashboard");const [dashboard,setDashboard]=useState<any>(null);const [products,setProducts]=useState<Product[]>([]);const [orders,setOrders]=useState<Order[]>([]);const [users,setUsers]=useState<User[]>([]);const [promos,setPromos]=useState<Promo[]>([]);const [query,setQuery]=useState("");const [statusFilter,setStatusFilter]=useState("all");const [selectedOrder,setSelectedOrder]=useState<Order|null>(null);const [selectedUser,setSelectedUser]=useState<User|null>(null);const [product,setProduct]=useState<Product>(emptyProduct);const [promo,setPromo]=useState<Promo>(emptyPromo);const [productOpen,setProductOpen]=useState(false);const [promoOpen,setPromoOpen]=useState(false);const [toast,setToast]=useState("");
 const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),2600)};const logout=()=>{sessionStorage.removeItem("guli_admin_token");setToken("")};
 const request=async(path:string,options:RequestInit={})=>{const r=await fetch(`${API}${path}`,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...(options.headers||{})}});if(r.status===401){logout();throw Error("Admin sessiyasi tugagan")};const j=await r.json();if(!r.ok||j.success===false)throw Error(j.message||"Server xatosi");return j};
 const load=async()=>{if(!token)return;setBusy(true);try{const [d,p,o,u,pr]=await Promise.all([request("/api/admin/dashboard"),request("/api/admin/products?limit=500"),request("/api/admin/orders?limit=500"),request("/api/admin/users?limit=500"),request("/api/admin/promos?limit=500")]);setDashboard(d.data);setProducts(p.data||[]);setOrders(o.data||[]);setUsers(u.data||[]);setPromos(pr.data||[])}catch(e){notify(e instanceof Error?e.message:"Yuklashda xatolik")}finally{setBusy(false)}};
 useEffect(()=>{if(token)load()},[token]);
 const doLogin=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setLoginError("");try{const r=await fetch(`${API}/api/admin/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:login,password})});const j=await r.json();if(!r.ok||!j.success)throw Error(j.message||"Kirish rad etildi");sessionStorage.setItem("guli_admin_token",j.token);setToken(j.token)}catch(e){setLoginError(e instanceof Error?e.message:"Kirishda xatolik")}finally{setBusy(false)}};
 const productsFiltered=useMemo(()=>products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase())),[products,query]);
 const ordersFiltered=useMemo(()=>orders.filter(o=>(statusFilter==="all"||o.status===statusFilter)&&`${o.order_number||o.id} ${o.first_name||""} ${o.username||""} ${o.phone||""}`.toLowerCase().includes(query.toLowerCase())),[orders,statusFilter,query]);
 const usersFiltered=useMemo(()=>users.filter(u=>`${u.telegram_id} ${u.username||""} ${u.first_name||""} ${u.last_name||""} ${u.telegram_phone||""}`.toLowerCase().includes(query.toLowerCase())),[users,query]);
 const uploadImage=async(file:File)=>{
  if(!file.type.startsWith("image/")) throw Error("Faqat rasm fayli tanlang");
  setBusy(true);
  try{
    const bitmap=await createImageBitmap(file);
    const max=1600;
    const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));
    const canvas=document.createElement("canvas");
    canvas.width=Math.max(1,Math.round(bitmap.width*scale));
    canvas.height=Math.max(1,Math.round(bitmap.height*scale));
    const ctx=canvas.getContext("2d");
    if(!ctx) throw Error("Rasm tayyorlashda xatolik");
    ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);
    bitmap.close();
    const dataUrl=canvas.toDataURL("image/webp",0.82);
    const data=dataUrl.split(",")[1];
    const r=await request("/api/admin/upload-image",{method:"POST",body:JSON.stringify({data,mimeType:"image/webp",extension:"webp"})});
    notify("Rasm yuklandi ✓");
    return r.data.url as string;
  }catch(e){notify(e instanceof Error?e.message:"Rasmni yuklashda xatolik");throw e}finally{setBusy(false)}
 };
 const saveProduct=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const payload={...product,price:Number(product.price),old_price:product.old_price?Number(product.old_price):null,stock:Number(product.stock),rating:Number(product.rating),reviews:Number(product.reviews),sort_order:Number(product.sort_order||0)||(!product.id?Math.max(0,...products.map(p=>Number(p.sort_order)||0))+1:0)};const r=product.id?await request(`/api/admin/products/${product.id}`,{method:"PUT",body:JSON.stringify(payload)}):await request("/api/admin/products",{method:"POST",body:JSON.stringify(payload)});setProducts(x=>product.id?x.map(p=>p.id===product.id?r.data:p):[r.data,...x]);setProductOpen(false);notify("Mahsulot saqlandi ✓")}catch(e){notify(e instanceof Error?e.message:"Saqlashda xatolik")}finally{setBusy(false)}};
 const savePromo=async(e:FormEvent)=>{e.preventDefault();try{const payload={...promo,code:promo.code.trim().toUpperCase(),discount_value:Number(promo.discount_value),min_order_amount:Number(promo.min_order_amount),usage_limit:promo.usage_limit==null?null:Number(promo.usage_limit)};const r=promo.id?await request(`/api/admin/promos/${promo.id}`,{method:"PUT",body:JSON.stringify(payload)}):await request("/api/admin/promos",{method:"POST",body:JSON.stringify(payload)});setPromos(x=>promo.id?x.map(p=>p.id===promo.id?r.data:p):[r.data,...x]);setPromoOpen(false);notify("Promo saqlandi ✓")}catch(e){notify(e instanceof Error?e.message:"Promo xatosi")}};
 const updateStatus=async(o:Order,status:string)=>{try{const r=await request(`/api/admin/orders/${o.id}`,{method:"PUT",body:JSON.stringify({status})});setOrders(x=>x.map(v=>v.id===o.id?r.data:v));setSelectedOrder(r.data);notify("Status yangilandi ✓")}catch(e){notify(e instanceof Error?e.message:"Status xatosi")}};
 const hideProduct=async(p:Product)=>{try{const r=await request(`/api/admin/products/${p.id}`,{method:"DELETE"});setProducts(x=>x.map(v=>v.id===p.id?r.data:v));notify("Mahsulot yashirildi")}catch(e){notify(e instanceof Error?e.message:"Xatolik")}};
 if(!token)return <div className="proLogin"><div className="loginAura"/><form className="proLoginCard" onSubmit={doLogin}><div className="proLogo">🌷</div><span className="proEyebrow">GULI PREMIUM</span><h1>Control Center</h1><p>Do‘konni bitta professional paneldan boshqaring.</p><label>Login<input value={login} onChange={e=>setLogin(e.target.value)} autoComplete="username" required/></label><label>Parol<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{loginError&&<div className="proError">{loginError}</div>}<button className="proPrimary" disabled={busy}>{busy?"Tekshirilmoqda…":"Kirish →"}</button><small>Admin tokeni faqat sessionStorage’da saqlanadi.</small></form></div>;
 const nav=[ ["dashboard","⌂","Boshqaruv"],["products","◈","Mahsulotlar"],["orders","▣","Buyurtmalar"],["customers","♙","Mijozlar"],["promos","%","Promo"] ];
 const revenue=Number(dashboard?.todayRevenue||0);const title=nav.find(n=>n[0]===tab)?.[2]||"Boshqaruv";
 return <div className="proShell"><aside className="proSide"><div className="proBrand"><span>🌷</span><div><b>GULI</b><small>PREMIUM ADMIN</small></div></div><div className="sideNav">{nav.map(n=><button key={n[0]} className={tab===n[0]?"active":""} onClick={()=>{setTab(n[0]);setQuery("")}}><i>{n[1]}</i>{n[2]}</button>)}</div><div className="sideBottom"><span className="online"><b/> Online</span><button onClick={logout}>↪ Chiqish</button></div></aside>
 <main className="proMain"><header className="proTop"><div><span className="proEyebrow">GULI PREMIUM CONTROL</span><h1>{title}</h1></div><div className="topActions"><span className="dateNow">Bugun</span><button onClick={load} disabled={busy}>↻ Yangilash</button></div></header>
 {tab!=="dashboard"&&<div className="proToolbar"><div className="proSearch">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tab==="products"?"Mahsulot, kategoriya...":tab==="orders"?"№, mijoz, telefon...":"Qidirish..."}/></div>{tab==="products"&&<button className="proPrimary" onClick={()=>{setProduct({...emptyProduct});setProductOpen(true)}}>+ Mahsulot</button>}{tab==="promos"&&<button className="proPrimary" onClick={()=>{setPromo({...emptyPromo});setPromoOpen(true)}}>+ Promo kod</button>}</div>}
 {tab==="dashboard"&&<section className="dash"><div className="metricGrid"><Metric label="Bugungi savdo" value={money(revenue)} icon="₿" tone="rose"/><Metric label="Buyurtmalar" value={dashboard?.ordersCount||0} icon="▣"/><Metric label="Mijozlar" value={dashboard?.usersCount||0} icon="♙"/><Metric label="Faol mahsulotlar" value={dashboard?.productsCount||0} icon="◈"/></div><div className="dashGrid"><section className="proPanel"><PanelHead eyebrow="OPERATSION" title="Buyurtma holatlari" action={()=>setTab("orders")}/><div className="statusBoard">{STATUSES.slice(0,4).map(s=><div key={s}><b>{dashboard?.statusCounts?.[s]||0}</b><span>{s}</span><em style={{width:`${Math.min(100,Number(dashboard?.statusCounts?.[s]||0)*10)}%`}}/></div>)}</div></section><section className="proPanel"><PanelHead eyebrow="OMBOR" title="Kam qolganlar" action={()=>setTab("products")}/>{(dashboard?.lowStock||[]).length?<div className="lowList">{dashboard.lowStock.slice(0,6).map((p:Product)=><div key={p.id}><span>{p.name}</span><b>{p.stock} dona</b></div>)}</div>:<div className="proEmpty">✓ Ombor barqaror</div>}</section></div><section className="proPanel"><div className="panelHead"><div><span className="proEyebrow">LIVE</span><h2>So‘nggi buyurtmalar</h2></div><button onClick={()=>setTab("orders")}>Barchasi →</button></div><OrderTable rows={(dashboard?.recentOrders||[]).slice(0,8)} onOpen={o=>setSelectedOrder(o)}/></section></section>}
 {tab==="products"&&<section className="proPanel tablePanel"><div className="panelHead"><div><span className="proEyebrow">CATALOG</span><h2>{productsFiltered.length} ta mahsulot</h2></div><button onClick={()=>download("guli-products.csv",csv([["ID","Nom","Kategoriya","Narx","Ombor","Holat"],...productsFiltered.map(p=>[p.id,p.name,p.category,p.price,p.stock,p.active===false?"Yashirin":"Faol"]) ]))}>↓ CSV</button></div><div className="tableScroll"><table><thead><tr><th>Mahsulot</th><th>Kategoriya</th><th>Narx</th><th>Ombor</th><th>Holat</th><th/></tr></thead><tbody>{productsFiltered.map(p=><tr key={p.id}><td><div className="entityCell"><img src={p.image||"https://placehold.co/72x72/f6e8eb/b95a70?text=G"}/><div><b>{p.name}</b><small>ID {p.id}</small></div></div></td><td>{p.category}</td><td><b>{money(p.price)}</b>{p.old_price&&<del>{money(p.old_price)}</del>}</td><td><span className={p.stock<5?"stock dangerStock":"stock"}>{p.stock}</span></td><td><span className={`pill ${p.active===false?"mutedPill":""}`}>{p.active===false?"Yashirin":p.featured?"Tanlangan":"Faol"}</span></td><td><div className="actions"><button onClick={()=>{setProduct({...p,images:p.images||[],sizes:p.sizes||[],colors:p.colors||[]});setProductOpen(true)}}>Tahrirlash</button>{p.active!==false&&<button className="dangerBtn" onClick={()=>hideProduct(p)}>Yashirish</button>}</div></td></tr>)}</tbody></table></div></section>}
 {tab==="orders"&&<section className="proPanel tablePanel"><div className="filterRow">{["all",...STATUSES].map(s=><button key={s} className={statusFilter===s?"active":""} onClick={()=>setStatusFilter(s)}>{s==="all"?"Barchasi":s}</button>)}</div><div className="panelHead"><div><span className="proEyebrow">ORDERS</span><h2>{ordersFiltered.length} ta buyurtma</h2></div><button onClick={()=>download("guli-orders.csv",csv([["Buyurtma","Mijoz","Telefon","Jami","To‘lov","Status","Sana"],...ordersFiltered.map(o=>[o.order_number||o.id,o.first_name||o.username||"",o.phone||"",o.total,o.payment,o.status,o.created_at])]))}>↓ CSV</button></div><div className="tableScroll"><table><thead><tr><th>№</th><th>Mijoz</th><th>Mahsulot</th><th>Jami</th><th>To‘lov</th><th>Status</th><th>Sana</th></tr></thead><tbody>{ordersFiltered.map(o=><tr key={o.id} onClick={()=>setSelectedOrder(o)} className="clickable"><td><b>{o.order_number||o.id}</b></td><td><b>{o.first_name||"Mijoz"}</b><small>{o.username?`@${o.username}`:o.phone||""}</small></td><td>{o.items?.[0]?.product?.name||"Buyurtma"}{o.items?.length>1?` +${o.items.length-1}`:""}</td><td><b>{money(o.total)}</b></td><td>{o.payment==="card"?"Karta":"Naqd"}</td><td><span className="pill">{o.status}</span></td><td>{date(o.created_at)}</td></tr>)}</tbody></table></div></section>}
 {tab==="customers"&&<section className="proPanel tablePanel"><div className="panelHead"><div><span className="proEyebrow">CRM</span><h2>{usersFiltered.length} ta mijoz</h2></div><button onClick={()=>download("guli-customers.csv",csv([["Telegram ID","Ism","Username","Telefon","Yangilangan"],...usersFiltered.map(u=>[u.telegram_id,[u.first_name,u.last_name].filter(Boolean).join(" "),u.username?`@${u.username}`:"",u.telegram_phone||"",u.updated_at||""]) ]))}>↓ CSV</button></div><div className="tableScroll"><table><thead><tr><th>Mijoz</th><th>Telegram ID</th><th>Username</th><th>Telefon</th><th>Yangilangan</th></tr></thead><tbody>{usersFiltered.map(u=><tr key={u.telegram_id} className="clickable" onClick={()=>setSelectedUser(u)}><td><div className="avatarMini">{(u.first_name||"G").slice(0,1).toUpperCase()}</div><b>{[u.first_name,u.last_name].filter(Boolean).join(" ")||"Noma’lum"}</b></td><td>{u.telegram_id}</td><td>{u.username?`@${u.username}`:"—"}</td><td>{u.telegram_phone||"—"}</td><td>{u.updated_at?date(u.updated_at):"—"}</td></tr>)}</tbody></table></div></section>}
 {tab==="promos"&&<section className="proPanel tablePanel"><div className="panelHead"><div><span className="proEyebrow">MARKETING</span><h2>{promos.length} ta promo</h2></div></div><div className="tableScroll"><table><thead><tr><th>Kod</th><th>Chegirma</th><th>Min.</th><th>Foydalanish</th><th>Holat</th><th/></tr></thead><tbody>{promos.filter(p=>p.code.toLowerCase().includes(query.toLowerCase())).map(p=><tr key={p.id}><td><b className="promoCode">{p.code}</b></td><td>{p.discount_type==="percent"?`${p.discount_value}%`:money(p.discount_value)}</td><td>{money(p.min_order_amount)}</td><td>{p.used_count}{p.usage_limit?` / ${p.usage_limit}`:" / ∞"}</td><td><span className={`pill ${p.active?"":"mutedPill"}`}>{p.active?"Faol":"O‘chiq"}</span></td><td><button onClick={()=>{setPromo({...p});setPromoOpen(true)}}>Tahrirlash</button></td></tr>)}</tbody></table></div></section>}
 </main><nav className="proMobileNav">{nav.map(n=><button key={n[0]} className={tab===n[0]?"active":""} onClick={()=>setTab(n[0])}><span>{n[1]}</span>{n[2]}</button>)}</nav>
 {selectedOrder&&<OrderDrawer order={selectedOrder} onClose={()=>setSelectedOrder(null)} onStatus={updateStatus}/>} {selectedUser&&<UserDrawer user={selectedUser} orders={orders} onClose={()=>setSelectedUser(null)} onOrder={setSelectedOrder}/>} {productOpen&&<ProductModalV2 value={product} busy={busy} onClose={()=>setProductOpen(false)} onChange={setProduct} onSave={saveProduct} onUpload={uploadImage}/>} {promoOpen&&<PromoModal value={promo} onClose={()=>setPromoOpen(false)} onChange={setPromo} onSave={savePromo}/>} {toast&&<div className="proToast">{toast}</div>}{busy&&<div className="proBusy"/>}</div>
}
function Metric({label,value,icon,tone=""}:{label:string;value:any;icon:string;tone?:string}){return <div className={`metric ${tone}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}
function PanelHead({eyebrow,title,action}:{eyebrow:string;title:string;action?:()=>void}){return <div className="panelHead"><div><span className="proEyebrow">{eyebrow}</span><h2>{title}</h2></div>{action&&<button onClick={action}>Ko‘rish →</button>}</div>}
function OrderTable({rows,onOpen}:{rows:any[];onOpen:(o:any)=>void}){return <div className="tableScroll"><table><thead><tr><th>Buyurtma</th><th>Mijoz</th><th>Summa</th><th>Status</th><th>Sana</th></tr></thead><tbody>{rows.map(o=><tr key={o.id} className="clickable" onClick={()=>onOpen(o)}><td><b>{o.order_number||o.id}</b></td><td>{o.first_name||o.username||"Mijoz"}</td><td><b>{money(o.total)}</b></td><td><span className="pill">{o.status}</span></td><td>{date(o.created_at)}</td></tr>)}</tbody></table></div>}
function OrderDrawer({order,onClose,onStatus}:{order:Order;onClose:()=>void;onStatus:(o:Order,s:string)=>void}){const addr=order.address||{};return <div className="drawerShade" onMouseDown={onClose}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawerHead"><div><span className="proEyebrow">BUYURTMA</span><h2>№ {order.order_number||order.id}</h2><small>{date(order.created_at)}</small></div><button onClick={onClose}>×</button></div><div className="drawerBody"><section className="detailHero"><span className="orderIcon">▣</span><div><b>{order.first_name||"Mijoz"}</b><small>{order.username?`@${order.username}`:"Telegram mijozi"}</small></div></section><div className="detailGrid"><div><small>Telefon</small><b>{order.phone||"—"}</b></div><div><small>To‘lov</small><b>{order.payment==="card"?"Karta":"Naqd"}</b></div><div><small>Mahsulotlar</small><b>{money(order.subtotal)}</b></div><div><small>Yetkazib berish</small><b>{order.delivery?money(order.delivery):"Bepul"}</b></div><div><small>Chegirma</small><b>{order.discount?`−${money(order.discount)}`:"—"}</b></div><div><small>Jami</small><b>{money(order.total)}</b></div></div><div className="detailSection"><h3>Status</h3><select value={order.status} onChange={e=>onStatus(order,e.target.value)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><div className="timeline">{STATUSES.slice(0,4).map((s,i)=>{const current=STATUSES.indexOf(order.status);return <div className={i<=current?"done":""} key={s}><span>{i<current?"✓":i+1}</span><b>{s}</b></div>})}</div></div><div className="detailSection"><h3>Mahsulotlar</h3>{(order.items||[]).map((it:any,i:number)=><div className="lineItem" key={i}>{it.product?.image&&<img src={it.product.image} alt=""/>}<div><b>{it.product?.name||"Mahsulot"}</b><small>{it.size||"—"} · {it.color||"—"} · {it.quantity||1} dona</small></div><strong>{money(Number(it.product?.price||0)*Number(it.quantity||1))}</strong></div>)}</div><div className="detailSection"><h3>Yetkazib berish manzili</h3><p className="addressText">📍 {[addr.region,addr.district,addr.street,addr.house,addr.apartment].filter(Boolean).join(", ")||"Manzil ko‘rsatilmagan"}</p>{addr.landmark&&<small>Mo‘ljal: {addr.landmark}</small>}</div></div></aside></div>}
function UserDrawer({user,orders,onClose,onOrder}:{user:User;orders:Order[];onClose:()=>void;onOrder:(o:Order)=>void}){const mine=orders.filter(o=>o.telegram_id===user.telegram_id||(user.username&&o.username===user.username));const spend=mine.reduce((s,o)=>s+Number(o.total||0),0);return <div className="drawerShade" onMouseDown={onClose}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawerHead"><div><span className="proEyebrow">CRM MIJOZ</span><h2>{[user.first_name,user.last_name].filter(Boolean).join(" ")||"Noma’lum"}</h2><small>{user.username?`@${user.username}`:"Telegram foydalanuvchisi"}</small></div><button onClick={onClose}>×</button></div><div className="drawerBody"><section className="detailHero"><div className="avatarLarge">{(user.first_name||"G").slice(0,1)}</div><div><b>{user.telegram_phone||"Telefon saqlanmagan"}</b><small>ID: {user.telegram_id}</small></div></section><div className="detailGrid"><div><small>Buyurtmalar</small><b>{mine.length}</b></div><div><small>Jami xarid</small><b>{money(spend)}</b></div></div><div className="detailSection"><h3>Buyurtmalar tarixi</h3>{mine.length?mine.map(o=><button className="customerOrder" key={o.id} onClick={()=>onOrder(o)}><span>{o.order_number||o.id}</span><b>{money(o.total)}</b><small>{o.status}</small></button>):<p>Bu mijozda buyurtmalar topilmadi.</p>}</div></div></aside></div>}
function PromoModal({value,onClose,onChange,onSave}:{value:Promo;onClose:()=>void;onChange:(v:Promo)=>void;onSave:(e:FormEvent)=>void}){const set=(k:keyof Promo,v:any)=>onChange({...value,[k]:v});return <Modal title={value.id?"Promo tahrirlash":"Yangi promo"} eyebrow="MARKETING" onClose={onClose}><form onSubmit={onSave}><div className="formGrid"><label>Kod<input value={value.code} onChange={e=>set("code",e.target.value.toUpperCase())} required/></label><label>Tur<select value={value.discount_type} onChange={e=>set("discount_type",e.target.value)}><option value="percent">Foiz</option><option value="fixed">Summa</option></select></label><label>Qiymat<input type="number" min="0.01" max={value.discount_type==="percent"?100:undefined} value={value.discount_value} onChange={e=>set("discount_value",Number(e.target.value))}/></label><label>Minimal buyurtma<input type="number" min="0" value={value.min_order_amount} onChange={e=>set("min_order_amount",Number(e.target.value))}/></label><label>Limit<input type="number" min="1" value={value.usage_limit??""} onChange={e=>set("usage_limit",e.target.value?Number(e.target.value):null)}/></label><label>Holat<select value={value.active?"active":"off"} onChange={e=>set("active",e.target.value==="active")}><option value="active">Faol</option><option value="off">O‘chiq</option></select></label></div><div className="modalActions"><button type="button" onClick={onClose}>Bekor qilish</button><button className="proPrimary">Saqlash</button></div></form></Modal>}
function Modal({title,eyebrow,onClose,children}:{title:string;eyebrow:string;onClose:()=>void;children:any}){return <div className="modalShade" onMouseDown={onClose}><div className="proModal" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><span className="proEyebrow">{eyebrow}</span><h2>{title}</h2></div><button onClick={onClose}>×</button></div>{children}</div></div>}
