import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { MetricCard } from "./AdminUIComponents";

export type BroadcastMsg = { id:string; title:string; body:string; imageUrl?:string; imageCount?:number; target:string; sentAt:string; recipientsCount:number; failedCount?:number };
type TelegramChat = { chat_id:string|number; title:string; username?:string|null; chat_type:string; bot_status:string; can_post_messages:boolean; active:boolean; updated_at:string; error?:string };
type ApiResponse = { success?:boolean; message?:string; data?:any };
type SelectedImage = { id:string; dataUrl:string; name:string };
type TargetMode = "channel"|"group"|"bot"|"groups"|"channels"|"all";

const API=(import.meta.env.VITE_API_URL||"https://guli-lingerie-api.onrender.com").replace(/\/$/,"");
const MINI_APP_URL="https://vite-react-seven-inky-10.vercel.app/?tgapp=v20260829";
function adminRequest(path:string,options:RequestInit={}){const token=sessionStorage.getItem("guli_admin_token")||"";const base=(sessionStorage.getItem("guli_custom_api_url")||API).replace(/\/$/,"");return fetch(`${base}${path}`,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...(options.headers||{})}});}
async function prepareImage(file:File):Promise<SelectedImage>{const raw=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||""));r.onerror=()=>reject(new Error("Rasmni o'qib bo'lmadi"));r.readAsDataURL(file)});try{const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const x=new Image();x.onload=()=>resolve(x);x.onerror=()=>reject(new Error("Rasm formati qo'llab-quvvatlanmadi"));x.src=raw});const max=1400,scale=Math.min(1,max/Math.max(image.naturalWidth||image.width,image.naturalHeight||image.height));if(scale===1&&raw.length<=700000)return{id:`${Date.now()}-${Math.random()}`,dataUrl:raw,name:file.name};const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round((image.naturalWidth||image.width)*scale));canvas.height=Math.max(1,Math.round((image.naturalHeight||image.height)*scale));const ctx=canvas.getContext("2d");if(!ctx)return{id:`${Date.now()}-${Math.random()}`,dataUrl:raw,name:file.name};ctx.drawImage(image,0,0,canvas.width,canvas.height);return{id:`${Date.now()}-${Math.random()}`,dataUrl:canvas.toDataURL("image/jpeg",0.78),name:file.name}}catch{return{id:`${Date.now()}-${Math.random()}`,dataUrl:raw,name:file.name}}}

const modeInfo:Record<TargetMode,{icon:string;title:string;desc:string}>={channel:{icon:"📣",title:"Kanal",desc:"Bitta kanalga yuborish"},group:{icon:"👥",title:"Guruh",desc:"Bitta guruhga yuborish"},bot:{icon:"🤖",title:"Bot",desc:"Telegram bot foydalanuvchilari"},groups:{icon:"👥",title:"Mavjud guruhlar",desc:"Tanlangan guruhlarga yuborish"},channels:{icon:"📣",title:"Mavjud kanallar",desc:"Tanlangan kanallarga yuborish"},all:{icon:"🚀",title:"Barchaga",desc:"Guruh + kanal + bot foydalanuvchilari"}};

export function AdminNotificationsTab({notify}:{notify:(m:string)=>void}){
  const [broadcasts,setBroadcasts]=useState<BroadcastMsg[]>(()=>{try{const x=JSON.parse(localStorage.getItem("guli_broadcast_announcements")||"[]");return Array.isArray(x)?x:[]}catch{return[]}});
  const [chats,setChats]=useState<TelegramChat[]>([]),[loading,setLoading]=useState(false),[checking,setChecking]=useState(false),[sending,setSending]=useState(false),[modal,setModal]=useState(false);
  const [title,setTitle]=useState(""),[body,setBody]=useState(""),[buttonText,setButtonText]=useState("🛍️ Online Marketni Ochish"),[target,setTarget]=useState<TargetMode>("group"),[selectedGroups,setSelectedGroups]=useState<string[]>([]),[selectedChannels,setSelectedChannels]=useState<string[]>([]),[lastError,setLastError]=useState(""),[botStatus,setBotStatus]=useState("unknown" as "unknown"|"ok"|"error");
  const [mainImage,setMainImage]=useState<SelectedImage|null>(null),[additionalImages,setAdditionalImages]=useState<SelectedImage[]>([]),[imageUrl,setImageUrl]=useState("");
  const mainRef=useRef<HTMLInputElement>(null),extraRef=useRef<HTMLInputElement>(null);
  const persist=(x:BroadcastMsg[])=>{setBroadcasts(x);localStorage.setItem("guli_broadcast_announcements",JSON.stringify(x));};
  const loadChats=useCallback(async()=>{setLoading(true);try{const r=await adminRequest("/api/admin/broadcast-chats");const j:ApiResponse=await r.json().catch(()=>({}));if(!r.ok||j.success===false)throw new Error(j.message||`Server xatosi (${r.status})`);setChats(Array.isArray(j.data?.chats)?j.data.chats:[])}catch(e){notify(e instanceof Error?e.message:"Telegram chatlarini yuklab bo'lmadi")}finally{setLoading(false)}},[notify]);
  useEffect(()=>{loadChats()},[loadChats]);
  const verifyChats=async()=>{setChecking(true);try{const r=await adminRequest("/api/admin/broadcast-chats/verify",{method:"POST"});const j:ApiResponse=await r.json().catch(()=>({}));if(!r.ok||j.success===false)throw new Error(j.message||`Server xatosi (${r.status})`);await loadChats();notify("Telegram guruh va kanallari qayta tekshirildi ✅")}catch(e){notify(e instanceof Error?e.message:"Chatlarni tekshirishda xatolik")}finally{setChecking(false)}};
  const checkBot=async()=>{setChecking(true);try{const r=await adminRequest("/api/admin/telegram-config/test");const j:ApiResponse=await r.json().catch(()=>({}));if(!r.ok||j.success===false)throw new Error(j.message||`Server xatosi (${r.status})`);setBotStatus("ok");await loadChats();notify(`Telegram bot ishlayapti${j.data?.botUsername?` @${j.data.botUsername}`:""} ✅`)}catch(e){setBotStatus("error");notify(e instanceof Error?e.message:"Botni tekshirishda xatolik")}finally{setChecking(false)}};
  const reset=()=>{setTitle("");setBody("");setButtonText("🛍️ Online Marketni Ochish");setTarget("group");setSelectedGroups([]);setSelectedChannels([]);setMainImage(null);setAdditionalImages([]);setImageUrl("");setLastError("");if(mainRef.current)mainRef.current.value="";if(extraRef.current)extraRef.current.value=""};
  const openCreate=()=>{reset();setModal(true)};
  const chooseMain=async(files:FileList|null)=>{const f=files?.[0];if(!f)return;try{setMainImage(await prepareImage(f))}catch(e){notify(e instanceof Error?e.message:"Rasmni yuklab bo'lmadi")}};
  const chooseExtra=async(files:FileList|null)=>{if(!files?.length)return;const slots=Math.max(0,9-additionalImages.length);try{const p=await Promise.all(Array.from(files).slice(0,slots).map(prepareImage));setAdditionalImages(x=>[...x,...p])}catch(e){notify(e instanceof Error?e.message:"Qo'shimcha rasmlarni yuklab bo'lmadi")}};
  const groups=useMemo(()=>chats.filter(c=>["group","supergroup"].includes(c.chat_type)),[chats]);
  const channels=useMemo(()=>chats.filter(c=>c.chat_type==="channel"),[chats]);
  const postableGroups=groups.filter(c=>c.active&&c.can_post_messages),postableChannels=channels.filter(c=>c.active&&c.can_post_messages);
  const toggle=(setter:React.Dispatch<React.SetStateAction<string[]>>,id:string)=>setter(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
  const images=[mainImage?.dataUrl||imageUrl.trim(),...additionalImages.map(x=>x.dataUrl)].filter(Boolean);
  const sendBroadcast=async(e:React.FormEvent)=>{e.preventDefault();if(!title.trim()&&!body.trim())return notify("Reklama matnini kiriting");if((target==="group"&&!selectedGroups.length)||(target==="channel"&&!selectedChannels.length)||(target==="groups"&&!selectedGroups.length)||(target==="channels"&&!selectedChannels.length))return notify("Avval yuboriladigan chatni tanlang");if(!images.length&&additionalImages.length)return notify("Asosiy rasmni tanlang");if(images.reduce((a,x)=>a+x.length,0)>3600000)return notify("Rasmlar hajmi juda katta");setSending(true);setLastError("");try{const r=await adminRequest("/api/admin/broadcast-telegram",{method:"POST",body:JSON.stringify({title:title.trim(),body:body.trim(),imageUrls:images,target,selectedGroupIds:selectedGroups,selectedChannelIds:selectedChannels,buttonText:buttonText.trim()||"🛍️ Online Marketni Ochish",buttonUrl:MINI_APP_URL})});const j:ApiResponse=await r.json().catch(()=>({}));if(!r.ok||j.success!==true)throw new Error(j.message||`Reklama yuborilmadi (${r.status})`);const sent=Number(j.data?.sent||0),failed=Number(j.data?.failed||0);const record:BroadcastMsg={id:`BC-${Date.now()}`,title:title.trim(),body:body.trim(),imageUrl:imageUrl||undefined,imageCount:images.length,target,sentAt:new Date().toISOString(),recipientsCount:sent,failedCount:failed};persist([record,...broadcasts]);setModal(false);notify(j.message||`Reklama ${sent} ta chatga yuborildi ✅`);await loadChats()}catch(e){const m=e instanceof Error?e.message:"Reklama yuborishda xatolik";setLastError(m);notify(`❌ ${m}`)}finally{setSending(false)}};
  const label=(t:string)=>t==="groups"?"👥 Tanlangan guruhlar":t==="channels"?"📣 Tanlangan kanallar":t==="bot"?"🤖 Bot foydalanuvchilari":t==="all"?"🚀 Barchasi":t==="group"?"👥 Guruh":"📣 Kanal";
  return <div className="dash" style={{display:"flex",flexDirection:"column",gap:18}}>
    <div className="metricGrid"><MetricCard label="Bot admin chatlar" value={`${postableGroups.length+postableChannels.length} ta`} icon="👥" tone="rose"/><MetricCard label="Guruhlar" value={`${postableGroups.length} ta`} icon="👥"/><MetricCard label="Kanallar" value={`${postableChannels.length} ta`} icon="📣"/><MetricCard label="Bot holati" value={botStatus==="ok"?"Online":botStatus==="error"?"Xato":"Tekshirilmagan"} icon={botStatus==="ok"?"✅":"🔎"}/></div>
    <section className="proPanel" style={{background:"linear-gradient(135deg,#4f46e5 0%,#3730a3 100%)",color:"#fff",padding:22,borderRadius:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:12}}><div><span style={{fontSize:11,fontWeight:800,letterSpacing:1,color:"#c7d2fe"}}>TELEGRAM BROADCAST V2</span><h2 style={{margin:"6px 0",color:"#fff"}}>📢 Reklama va xabarnomalar</h2><p style={{margin:0,fontSize:13,color:"#e0e7ff"}}>Private guruhlar Telegram orqali real tekshiriladi. Har bir reklama faqat tanlangan auditoriyaga yuboriladi.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="button" onClick={checkBot} disabled={checking} style={{padding:"10px 14px",borderRadius:11,border:"1px solid rgba(255,255,255,.35)",background:"rgba(255,255,255,.14)",color:"#fff",fontWeight:700}}>🤖 Botni tekshirish</button><button type="button" onClick={verifyChats} disabled={checking} style={{padding:"10px 14px",borderRadius:11,border:0,background:"#fff",color:"#3730a3",fontWeight:800}}>♻️ Chatlarni tekshirish</button><button type="button" onClick={openCreate} style={{padding:"10px 16px",borderRadius:11,border:0,background:"#fff",color:"#3730a3",fontWeight:800}}>🚀 Yangi reklama</button></div></div></section>
    <section className="proPanel"><div className="panelHead"><div><span className="proEyebrow">ACTIVE TELEGRAM TARGETS</span><h2>Guruhlar va kanallar ({postableGroups.length+postableChannels.length})</h2></div><button type="button" className="proPrimary secondary" onClick={loadChats} disabled={loading}>🔄 Yangilash</button></div>{!chats.length?<p style={{color:"#64748b"}}>Bot admin bo‘lgan Telegram chatlari hali topilmadi. Botni guruhga admin qilib qo‘shing — private guruh ham avtomatik ro‘yxatga olinadi.</p>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(250px,1fr))",gap:10,marginTop:12}}>{chats.map(c=><div key={String(c.chat_id)} style={{padding:13,borderRadius:13,background:c.active&&c.can_post_messages?"#f8fafc":"#fff7ed",border:"1px solid #e2e8f0"}}><b>{c.chat_type==="channel"?"📣":"👥"} {c.title||"Telegram chat"}</b><div style={{fontSize:11,color:"#64748b",marginTop:5}}>ID: {c.chat_id}{c.username?` · @${c.username}`:""}</div><span style={{display:"inline-block",marginTop:7,fontSize:10,padding:"3px 7px",borderRadius:20,background:c.active&&c.can_post_messages?"#dcfce7":"#fee2e2",color:c.active&&c.can_post_messages?"#166534":"#991b1b",fontWeight:700}}>{c.active&&c.can_post_messages?"🟢 Post qilish mumkin":"🔴 Post mumkin emas"}</span></div>)}</div>}</section>
    <section className="proPanel tablePanel"><div className="panelHead"><div><span className="proEyebrow">REAL SEND HISTORY</span><h2>Yuborilgan reklamalar ({broadcasts.length})</h2></div></div>{!broadcasts.length?<p style={{color:"#64748b"}}>Hali reklama yuborilmagan.</p>:<div className="tableScroll"><table><thead><tr><th>ID</th><th>Sarlavha</th><th>Auditoriya</th><th>Rasm</th><th>Yuborildi</th><th>Xato</th><th>Vaqt</th></tr></thead><tbody>{broadcasts.map(b=><tr key={b.id}><td><b className="promoCode">{b.id.slice(-8)}</b></td><td><b>{b.title||"(Sarlavhasiz)"}</b><div className="broadcastBodyPreview">{b.body}</div></td><td>{label(b.target)}</td><td>{b.imageCount?`🖼️ ${b.imageCount}`:"—"}</td><td><span className="pill bluePill">✈️ {b.recipientsCount}</span></td><td>{b.failedCount||"—"}</td><td>{new Date(b.sentAt).toLocaleString("uz-UZ",{dateStyle:"short",timeStyle:"short"})}</td></tr>)}</tbody></table></div>}</section>
    {modal&&<div className="modalShade" onMouseDown={()=>!sending&&setModal(false)}><div className="proModal" style={{maxWidth:720}} onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><span className="proEyebrow">NEW BROADCAST</span><h2>📢 Yangi reklama</h2></div><button type="button" onClick={()=>setModal(false)} disabled={sending}>×</button></div><form onSubmit={sendBroadcast}>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:8,marginBottom:16}}>{(Object.keys(modeInfo) as TargetMode[]).map(m=><button key={m} type="button" onClick={()=>setTarget(m)} style={{textAlign:"left",padding:12,borderRadius:12,border:target===m?"2px solid #4f46e5":"1px solid #e2e8f0",background:target===m?"#eef2ff":"#fff",cursor:"pointer"}}><div style={{fontSize:20}}>{modeInfo[m].icon}</div><b>{modeInfo[m].title}</b><div style={{fontSize:10,color:"#64748b",marginTop:3}}>{modeInfo[m].desc}</div></button>)}</div>
      {(target==="group"||target==="groups")&&<div style={{padding:12,borderRadius:12,background:"#f8fafc",border:"1px solid #e2e8f0",marginBottom:14}}><b>👥 {target==="group"?"Guruhni tanlang":"Mavjud guruhlar — tanlang"}</b><div style={{display:"grid",gap:7,marginTop:8}}>{postableGroups.length?postableGroups.map(c=><label key={String(c.chat_id)} style={{display:"flex",alignItems:"center",gap:8,padding:9,borderRadius:9,background:"#fff",border:"1px solid #e2e8f0",cursor:"pointer"}}><input type={target==="group"?"radio":"checkbox"} name="group-target" checked={selectedGroups.includes(String(c.chat_id))} onChange={()=>target==="group"?setSelectedGroups([String(c.chat_id)]):toggle(setSelectedGroups,String(c.chat_id))}/><span>👥 <b>{c.title}</b><small style={{display:"block",color:"#64748b"}}>{c.chat_id}{c.username?` · @${c.username}`:""}</small></span><em style={{marginLeft:"auto",fontSize:10,color:"#166534"}}>🟢 Post mumkin</em></label>):<span style={{color:"#991b1b"}}>Post qilish mumkin bo‘lgan guruh topilmadi.</span>}</div></div>}
      {(target==="channel"||target==="channels")&&<div style={{padding:12,borderRadius:12,background:"#f8fafc",border:"1px solid #e2e8f0",marginBottom:14}}><b>📣 {target==="channel"?"Kanalni tanlang":"Mavjud kanallar — tanlang"}</b><div style={{display:"grid",gap:7,marginTop:8}}>{postableChannels.length?postableChannels.map(c=><label key={String(c.chat_id)} style={{display:"flex",alignItems:"center",gap:8,padding:9,borderRadius:9,background:"#fff",border:"1px solid #e2e8f0",cursor:"pointer"}}><input type={target==="channel"?"radio":"checkbox"} name="channel-target" checked={selectedChannels.includes(String(c.chat_id))} onChange={()=>target==="channel"?setSelectedChannels([String(c.chat_id)]):toggle(setSelectedChannels,String(c.chat_id))}/><span>📣 <b>{c.title}</b><small style={{display:"block",color:"#64748b"}}>{c.chat_id}{c.username?` · @${c.username}`:""}</small></span><em style={{marginLeft:"auto",fontSize:10,color:"#166534"}}>🟢 Post mumkin</em></label>):<span style={{color:"#991b1b"}}>Post qilish mumkin bo‘lgan kanal topilmadi.</span>}</div></div>}
      {target==="bot"&&<div style={{padding:12,borderRadius:12,background:"#f8fafc",marginBottom:14,color:"#334155"}}>🤖 <b>Bot foydalanuvchilari</b><br/><small>Supabase'dagi Telegram foydalanuvchilariga yuboriladi.</small></div>}
      {target==="all"&&<div style={{padding:12,borderRadius:12,background:"#fff7ed",border:"1px solid #fed7aa",marginBottom:14}}>🚀 <b>Barchaga</b> — mavjud post qilinadigan guruhlar, kanallar va Telegram bot foydalanuvchilari. Duplicate ID'lar bir marta yuboriladi.</div>}
      <div className="formGrid"><label>Reklama sarlavhasi<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="🌸 Yangi kolleksiya!"/></label><label className="fullRow">Reklama matni<textarea rows={5} required value={body} onChange={e=>setBody(e.target.value)} placeholder="Aksiya, chegirma yoki mahsulot haqida..."/></label>
      <div className="fullRow"><span style={{fontSize:12,fontWeight:700}}>🖼️ Rasmlar ({images.length}/10)</span><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(110px,1fr))",gap:8,marginTop:8}}><button type="button" onClick={()=>mainRef.current?.click()} disabled={sending} style={{minHeight:100,border:"1.5px dashed #cbd5e1",borderRadius:12,background:"#f8fafc"}}>🖼️<br/><b>Asosiy rasm</b></button>{mainImage&&<div style={{position:"relative"}}><img src={mainImage.dataUrl} alt="" style={{width:"100%",height:100,objectFit:"cover",borderRadius:12}}/><button type="button" onClick={()=>setMainImage(null)} style={{position:"absolute",right:4,top:4}}>×</button></div>}{additionalImages.map((x,i)=><div key={x.id} style={{position:"relative"}}><img src={x.dataUrl} alt="" style={{width:"100%",height:100,objectFit:"cover",borderRadius:12}}/><button type="button" onClick={()=>setAdditionalImages(a=>a.filter(v=>v.id!==x.id))} style={{position:"absolute",right:4,top:4}}>×</button><small style={{position:"absolute",bottom:3,left:4,background:"rgba(0,0,0,.6)",color:"#fff",padding:2}}>#{i+2}</small></div>)}{mainImage&&additionalImages.length<9&&<button type="button" onClick={()=>extraRef.current?.click()} disabled={sending} style={{minHeight:100,border:"1.5px dashed #cbd5e1",borderRadius:12,background:"#fff"}}>➕<br/><b>Qo‘shimcha</b></button>}</div><input ref={mainRef} hidden type="file" accept="image/*" onChange={e=>chooseMain(e.target.files)}/><input ref={extraRef} hidden type="file" accept="image/*" multiple onChange={e=>chooseExtra(e.target.files)}/><input value={imageUrl} onChange={e=>setImageUrl(e.target.value)} placeholder="URL orqali asosiy rasm (ixtiyoriy)" style={{marginTop:8}}/></div>
      <label className="fullRow">Tugma matni<input value={buttonText} onChange={e=>setButtonText(e.target.value)}/></label></div>{lastError&&<div style={{marginTop:12,padding:12,borderRadius:10,background:"#fef2f2",color:"#991b1b"}}>❌ {lastError}</div>}<div className="modalActions" style={{marginTop:18}}><button type="button" onClick={()=>setModal(false)} disabled={sending}>Bekor qilish</button><button type="submit" className="proPrimary" disabled={sending}>{sending?"⏳ Yuborilmoqda...":"🚀 Reklamani yuborish"}</button></div></form></div></div>}
  </div>;
}
