import { useEffect, useRef, useState } from "react";
import { MetricCard } from "./AdminUIComponents";
import { sendAdminReply, updateConversationMetadata } from "../../utils/chatSync";

type PaymentTx = { id:string; dbId?:string; telegramId?:number; orderId:string; customerName:string; amount:number; method:"card"|"click"|"payme"; status:"verified"|"pending"|"rejected"; paymentStatus?:string; receiptUrl:string; receiptMime?:string; timestamp:string };
const API=(import.meta.env.VITE_API_URL||"https://guli-lingerie-api.onrender.com").replace(/\/$/,"");
const money=(n:number)=>`${Math.round(Number(n)||0).toLocaleString("uz-UZ")} so'm`;
const methodOf=(v:any):PaymentTx["method"]=>/click/i.test(String(v))?"click":/payme/i.test(String(v))?"payme":"card";
const stateOf=(o:any):PaymentTx["status"]=>{const p=String(o?.payment_status||"").toLowerCase();if(p==="rejected")return"rejected";if(p==="verified")return"verified";if(p==="pending"||p==="receipt_uploaded")return"pending";return !p&&["Qabul qilindi","Yetkazildi"].includes(String(o?.status||""))?"verified":"pending";};

async function getReceipt(id:string,t:string){if(!id)return null;try{const r=await fetch(`${API}/api/admin/orders/${encodeURIComponent(id)}/payment-receipt`,{headers:{Authorization:`Bearer ${t}`}});const j=await r.json().catch(()=>({}));return r.ok&&j.success?j.data:null;}catch{return null;}}

export function AdminPaymentsTab({notify}:{notify:(m:string)=>void}){
 const [payments,setPayments]=useState<PaymentTx[]>([]),[filterMethod,setFilterMethod]=useState("all"),[preview,setPreview]=useState<PaymentTx|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState<string|null>(null),[selected,setSelected]=useState<PaymentTx|null>(null);
 const input=useRef<HTMLInputElement|null>(null); const token=()=>sessionStorage.getItem("guli_admin_token")||"";
  const load=async()=>{const t=token();if(!t)return;setLoading(true);try{const r=await fetch(`${API}/api/admin/orders?limit=500`,{headers:{Authorization:`Bearer ${t}`}});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw Error(j.message||`Server xatosi (${r.status})`);const rows=Array.isArray(j.data)?j.data:[];const out=await Promise.all(rows.map(async(o:any)=>{const rec=(o.payment_receipt_path||o.receipt_url||o.payment_status==="receipt_uploaded"||o.payment_status==="paid"||o.payment==="card")?await getReceipt(String(o.id||o.order_number||""),t):null;const finalUrl=rec?.receipt_url||o.receipt_url||o.receiptUrl||rec?.url||"";return{id:`TX-${String(o.id||o.order_number).slice(-6)}`,dbId:String(o.id||""),telegramId:Number(o.telegram_id)||undefined,orderId:String(o.order_number||o.id||"—"),customerName:[o.first_name,o.last_name].filter(Boolean).join(" ")||o.customer_name||o.first_name||o.username||o.phone||"Mijoz",amount:Number(o.total||0),method:methodOf(o.payment),status:stateOf(o),paymentStatus:String(o.payment_status||""),receiptUrl:finalUrl,receiptMime:finalUrl.toLowerCase().endsWith(".pdf")?"application/pdf":"image/*",timestamp:o.created_at||new Date().toISOString()} as PaymentTx;}));setPayments(out);}catch(e){notify(e instanceof Error?e.message:"To‘lovlarni yuklashda xatolik");}finally{setLoading(false);}};
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(),10000);return()=>window.clearInterval(id);},[]);
 const changePayment=async(tx:PaymentTx,status:"verified"|"rejected")=>{if(!tx.dbId)return notify("DB ID topilmadi");setBusy(tx.id);try{const t=token();let r=await fetch(`${API}/api/admin/orders/${encodeURIComponent(tx.dbId)}/payment`,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({payment_status:status})});let j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw Error(j.message||"To‘lov statusini saqlab bo‘lmadi");const orderStatus=status==="verified"?"Qabul qilindi":"Bekor qilindi";r=await fetch(`${API}/api/admin/orders/${encodeURIComponent(tx.dbId)}`,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({status:orderStatus})});j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw Error(j.message||"Buyurtma statusini saqlab bo‘lmadi");setPayments(x=>x.map(p=>p.id===tx.id?{...p,status,paymentStatus:status}:p));setPreview(p=>p?.id===tx.id?{...p,status,paymentStatus:status}:p);const recipient=tx.telegramId?String(tx.telegramId):"guest-user";const msg=status==="verified"?`🔔 №${tx.orderId} buyurtmangizning karta to‘lovi tasdiqlandi. Status: "Qabul qilindi". Rahmat! 🌸`:`⚠️ №${tx.orderId} buyurtmangizning to‘lov cheki rad etildi.`;sendAdminReply(recipient,msg);updateConversationMetadata(recipient,{lastOrderStatus:orderStatus,lastOrderNumber:tx.orderId,lastOrderTotal:tx.amount});notify(status==="verified"?"Chek tasdiqlandi ✓":"Chek rad etildi ✕");await load();}catch(e){notify(e instanceof Error?e.message:"To‘lov statusida xatolik");}finally{setBusy(null);}};
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0],tx=selected;if(!f||!tx?.dbId)return;if(!f.type.startsWith("image/")&&f.type!=="application/pdf")return notify("JPG, PNG, WEBP yoki PDF yuklang");if(f.size>6*1024*1024)return notify("Chek 6 MB dan kichik bo‘lishi kerak");setBusy(tx.id);try{const data=String(await new Promise<string>((res,rej)=>{const rd=new FileReader();rd.onload=()=>res(String(rd.result||""));rd.onerror=rej;rd.readAsDataURL(f)})).split(",")[1]||"";const ext=f.name.split(".").pop()||"jpg";const r=await fetch(`${API}/api/admin/orders/${encodeURIComponent(tx.dbId)}/payment-receipt`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token()}`},body:JSON.stringify({data,mimeType:f.type,extension:ext})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw Error(j.message||"Chekni saqlab bo‘lmadi");notify(`№${tx.orderId} uchun chek serverga saqlandi ✓`);await load();}catch(e){notify(e instanceof Error?e.message:"Chekni saqlashda xatolik");}finally{setBusy(null);setSelected(null);e.target.value="";}};
 const filtered=payments.filter(p=>filterMethod==="all"||p.method===filterMethod),verified=payments.filter(p=>p.status==="verified").reduce((s,p)=>s+p.amount,0),pending=payments.filter(p=>p.status==="pending").length;
 const filters:Array<[string,string]>=[["all","Barcha karta to‘lovlari"],["card","💳 Karta o‘tkazmasi"],["click","📲 Click"],["payme","📱 Payme"]];
 return <div className="dash"><input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={upload}/><div className="metricGrid"><MetricCard label="Tasdiqlangan karta to‘lovlari" value={money(verified)} icon="💳" tone="rose"/><MetricCard label="Kutilayotgan cheklar" value={`${pending} ta`} icon="⏳"/><MetricCard label="Click / Payme Online" value="Faol" icon="⚡"/><MetricCard label="Chek nazorati" value="Faol" icon="🛡️"/></div>
 <section className="proPanel tablePanel"><div className="filterRow">{filters.map(([v,label])=><button key={v} type="button" className={filterMethod===v?"active":""} onClick={()=>setFilterMethod(v)}>{label}</button>)}</div><div className="panelHead"><div><span className="proEyebrow">CARD PAYMENTS & RECEIPTS</span><h2>Kartadan to‘lovlar va Cheklar ({filtered.length}) {loading?"⏳":""}</h2></div><button type="button" className="proPrimary secondary" onClick={()=>void load()}>🔄 Yangilash</button></div>
 <div className="tableScroll"><table><thead><tr><th>Chek rasmi</th><th>Tranzaksiya</th><th>Buyurtma №</th><th>Mijoz</th><th>Summa</th><th>Usul</th><th>Status</th><th>Vaqt</th><th>Amallar</th></tr></thead><tbody>{filtered.map(tx=><tr key={tx.id}><td><button type="button" onClick={()=>setPreview(tx)} style={{width:58,height:58,padding:0,borderRadius:10,overflow:"hidden",border:"2px solid #e2e8f0",background:"#f8fafc"}}>{tx.receiptUrl?(tx.receiptMime==="application/pdf"?"📄":<img src={tx.receiptUrl} alt="Chek" style={{width:"100%",height:"100%",objectFit:"cover"}}/>):"🧾"}</button></td><td><b className="promoCode">{tx.id}</b></td><td><b>{tx.orderId}</b></td><td>{tx.customerName}</td><td><b style={{color:"#059669"}}>{money(tx.amount)}</b></td><td><span className="pill">{tx.method==="card"?"💳 Karta":tx.method==="click"?"📲 Click":"📱 Payme"}</span></td><td><span className={`pill ${tx.status==="pending"?"mutedPill":tx.status==="rejected"?"dangerPill":""}`}>{tx.status==="verified"?"✓ Tasdiqlangan":tx.status==="rejected"?"✕ Rad etilgan":tx.paymentStatus==="receipt_uploaded"?"🧾 Chek yuklangan":"⏳ Tekshirilmoqda"}</span></td><td>{new Date(tx.timestamp).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</td><td><div className="actions" style={{justifyContent:"flex-end",gap:6}}><button type="button" className="proPrimary secondary miniBtn" disabled={busy===tx.id} onClick={()=>{setSelected(tx);input.current?.click()}}>📷 Chek yuklash</button>{tx.status==="pending"&&<><button type="button" className="proPrimary miniBtn" disabled={busy===tx.id} onClick={()=>void changePayment(tx,"verified")}>Tasdiqlash ✓</button><button type="button" className="dangerBtn" disabled={busy===tx.id} onClick={()=>void changePayment(tx,"rejected")}>Rad etish</button></>}</div></td></tr>)}</tbody></table></div></section>
 {preview&&<div style={{position:"fixed",inset:0,background:"rgba(15,23,42,.86)",zIndex:99999,display:"grid",placeItems:"center",padding:16}} onClick={()=>setPreview(null)}><div style={{position:"relative",maxWidth:760,width:"100%",maxHeight:"92vh",overflow:"auto",background:"#fff",borderRadius:24,padding:24}} onClick={e=>e.stopPropagation()}><button type="button" onClick={()=>setPreview(null)} style={{position:"absolute",right:16,top:16,zIndex:2,border:0,borderRadius:"50%",width:38,height:38,fontSize:20}}>✕</button><span className="proEyebrow">TO‘LOV CHEKI</span><h2>№ {preview.orderId} — To‘lov cheki</h2><div style={{background:"#0f172a",borderRadius:16,minHeight:300,overflow:"hidden",display:"grid",placeItems:"center"}}>{preview.receiptUrl?(preview.receiptMime==="application/pdf"?<iframe title="Chek" src={preview.receiptUrl} style={{width:"100%",height:"60vh",border:0}}/>:<img src={preview.receiptUrl} alt="Chek" style={{maxWidth:"100%",maxHeight:"60vh",objectFit:"contain"}}/>):<div style={{color:"#fff"}}>🧾 Chek yuklanmagan</div>}</div><div style={{display:"flex",gap:10,marginTop:16,flexWrap:"wrap"}}>{preview.status==="pending"&&<><button type="button" className="proPrimary" onClick={()=>void changePayment(preview,"verified")}>✓ Chekni tasdiqlash</button><button type="button" className="dangerBtn" onClick={()=>void changePayment(preview,"rejected")}>✕ Rad etish</button></>}{preview.receiptUrl&&<a href={preview.receiptUrl} target="_blank" rel="noreferrer" download={`Chek_${preview.orderId}`} style={{padding:"10px 16px",borderRadius:10,background:"#f1f5f9",textDecoration:"none",fontWeight:700}}>📥 Chekni yuklab olish</a>}</div></div></div>}
 </div>;
}
