-- GULI reviews: realtime uses a public-safe event table.
-- product_reviews contains Telegram/order identity and is never directly readable by clients.

create table if not exists public.review_events (
  id bigint generated by default as identity primary key,
  product_id uuid not null,
  product_code text,
  event_type text not null check (event_type in ('INSERT','UPDATE','DELETE')),
  occurred_at timestamptz not null default now()
);

create index if not exists idx_review_events_product_time
  on public.review_events (product_id, occurred_at desc);

alter table public.review_events enable row level security;
drop policy if exists review_events_public_read on public.review_events;
create policy review_events_public_read on public.review_events for select to public using (true);
grant select on public.review_events to anon, authenticated;

create or replace function public.emit_review_event()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'DELETE' then
    insert into public.review_events(product_id, product_code, event_type) values (old.product_id, old.product_code, 'DELETE');
    return old;
  elsif tg_op = 'UPDATE' then
    insert into public.review_events(product_id, product_code, event_type) values (new.product_id, new.product_code, 'UPDATE');
    return new;
  else
    insert into public.review_events(product_id, product_code, event_type) values (new.product_id, new.product_code, 'INSERT');
    return new;
  end if;
end;
$$;

revoke all on function public.emit_review_event() from public, anon, authenticated;
drop trigger if exists trg_product_reviews_event on public.product_reviews;
create trigger trg_product_reviews_event after insert or update or delete on public.product_reviews
for each row execute function public.emit_review_event();

drop policy if exists product_reviews_public_read on public.product_reviews;
revoke select on public.product_reviews from anon, authenticated;

do $$
begin
  if exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='product_reviews') then
    alter publication supabase_realtime drop table public.product_reviews;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='review_events') then
    alter publication supabase_realtime add table public.review_events;
  end if;
end $$;
